ex-em/EVUI

src/components/tabs/tabs.vue

###############################
1. 컴포넌트 등록이 된 후 동일한 컴포넌트를 추가 시 contents 영역에 새롭게 추가되지 않는 문제 수정
2. component 태그에 props 값 전달을 위해 v-bind 추가

[#194] Tab Panel 기능 개발

---

src/components/button/button.vue

1. icon, text가 존재하는 부분의 내부 공간의 수평 정렬이 없어 min-width 적용 시 가운데 정렬안되는 문제 수정

[#126] Button 내부 컨텐츠 정렬 관련 수정

---

home/guide/views/examples/tab/tab-default.vue
src/components/tabs/tabs.vue

1. v-model로 전달된 배열의 참조가 남아있어 정상적으로 탭 추가에 대한 인지가 안되는 문제 수정
2. change-tab 이벤트 발생시 전달되는 인자에 대한 값이 반대로 되어있어 변경

[#281] Tab 추가 시 Active 관련 버그

---

home/guide/views/examples/loadingmask/loadingmask-custom.vue
home/guide/views/examples/loadingmask/loadingmask-default.vue

- 태그명 ev-loading-mask로 변경
- v-show를 v-if로 변경
- 로딩마스크의 경우 자주 바뀌는 것도 아니고 런타임 시 조건이 바뀌지 않기때문에 v-if로 변경함

[#316] loading mask 태그명, 조건 변경

---

package.json
src/components/datepicker/index.js
src/index.js

- 단독으로 calendar 컴포넌트를 사용하는 경우 오류 발생
- EvCalendar가 누락되어있어 추가하여 단독 컴포넌트로 사용할 수 있도록 함
- vue-i18n 패키지 추가

[#376] calendar 컴포넌트 누락

---

src/components/input/input.number.vue

- 함수형태 변경
- input number box에 v-model로 바인드를 하고 formatterValue() computed에서 currentValue가 변할 때,
상위에 $emit으로 input 이벤트를 걸도록 함

[#382] input number box에 v-model을 사용하도록 로직 변경

---

src/components/radio/radio.vue

============================
- on-change로 변경
- checkbox 컴포넌트에서 체인지 이벤트명 변경하였으나 radio에서는 누락됨

[#401] radio 컴포넌트 체인지 이벤트명 변경

---

src/components/tabs/tabs.vue

============================
- 탭 내부에 <component>태그로 불러온 컴포넌트가 아닌 일반 DOM인 경우 높이가 맞지 않는 현상 수정

[#413] tab 컴포넌트 스타일 변경

---

src/components/input/input.number.vue

#######
- InputNumber 컴포넌트에서 validator 내에서 Number 타입 확인하는 부분 추가함
- isNaN 대신 Number.isNaN()으로 변경

[#382] InputNumber 컴포넌트에서 validator 내에서 Number 타입 확인하는 부분 추가 (#418)

---

src/components/datepicker/calendar.core.js
src/components/datepicker/datepicker.vue

- datepicker 날짜 입력 란의 값을 모두 지우는 경우 calendar 값 초기화 및
현재 날짜의 년/월에 해당하는 페이지로 이동 및 v-model 값 null 처리 로직 추가
- setDateTime의 파라미터는 moment.js 고유의 파라미터를 사용하고 있으며,
이 값의 유효성 검사를 위해 라이브러리 .isValid() 사용

[#445] datepicker, calendar 로직 수정

---

src/components/chart/chart.vue
src/components/selectbox/dropdown.vue
src/components/slider/slider-tooltip.vue
src/components/table/table.filter.vue
src/components/timepicker/timepicker.vue

##########
툴팁 및 드롭다운 등 z-index를 window보다 높게 조정   
- 기존: 툴팁 100 / 윈도우 700
- 변경: 툴팁 850

[#436] z-index 조정

---

src/common/utils.js
src/components/chart/chart.core.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.legend.js
src/components/chart/scale/scale.js

##########
- Resize Bar mousedown 시 left값이 없어 왼쪽에 뜨는 버그
- MaxTip 소수점일 경우 3자리에 컴마처리 되는 버그
- Chart의 넓이에 따라 Time Axis Label이 겹치는 버그
- Graph Data값이 null일 때 Tooltip이 나옴
- mouseout 이벤트가 제대로 트리거되지 않아 Tooltip이 살아남는 버그
- MaxTip 데이터가 0일때 나오지 않음

[#464] Chart 버그 수정

---

src/components/radio/radio.vue

- emit 'on-change' 전에 'input'을 실행하도록 순서 변경

[#467] radio > onChange 내부 로직 순서 변경

---

src/components/chart/scale/scale.js

Axis Scale 시, round 처리가 되면 실제 최대 데이터보다 Axis의 Max가 작아지는 현상이 발생 (작은 숫자의 경우) 하여 올림으로 변경

[#478] 차트 버그 수정

---

src/components/message-box/message-box.js

###################################################
messagebox 쓸때 title 이나 onClosed 필요없다해서 빼고 쓰면
이전에 호출했었던 title 이랑 callback 함수가 실행되는 버그가 있어서
명시를 안해주면 디폴트값을 새로 부여해주도록 수정

[#433] Messagebox > 프로퍼티 명시가 없을 경우, 이전에 사용했던 내용으로 진행되는 버그 수정

---

docs/pages/chart/bar/examples/time.vue
src/components/chart/chart.vue
src/components/chart/element/element.tip.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.tooltip.js

########
- stack chart tooltip시 null값 처리를 0으로 고정하도록 변경
- X축 포인트가 없을 때 fixedIndicator 그리지 않도록 변경
- 툴팁에서 series명 + value값보다 상단 타이틀이 더 넓이가 넓을 시 tooltip이 짤리는 현상 수정
- cloneDeep 옵션으로 watch 기능 개선

[#478] Chart 각종 버그 수정

---

src/components/chart/element/element.tip.js
src/components/chart/scale/scale.js

########
- 이전에 찍혀있던 Indicator값을 좌표로 처리하다보니 Chart의 사이즈가 외부 요건에 의해 달라졌을 때 좌표가 맞지 않게 되어 값을 기억했다가 사이즈에 맞춘 좌표값을 찾도록 변경
- Scale 처리 시, tickSize 계산에 오류가 있어 해당 부분 수정

[#478] Chart 버그 수정

---

package.json

별 차이는 없는데 수동으로 올리시는 것 같길래 한 번 넣어봤습니다.
`> npm run pub:patch` 를 실행하면 `package.json`, `package-lock.json` 파일의 patch 버전이 1 올라갑니다. 계속 실행하면 계속 올라갑니다.
예를 들어 `2.3.5` 까지 올라온 상태에서,
`> npm run pub:patch` 를 실행하면 `package.json`, `package-lock.json` 의 버전은 `2.3.6` 이 됩니다.
`> npm run pub:minor` 를 실행하면, `2.4.0` 이 됩니다. patch 버전을 0 으로 초기화 시키고 minor 버전을 1 올립니다. 
같은 원리로 `> npm run pub:major` 도 진행할 수 있습니다.
`--no-git-tag-version` 은 버전을 올릴 때 태그를 자동으로 생성하는 것을 막아줍니다.
작게보면 숫자 하나만 바꾸는데 굳이 커맨드 명령어를 입력해야하나? 겠지만
조금만 크게보면 명령어를 사용했을 때는 휴먼에러가 발생할 일이 없습니다.

[#519] 프로젝트 버전 변경 커맨드 추가

---

src/components/chart/scale/scale.js

########
- maxValue가 1일 경우, tick을 chart 높이에 따라 Y축 분할 처리하는 부분 보정

[#478] Scale 버그 수정

---

src/components/chart/chart.vue
src/components/chart/scale/scale.step.js

########
- Chart init 예외 처리 추가
- real DOM이 mounting 및 box size가 정리된 상태에서 Chart를 그리기 위해 setTimeout을 사용했으나, setTimeout이 발동되기 전에 Vue가 destroy될 경우 this.evChart가 존재하지 않아 에러가 발생함
- 빈 문자열일 경우 step에서 ellipsis 처리를 할 때 에러가 남

[#478] Chart Bug fix

---

src/components/chart/scale/scale.js

########
- Context의 beginPath, closePath의 위치를 잘못 잡아 계속 덮어쓰는 현상 수정

[#478] Axis Grid Line 버그

---

src/components/chart/model/model.store.js

#########
- 차트 전체 데이터값이 0이고, 데이터 끝 부분에 null이 존재할 경우, domain의 값을 null값에도 적용시키는 이슈 해소

[#478] Chart Bug 수정

---

src/components/chart/chart.vue

#########
- v-resize가 정확하게 동작하지 않는 경우가 있어 추가로 forceUpdate를 넣어
개발자가 강제로 차트를 새로 갱신하도록 한다.

[#478] Chart Update 메소드 추가

---

docs/pages/chart/bar/bar.vue
src/components/chart/plugins/plugins.interaction.js

#########
- tooltip use가 false일 경우 context 참조 부분 예외처리

[#478] Chart Tooltip 버그 수정

---

.eslintrc.js
docs/components/Example.vue
docs/router/index.js
docs/views/PageNotFound.vue
package-lock.json
package.json
vue.config.js

- Docs의 샘플코드 컴포넌트 구성
- 임시로 체크박스 컴포넌트를 샘플로 삼아 코드를 보여줌
- view > 컴포넌트명 > example 폴더 내 존재하는 예시코드들을 raw-loader로 읽은 후 vue-template-compiler를 사용하여 parseComponent한 코드를 추출하는 로직 구현
- vue파일을 raw-loader를 사용하여 읽을 때의 import eslint 처리 및 해당 경로 지정
- highlight.js 라이브러리를 이용하여 코드텍스트에 하이라이트 구현
- page not found 시 router 예외처리 및 임시 vue파일 생성

[#623] Docs 샘플 컴포넌트 구성

---

docs/views/checkbox/example/CheckboxGroup.vue
src/components/checkbox/Checkbox.vue
src/components/checkboxGroup/CheckboxGroup.vue
src/components/radio/Radio.vue

- Checkbox 버튼타입 기능 추가
- DOCS > Checkbox  버튼타입 예제 추가
- DOCS > Checkbox indeterminate 예제 버그 수정
- radio cursor 수정

[#630] Checkbox 버튼타입 기능 추가

---

src/components/textfield/textfield.vue

##########
- 텍스트 필드의 validation 조건이 동적으로 변경될때 use-reg-exp 조건이 변경되어야 하는데, 현재 입력된 텍스트 필드의 value 가 변화가 없으므로 컴포넌트 내부의 validateError 함수를 실행하지 않아 reg exp 의 조건에 맞는 결과를 보여주지 않으므로 use-reg-exp props 에 watch를 걸어 validateError 함수를 실행 하도록 함
- 빈 문자열의 검출이 되지 않는 버그 수정

[#673] textfield RegExp 관련 수정

---

src/components/message-box/message-box.vue

##########
- ev-messagebox 헤더 아이콘 숨김 옵션 추가
- showHeaderIcon 옵션의 default는 true로 헤더 영역의 icon을 보여줌

[#676] ev-messagebox 헤더 아이콘 숨김 옵션(showHeaderIcon) 추가

---

src/components/contextmenu/contextmenu.vue
src/components/contextmenu/contextmenu.wrap.vue

- 포지션 계산할 때, 클릭된 좌표에서 창 가장 자리까지 남은 거리 계산식이 잘못 되어 수정함

[#678] ContextMenu 화면 벗어나는 현상 수정

---

docs/router/index.js
docs/views/messageBox/api/messageBox.md
docs/views/messageBox/example/Default.vue
docs/views/messageBox/props.js
src/components/message/Message.vue
src/components/messageBox/MessageBox.vue
src/components/messageBox/index.js
src/components/notification/Notification.vue
src/components/notification/index.js
src/main.js

- MessageBox 2.0 버전 마이그레이션 및 기능 개선
- 기타 스타일 및 불필요 코드 수정
- docs 샘플 페이지 생성
- message, notification 코드 개선

[#703][3.0] MessageBox 컴포넌트

---

src/components/textfield/textfield.vue

##########
- 컴포넌트 내부 wrapStyle 에서 lineHeight를 지정 하여 textField 의 크기와 text 의 크기를 맞추게 되어 있는데, textarea 타입인 경우에는 row가 여러줄이 되어야 하기 때문에 lineHeight 를 지정 하면 안됨

[#715] textfield > textarea type 인 경우 Style 버그 수정

---

package-lock.json
package.json
src/components/grid/grid.vue

##########
- dom 이 display 되지 않는 상태에서 그리드가 생성 되면 발생 하는 column width 문제를 해결하기 위해 실제 display 를 감지 하는 디렉티브를 추가

[#725][2.0] grid > vue-observe-visibility directive

---

docs/views/tree/api/tree.md
docs/views/tree/example/Default.vue
src/components/textField/TextField.vue
src/components/tree/Tree.vue
src/components/tree/TreeNode.vue

###########
- Filtering 기능 추가하여 스펙 문서 수정(tree.md), 예제 추가(Default.vue)
- Tree, TreeNode 컴포넌트 내에서 스타일 scoped 사용 제거
- filtering 기능 추가
- 검색어가 아예 없을 경우에도 검색이 되어야 하므로 조건 제거(TextField.vue)

[#734][3.0] Tree 컴포넌트 기능 개선(filtering 기능 추가), TextField 컴포넌트의 searchValue() 수정

---

LICENSE
README.md
package-lock.json
package.json
vue.config.js

- 라이브러리로 빌드 시 style을 포함시키는 옵션 설정
- 배포 과정
1) npm run build:lib
2) npm login (admin login, once)
3) package.json > version update
4) npm publish
- package.json 내 vuex, vue-router를 devDep로 변경
- LICENSE 추가

[#753][3.0] NPM PUBLISH

---

src/components/icon/Icon.vue
src/components/icon/index.js
src/style/lib/icon.css
vue.config.js

- EvIcon 컴포넌트에서 폰트를 불러오는 icon.css 파일을 import하는 부분을 vue파일이 아닌 index.js로 변경
- 폰트 경로 수정
- 라이브러리 형태로 빌드 시 fonts의 확장자 파일을 url-loader로 같이 포함하여 묶는 방식으로 변경

[#753][3.0] 라이브러리 빌드 시 폰트가 안나오는 현상 수정

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Column.vue
docs/views/barChart/example/Default.vue
docs/views/barChart/example/Horizontal.vue
docs/views/barChart/example/Stack.vue
docs/views/barChart/example/Time.vue
docs/views/barChart/props.js
package.json
src/components/chart/element/element.bar.js

1. Bar차트의 showValue 옵션 중 'align' 항목 추가
>   - 결과 샘플 https://www.notion.so/f91f4384184b4fa9946ab23230c686e2
2. BarChart API 내용 수정 
>    -  Default: Default 값으로만 표현되도록 추가 지정했던 속성들 모두 제거 후 예제에 필수값만 남김
>   -  Column: showValue > align 예제 포함시킴
>   -  Stack : showValue 예제 제외 시킴
>   - Time: 실시간으로 데이타를 업데이트 하는 예제에만 집중하기 위해 series 줄이고 grid 속성 조정
>   - Horizontal: showValue > align 예제 포함시키고 데이터 값 조정 (0, 적은수, 중간수, 큰수가 모두 보이도록) 
>   - .md : 설명이 내용과 상이하여 조정함
3. 버전 수정
>   - 3.1.11 -> 3.1.13

[3.0] Chart > series > showValue 옵션에 align 항목 추가

---

src/components/slider/uses.js

[#780][3.0] slider 컴포넌트 step, mark 관련 반응형 로직 수정

---

src/components/chart/element/element.bar.js
src/components/chart/element/element.bar.time.js
src/components/chart/element/element.pie.js
src/components/chart/element/element.scatter.js
src/components/chart/plugins/plugins.legend.js

1. Legend영역 series label에서 mouseover -> mouseleave해도 특정 series만 강조하던 효과가 사라지지 않던 현상 제거
2. line 차트 외 다른 차트(bar, scatter, pie)에서는 series label에 mouse over를 해도 특정 series만 강조하는 효과가 나타나지 않아 관련 로직 추가

[3.0] Chart legend 영역에서 Series label mouseleave event handler 이슈

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Gradient.vue
docs/views/barChart/props.js
src/components/chart/element/element.bar.js
src/components/chart/helpers/helpers.canvas.js
src/components/chart/plugins/plugins.legend.js
src/components/chart/plugins/plugins.tooltip.js

- 막대 그리는부분, 마우스 hover시 highlight 처리하는부분,  tooltip, legend 에 그라데이션 처리 로직 추가
- 그라데이션 관련 Sample Code작성

[#786][3.0] Bar Chart 그라데이션 기능 추가

---

docs/views/comboChart/example/LineBar.vue
docs/views/comboChart/example/LineStackBar.vue
docs/views/comboChart/example/StackLineBar.vue
docs/views/comboChart/example/StackLineStackBar.vue
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/Default.vue
docs/views/scatterChart/api/scatterChart.md
docs/views/scatterChart/example/Default.vue
docs/views/scatterChart/example/Event.vue
docs/views/scatterChart/props.js
src/components/chart/Chart.vue
src/components/chart/chart.core.js
src/components/chart/element/element.scatter.js
src/components/chart/helpers/helpers.canvas.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/uses.js

- scatter chart 드래그 기능 추가
- lineChart.md 오타 수정
- 드래그 추가에 따른 scatterChart.md, example 화면 추가에 따른 수정
- scatterChart example - default 화면에 X axis 갯수, series 갯수 변경 기능 추가
- scatterChart pointStyle 중 'dash' 삭제 (드래그 이벤트 스펙과 상이한 점이있어서, 데이터 좌표가 중앙에 있지 않음)
- 차트 예제 중 setInterval 인데 clearTimeout 처리한 부분 => clearInterval 로 수정

[#787][3.0] scatter chart 드래그 기능 추가

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/pieChart/api/pieChart.md
docs/views/scatterChart/api/scatterChart.md
src/components/chart/chart.core.js
src/components/chart/uses.js

- padding 옵션화 기능 추가
- 기본값:  { top : 20, left: 2, right: 2, bottom: 4 } 
- 관련 설명 .md 파일에 추가
```
const chartOptions = {
padding: { top: 0 },
...
}
```

[#806][3.0] Chart padding 옵션 추가

---

src/components/chart/chart.core.js
src/components/chart/element/element.bar.js

- 차트의 너비/높이에서  기본 padding값을 빼고, 그려야 하는 데이터의 label들 중 축을 벗어나는 만큼을 또 빼면서 series(막대, 라인...)을 그릴때 차트의 너비/높이가 음수로 전환되는 현상 발생
- 음수값을 가지고 Canvas의 arcTo 메소드를 호출하다가 Error 발생
- 차트 너비/높이에서 padding값을 빼는 로직에 음수로 전환되지 않도록 조건 문 추가
- 막대차트 // 모서리가 둥근 막대를 그리는 과정에서 에러 발생 시 일반 막대를 그리도록 예외처리
-  차트의 최소 너비/높이 값 지정

[#809][3.0] bar chart _ border radius 관련 에러 메시지 처리

---

docs/views/textField/api/textField.md
docs/views/textField/example/Icon.vue
docs/views/textField/props.js
src/components/textField/TextField.vue

- slot을 이용한 TextField 내에 Prefix, Suffix 아이콘 설정
- Icon 예제 추가
- md 파일 수정

[#817][3.0] TextField 아이콘 설정 추가

---

src/components/chart/helpers/helpers.canvas.js
src/components/chart/helpers/helpers.util.js

1.  rgba에서 투명도 값으로 0을 지정할 경우 rgba 입력값인지 판단하는 정규표현식에서 false 처리하여 수정
2. 그라데이션 입력에서 startColor 값을 지정안 할 경우 '#FFFFFF'으로 임의 처리하였지만 투명도 100으로 보이게끔 rgba(255, 255, 255, 0)으로 변경

[#820] [3.0] Bar Chart 그라데이션 값 rgba 지원 __ 투명값 0 처리

---

src/components/icon/Icon.vue

click 이벤트에 stop 수식어 제거(버블링 허용)

[#639] 아이콘 컴포넌트의 클릭 이벤트 stop 수식어 제거

---

src/components/chart/chart.core.js
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/style/chart.scss

- label 명이 길어져도 maxSeries의 값이 보이도록 수정
: tooltipCanvas width 설정 시 label명이 더 길명 label명을 기준으로 설정
- chartDom이 없을 때(ex. display: none) 예외 처리

[#825] Chart Tooltip label명 길어질 때 잘림 현상

---

src/components/grid/Grid.vue

- toolbar와 count 를 감싸고 있는 'toolbar-wrapper'를 toolbar 혹은 count를 사용하지 않을 때는 dom이 보이지 않도록 처리

[#837] Grid toolbar-wrapper 사용 시에만 표시

---

src/components/chart/Chart.vue
src/components/chart/uses.js

```
await watch(() => props.data, (curr) => {
const newData = defaultsDeep({}, curr, normalizedData);
```
- props.data 데이터를 watch하는 과정에서 신규 데이터(curr)와 차트의 기본 데이터 (DEFAULT_DATA)를 합쳐야 하는데 
- normalizedData( 컴포넌트 생성시점의 props.data + DEFAULT_DATA)와 합쳐 문제 발생
1.  인자로 전달받아 normalized된 데이터를 반환하는 함수 생성
- 해당 함수는 전달받은 데이터와 사전 정의된 차트의 기본데이터를 합치는 일만 함

[#846] [3.0] chart- props.data / props.option update 로직 이슈

---

src/components/chart/plugins/plugins.tooltip.js

- tooltip이 body 태그의 clientWidth을 벗어날 경우 반대쪽에 그리는 로직이 정상적으로 수행되지 않음 
- 차트 툴팁의 위치를 정하는 로직에서 특정 값(마우스 위치 <-> 툴팁 위치 사이 값: 20) 이 누락되어 이를 수정함

[#848] [3.0] chart tool-tip 위치 계산 이슈

---

src/components/tabPanel/TabPanel.vue
src/components/tabs/Tabs.vue

- getCurrentInstance() 내 ctx 가져오는 로직을 지우고 mv의 값을 바로 provide로 넘김

[#724][3.0] Tab 내부의 ctx 로직 삭제

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/Tooltip.vue
docs/views/scatterChart/api/scatterChart.md
src/components/chart/helpers/helpers.util.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/scale/scale.step.js
src/components/chart/style/chart.scss
src/components/chart/uses.js

1. label 혹은 series 명이 길어질 경우 화면 밖으로 나가는 현상 발생
1. `maxWidth` / `maxHeigh`t 옵션 추가
2. ` maxWidth`을 기준으로 overflow되는 text를 위한 처리 옵션 (`'wrap'`, `'ellipsis'`)
3. scrollbar / use -> `useScrollbar` 으로 옵션명 변경
4.  추가 / 수정된 옵션에 관한 내용 .md 파일 및 예제 코드에 추가

[3.0] chart - seriesName, Axis Label 이 길어질 경우 예외 처리

---

docs/views/select/api/select.md
docs/views/select/example/Default.vue
docs/views/select/example/Multiple.vue
src/components/select/Select.vue
src/components/select/uses.js

- Select 컴포넌트에서 `@change` 트리거 이벤트를 걸어도 발동되지 않는 현상
---
1. input 요소의 change 이벤트는 blur시 발동되므로 JS로 input.focus() -> input.bulr() 하여 강제로 change 이벤트 발생 ❌
- JS로 input value 수정 후에 focue -> blur 해도 change 이벤트가 발동되지 않음
2. input 요소의 change 이벤트를 input 이벤트로 변경 ❌
- input 이벤트는 값이 변경되면 발동되므로 해당 이벤트로 변경했지만 마찬가지로 발동되지 않음
3. input 요소에서 change, input 이벤트가 동작하지 않아 클릭 했을 때 'change' emit하도록 로직 수정 ✔
- 위의 두 방법이 적용되지 않아 click 이벤트 시 change를 emit하는 방법으로 수정
---

[#646][3.0] Select 컴포넌트 change 이벤트가 안되는 현상 수정

---

src/components/tree/Tree.vue
src/components/tree/TreeNode.vue

- 최신 vue3 문법에서 자기 자신의 컴포넌트를 재귀적으로 사용하는 것을 막아놔서 위 코드를 사용하면 에러 발생
---
- EVUI의 Menu.vue 컴포넌트에서도 같은 이슈가 발생하여 수정된 히스토리가 있어서 해당 부분 참고
- [Creating a Recursive Tree Component in Vue.js](https://www.digitalocean.com/community/tutorials/vuejs-recursive-components)
- [Dynamic & Async Components](https://v3.vuejs.org/guide/component-dynamic-async.html#dynamic-async-components)
---
- 최신 vue3에서는 자기 자신의 컴포넌트를 재귀적으로 사용하게 되면 `[Vue warn]: Failed to resolve component: _self` 에러가 발생
- 따라서 기존에 EVUI의 Tree컴포넌트에서 구현된 재귀적인 방법 대신 다른 방법을 사용 필요
- Menu.vue 컴포넌트를 참고하여 상위 컴포넌트(Tree.vue)가 하위 컴포넌트(TreeNode.vue)에게 props로 TreeNode 컴포넌트를 넘겨주고 `<component>`로 TreeNode 컴포넌트를 동적 생성하는 방법으로 수정
---

[#866] [3.0] build 후 적용시 Tree 컴포넌트의 하위 컴포넌트가 보이지 않는 현상 수정

---

src/components/chart/plugins/plugins.legend.js
src/components/chart/style/chart.scss

- point옵션이 true인 line chart의 경우 legend 영역 color 부분에 똑같이 point를 표시함

[#883] line chart legend style 변경

---

src/components/grid/Grid.vue
src/components/grid/uses.js

#################
- Grid의 bodyEl.clientHeight 가 0 이 아닌 경우 Virtual scroll 계산 실행

[#888] Grid Virtual scroll 관련 이슈 수정

---

docs/views/treeGrid/api/treeGrid.md
src/components/treeGrid/TreeGrid.vue
src/components/treeGrid/TreeGridNode.vue
src/components/treeGrid/uses.js

- row 데이터 변경 시 반응형이 동작하지 않은 이슈 관련 TreeGrid 데이터 stores 정리:
1) treeStore - TreeGrid 전체 각 row 데이터를 배열형태로 저장
2) showTreeStore - TreeGrid 전체 row 중에 expand/collapse 중 expand 되어 show 처리 될 row 데이터만 배열형태로 저장
3) viewStore - Virtual scrolling 계산하여 TreeGrid 높이에 따라 렌더링할 row 데이터만 배열형태로 저장
4) treeRows - props.rows 로 전달 받은 TreeGrid 계층 구조의 데이터를 저장
- 불필요한 코드 제거
- row 에 level 정보가 있는 class 추가

[#894][3.0] Tree Grid 수정사항

---

docs/views/window/api/window.md
src/components/window/Window.vue
src/components/window/uses.js

- mousemove, mousedown 시 이벤트 prevent 되어 window 내 마우스 관련 동작이 정상적으로 되지 않는 문제 수정
- draggable true 일 경우, 스크롤 여부에 따른 body 스타일 클래스 추가 로직 수정
- mousedown-mousemove 이벤트 emit 시, 전달인자 2.0 버전과 같게 수정

[#885][3.0] Window 버그 수정 1차

---

src/components/treeGrid/TreeGridNode.vue

- 객체 내 프로퍼티 없는 경우 문제 발생. optional chaining(?.)을 사용한 에러 로직 수정

[#894][3.0] Tree Grid 내 로직 수정

---

package.json
src/components/grid/Grid.vue
src/components/grid/index.js
src/components/grid/uses.js

- dom 이 display 되지 않는 상태에서 그리드가 생성되면 발생하는 column width 문제를 해결하기 위해 실제 display 를 감지하는 디렉티브를 추가
- 2.0 과 같은 이슈 [2.0] grid > vue-observe-visibility directive #725

[#902][3.0] grid > v-observe-visibility directive

---

src/components/treeGrid/TreeGrid.vue
src/components/treeGrid/index.js
src/components/treeGrid/uses.js

- dom 이 display 되지 않는 상태에서 그리드가 생성되면 발생하는 column width 문제를 해결하기 위해 실제 display 를 감지하는 디렉티브를 추가
- #902 와 동일

[#906][3.0] TreeGrid> v-observe-visibility directive

---

docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/DragSelection.vue
docs/views/lineChart/example/Event.vue
docs/views/lineChart/props.js
docs/views/scatterChart/api/scatterChart.md
src/components/chart/element/element.line.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/uses.js

Scatter chart에만 있었던 Drag select 기능을 Line Chart에도 추가하였습니다. 
`@drag-select` 로 이벤트를 등록할 수 있으며 선택된 영역내에 있는 데이터 (`data`) 와 선택된 영역의 범위(`range`)가 전달됩니다.
1. `DragSelection.vue` 파일에  Sample Code 추가
2. `Event.vue` 파일 버그 픽스
- X축의 CategoryMode 옵션 제거
-  클릭된 label값을 화면에 표시하는 과정에서 timezone이 맞지 않는 현상이 있어 string으로 변환하는 로직 추가
3.  lineChart에 드래그 범위에 해당하는 데이터들을 반환하는 로직(`findItems`)추가
4.  Darg한 영역을 표시하는 로직에 `line`타입 조건 분기
5. `dragSelection` 옵션의 `use` 값 기본 false로 변경
5. lineChart.md파일에 `dragSelection` 관련 정보 추가

[#920] [3.0] Line Chart Drag select 이벤트 추가

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Gradient.vue
docs/views/lineChart/api/lineChart.md
docs/views/pieChart/api/pieChart.md
docs/views/scatterChart/api/scatterChart.md
src/components/chart/plugins/plugins.legend.js

1. Chart Legend 옵션에 Padding옵션 추가 
- padding > top과 변수명이 겹쳐, position > top을 의미하는 변수명을  `top`에서 `positionTop`으로 변경 
2. 관련 설명 Docs에 추가
3. Bar Chart > Gradient Sample Code에 적용

[#928] [3.0] Chart > legend padding 옵션 추가

---

src/components/treeGrid/TreeGrid.vue

- Grid 처럼 tree grid 에도 props 에 전달된 selected 를 이용해서 클릭된 항목이 해제 되도록 하기위해 watch 가 필요함

[#935][3.0] TreeGrid > deselect 를 위한 watch 추가

---

src/components/contextMenu/MenuList.vue

- click 에 바인딩한 함수 실행시 context menu 내부 데이터 passing

[#935][3.0] Context menu > click 시 바인딩 함수에 data passing

---

src/components/datePicker/uses.js

작업 내용
- range 모드인 경우 timeFormat이 없을 때 shortcut클릭 안됨
원인: range 모드인 경우 timeFormat이 Array로 들어오는데 값이 없을 때 destructuring하여 오류 발생
해결 : destructuring전 사전 체크 로직 추가

[#954][3.0] DatePicker > range 모드인 경우 timeFormat이 없을 때 shortcut클릭 안되는 버그 수정

---

package.json
src/components/datePicker/uses.js

- 작업 내용
1. shortcut 연속으로 눌렀을 때 active 해제
원인: click 눌렀을 때 modelValue를 변경해 watch를 타서 button active를 시키도록 했었음
값이 동일할 경우 watch를 타지 않아 active가 되지 않음
해결: click한 key를 알고 있기 때문에 바로 active 시키도록 변경

[#957][3.0] DatePicker > shortcut 연속으로 눌렀을 때 active 해제되는 버그 수정

---

src/components/chart/Chart.vue

1. `ChartData` 옵션의 `Group` 부분을 `[['series1', 'series2']]` 와 `[[]]` 사이를 왔다갔다 할 수 있게 toggle처리
1. `Group` 옵션을 on/off 할 수 있음
1. Off -> On으로는 가지만 On -> Off로 가진 않음
1. `Chart Data`를  Watch하는 과정에서 Chart Data중 Series만 변경되었는지 체크하는데, group 및 data도 체크해야 제대로 차트를 다시 그릴 수 있어 로직 변경

[#959] [3.0] Chart > Chart Data 변경 Watch 정상 동작 하지 않음

---

src/components/chart/element/element.bar.js
src/components/chart/model/model.store.js

1. Stack일 경우 borderRadius 옵션 유무와 상관 없이 직각 형태의 박스를 그리드록 유회 하던 로직 제거
2. Stack일 경우 가장 상단에 위치한 박스만 둥글게 그리도록 `isTop` 플래그 추가

[#961] [3.0] chart > Stack Bar chart - borderRadius 옵션 추가

---

package.json
src/components/chart/helpers/helpers.canvas.js

BarChart에서 value 값으로 `undefined`값이 들어오면 막대의 높이 혹은 너비를 계산하는 로직에서 `NaN`이 리턴되어 에러로그 발생
1. `null` 뿐만 아니라 `undefined`도 체크하도록 조건 추가

[#963] [3.0] Chart > 높이 혹은 너비계산시 NaN이 리턴되는 현상

---

package.json
src/components/chart/model/model.store.js

1. 값이 null 혹은 undefined이 아닐경우를 체크하기 위해 사용했던  `if (gdata)` 조건에 0도 걸려 에러 발생
1. 값이 object 타입일 경우 외에는 원래 값이 들어가도록 로직 수정
2. EVUI 버전 업데이트 (3.1.49 -> 3.1.50)

[#963] [3.0] Chart > Falsy Value Issue

---

src/components/chart/Chart.vue
src/components/chart/chart.core.js

- Keep-alive를 사용하고 있고 브라우저의 뒤로가기 / 앞으로 가기 기능으로 화면을 이동했을 때 이전 화면에서 보던 Tooltip이 제거 되지 않음
- ![EVUI_chart_keep_alive](https://user-images.githubusercontent.com/53548023/145943263-543048c9-c937-4cc3-a679-7774f385f046.gif)
1. `onDeactivated` hook 추가
2. `hideTooltip` 메소드 추가
- ![keep-alive-chart](https://user-images.githubusercontent.com/53548023/145943373-fe5e43d4-de4e-46e4-937a-1aea2d919f44.gif)

[#965][3.0]Chart>keep-alive 엘리먼트와 함께 사용했을 때 Tooltip이 사라지지 않는 현상 발생

---

docs/views/treeGrid/example/Toolbar.vue
src/components/treeGrid/TreeGrid.vue
src/components/treeGrid/uses.js

- 트리의 데이터가 변경되면 노드 상태(expand/show)가 초기화 되는 문제 -> 해당 값으로 grid data가 변경되어야 한다.
- checked 데이터를 변경해도 반영이 안되는 문제 해결
[AS-IS]
[TO-BE]

[3.0] Tree Grid 노드 데이터 관련 이슈

---

package.json
src/components/grid/Grid.vue
src/components/grid/uses.js

- Grid > 컬럼 정보 변경 시 sort 초기화 로직 적용
- 그리드 컬럼 클릭 시 asc, desc, default 로 상태 값 변경
- 컬럼이 변경되어도 이전 sort 관련 데이터가 남아있다.
- desc <-> asc 로 toggle 된다.
**[TO-BE]**
- 컬럼이 변경되면 sort 데이터도 초기화된다.
- asc -> desc -> 기본 순서대로 toggle 된다.
※ 'RTS Port' 의 데이터 타입은 String입니다.

[#984] [3.0] Grid Sort 관련

---

src/components/chart/chart.core.js

1.  특정 막대를 클릭하고 (series3이 가장 상단에 위치하는 막대)  ChartData를 변경하여 전체를 다시 그릴때 가장 값이 큰 막대에 Tip이 위치하는데, 이전에 클릭했던 Series3을 기억하여 Tip의 위치가 막대 중간에 표시됨
- 예를들어 ChartData 수정과 같은 크게 Update된 일이 있을 경우 이전에 클릭했던 정보를 담는 변수를 초기화 하도록 함

[#986] [3.0] [3.0] Chart - MaxTip draw 관련 조건 수정

---

src/components/chart/Chart.vue

- Series2를 안보이게 처리할 상태에서 데이터가 추가될 경우 다시 Series2가 보이기 시작함
- Series2를 안보이게 처리할 상태에서 데이터가 추가되어도 안보이는 상태가 유지되도록 변경됨
1. isUpdateSeries에는 data 전체 변경여부가 아닌 Series 정보를 다시 계산하고 Legend 영역을 다시 그려야 하는 일에만 true로 들어가야함

[#989] [3.0] Chart > 차트에 데이터가 추가될 경우 Legend active / inactive 유지 되지 않음

---

src/components/chart/Chart.vue
src/components/chart/chart.core.js

- 재현 스텝
1. Legend - show : false,  groups: [] 상태의 차트 생성
2. Legend show 값을 true로 변경했다가 다시 false로 원복
3. stack 모드가 되도록 groups 의 값을 변경했다가 다시 원복 
4. Legend show 값을 true로 설정
- 결과
- 4번 이후 나타나는 legend영역에 sereis정보가 안보였었지만 보여지도록 로직 수정함
- 차트의 Series 혹은 groups가 업데이트 될 때 legend영역을 update(reset + init) 해야 하는데 reset(series 정보 제거) 하는 로직만 있어 수정함

[#988] [3.0] Chart > Legend 영역만 생기고 내부 Series 정보가 그려지지 않음

---

src/components/chart/plugins/plugins.interaction.js

- 차트 드래그 가능 범위 조정 (Axis 바깥 쪽 label 영역 포함)

[#997][3.0] Scatter Chart > Drag 범위 조정

---

src/components/chart/plugins/plugins.tooltip.js

- Stack 모드이고 값이 0이 포함된 경우 Tooltip의 `sortByValue` 옵션이 정상 동작하지 않는 현상
- 정렬하는 로직에서 값이 없음을 판단하는 조건문에 0도 포함되어 수행하였기 때문에 의도와 다르게 계산되었음
- null또는 undefined만 감지하도록 조건문 수정

[#999][3.0] Chart > Stack모드일때 Tooltip 의 정렬기능이 동작하지 않음

---

docs/views/window/example/Default.vue
src/components/window/uses.js

[3.0] EVUI > Window ESC 기능 버그 수정
#996
Window에 Escape key 누르면 닫히는 기능 추가와 관련하여 버그 수정
[ 버그 상황 ]
v-for로 Draggable Window를 여러 개 열었을 때 가장 상단의 Window만 닫히고 나머지 Window는 닫히지 않음
[ 보완 내역 ]
Window가 열리고 닫히는 경우의 수를 lifecycle hook과 관련하여 세분화하여 개선

[#1003][3.0] Window > ESC 기능 버그 수정 

---

package.json
src/components/chart/Chart.vue
src/components/chart/chart.core.js

- 브라우저 기능 중 확대 <-> 축소를 하다보면 차트의 일부분이 잘리는 현상 발생
- 위 이미지상 X축 Label이 보이지 않음
- Chart.vue파일 내 resize 이벤트 발생 시 Chart class의 resize method를 사용하도록 수정
- resize시 scale(해상도) 설정 부분이 누락되어 있어 추가

[#995][3.0] Chart > 브라우저 확대/축소 시 Resize 이벤트가 정상적으로 수행되지 않음

---

docs/views/window/api/window.md
docs/views/window/example/Default.vue
package.json
src/components/window/Window.vue
src/components/window/uses.js

- Window가 여러 개 열려 있을 때 특정 Window를 클릭한 경우, 해당 Window의 z-index 값을 높여 가장 상단에 위치시키는 기능 추가
- 기능 관련 focusable prop 추가
- 기능 관련 문서에 예제 코드 추가
구현 내용 정리 notion: 
https://www.notion.so/exem-fe/Window-z-index-esc-d6fabfb1bf5c4b178e0057adeb19e881#08b2fb2e19054f5293d006f34f43b89f

[#1009][3.0] Window > 클릭 시 z-index 높이는 기능 추가

---

docs/views/grid/api/grid.md
docs/views/grid/example/CellRenderer.vue
docs/views/grid/example/Default.vue
src/components/grid/Grid.vue
src/components/grid/uses.js

- 컬럼에 sortable: false 설정 시 sort 동작 안함
- 'Phone' 컬럼 `sortable: false` 설정

[#1024][3.0] Grid 컬럼 sortable 옵션 추가

---

package.json
src/components/window/uses.js

- [기존] 드래그 시,  width, height px로 전환
- [변경] props로 받은 width, height 단위 유지

[#1026][3.0] Window 드래그 시 props로 받은 크기 유지

---

package.json
src/components/chart/plugins/plugins.interaction.js

- 드래그 영역이 활성화 되어 있는 상태에서 차트의 다른 부분을 클릭하면 영역이 지워지는 이벤트 추가

[#1017][3.0] chart > drag-select 이벤트로 지정된 영역 해지 기능 추가

---

src/components/chart/scale/scale.js

- plot line 혹은 plot band 가 그려질 위치 값으로 null이 반환되는 경우 draw로직을 수행하지 않도록 예외처리 추가

[#1019][3.0] chart > PlotLine & PlotBand 영역 차트 이탈 현상 발생

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/pieChart/api/pieChart.md
docs/views/scatterChart/api/scatterChart.md
src/components/chart/plugins/plugins.legend.js
src/components/chart/uses.js

- Legend(범례) 영역의 사이즈를 조절할 수 있는 막대 
1. chartOption > legend > allowResize 옵션 추가 (**기본값 false**)
2. 관련 문서 내용 추가

[#1034] Chart > Legend영역 resize-bar 비활성화 관련 옵션 추가

---

src/components/chart/uses.js

1. Default 옵션을 가지고 있는 객체를 직접 수정하는 로직 제거

[#1039] Chart > Tooltip 사용 여부 기본 값 적용 버그

---

docs/views/treeGrid/example/Toolbar.vue
package.json
src/components/grid/Grid.vue
src/components/treeGrid/TreeGrid.vue
src/components/treeGrid/uses.js

**- 검색 대상의 자식 노드도 보여주기**
[AS-IS]
[TO-BE]
**- 노드의 펼침/접힘 상태 유지**
[AS-IS]
_검색 시 검색 대상의 부모 노드가 접힘-> 펼침으로 변경됨_
_검색어를 지우면서 모든 노드가 show_ 
[TO-BE]
**- 전체 체크 확인 시 데이터가 있는지 확인 조건 추가**

[#1041] TreeGrid 검색 스펙 변경

---

docs/views/scatterChart/example/Default.vue
docs/views/scatterChart/example/Event.vue
docs/views/scatterChart/props.js
package.json
src/components/chart/plugins/plugins.interaction.js
src/components/chart/uses.js

1. Drag-select를 한 상태에서 범위 선택을 취소하기 위해 차트 영역 아무곳이나 click 하면 범위가 해제되는 기능이 추가하였었으나,  사용자가 drag-select와 click 이벤트를 함께 등록했을 경우 범위 해제하려다가 click 이벤트까지 발행되는 문제 발생
_-> click 이벤트 emit 하기 전 drag 중이었는지 확인하는 조건문 추가_
2. 이벤트 객체를 받아볼 수 없음 
_-> (모든 차트 공통) click, dbl-click, drag-selection에 event객체를 받아볼 수 있는 parameter 'e' 추가_
3. Scatter Chart Event 예제 코드에 drag-select 내용만 있음 
_-> click 및 dbl-click 에 관한 코드도 추가_ 
4. Scatter Chart에 Tooltip 옵션을 true로 줘도 tooltip이 동작하지 않음 
_-> Scatter chart tooltip 관련 조건문 수정_

[#1043] Chart > drag-select 해지 이벤트와 click 이벤트가 동시에 발생하는 현상 수정

---

src/components/chart/plugins/plugins.interaction.js

**1.  drag 한 영역을 표시하는 상자가 생성되지 않았을 정도로 작은 drag 였음에도 불구하고 drag 이벤트가 emit됨**
-> drag 영역의 너비 및 높이가 1이상일 경우에만 drag-select 이벤트가 발생되도록 조건 추가
**2.  간혈적으로 drag 한 영역의 범위 값으로 차트 축의 최소, 최대가 넘는 값이 반환됨**
-> drag 범위를 계산하는 로직에서 계산된 결괏값이 축의 min max값을 넘지 않도록 로직 추가
- 위의 행위는 전부 Click으로 간주됩니다.

[#1045] Chart > drag-select 이벤트 선택 영역 사이즈 관련 이슈

---

docs/views/grid/example/Toolbar.vue
docs/views/treeGrid/example/Toolbar.vue
package.json
src/components/grid/Grid.vue
src/components/grid/uses.js
src/components/treeGrid/TreeGrid.vue

- input 이벤트 없이 검색어가 변경돼도 `onSearch`가 호출될 수 있도록 수정
**▶input 이벤트 없이 `searchValue` 값을 변경하여 적용해본 결과**
- TreeGrid
- Grid
**▶각 프로젝트 반영 시 수정사항**
- ev-grid, ev-tree-grid `option`에 `searchValue` 바인딩 값 추가
- **기존의 코드를 수정하지 않아도 정상 동작하나 위 바인딩 값을 추가해야만 input이벤트 없이 검색어를 변경했을 때 동작함**

[#1047] Grid, TreeGrid > 사용자가 입력했을 경우에만 검색 가능

---

package.json
src/components/chart/Chart.vue

1. redraw 메소드 추가 
2. EVUI 버전 업데이트 (3.2.0 => 3.2.1)
사용자가 아래와 같이 코드를 작성하여 원하는 시점에 차트를 다시 그릴 수 있음 
```
<ev-chart
:data="$props.data"
:options="$props.option"
ref="chartEl"
/>
setup() {
const chartEl = ref();
onActivated(() => {
chartEl.value?.redraw();
});
return {
chartEl,
};
}
```

[#1052] Chart > redraw 메소드 추가

---

docs/views/grid/api/grid.md
docs/views/grid/example/Toolbar.vue
package.json
src/components/grid/style/grid.scss
src/components/grid/uses.js
src/components/treeGrid/style/treeGrid.scss

- Grid stringNumber 타입 추가하여 string 이지만 number 타입 기준으로 sort
[AS-IS]
[TO-BE]

[#1054] Grid > stringNumber 타입 추가

---

docs/views/messageBox/api/messageBox.md
docs/views/messageBox/example/Default.vue
src/components/button/Button.vue
src/components/messageBox/MessageBox.vue

1. 버튼 클릭
2. MessageBox 열림
3. 포커스가 MessageBox가 아닌 버튼에 있어 Enter 키를 누르면 버튼이 계속 눌려 MessageBox가 계속 열림
1. MessageBox 컴포넌트에 focusable prop 추가
2. confirm 버튼, cancel 버튼, 메시지박스 컴포넌트 순으로 포커스 주었으며, 버튼에 포커스가 있는 경우 엔터를 누르면 닫힙니다.
3. ev-button에서 autoFocus prop이 true인 경우 focus() 메서드 호출하도록 추가
4. 예제 코드 추가

[#1056] MessageBox 열려 있을 때 포커스 설정

---

src/components/treeGrid/uses.js

#############
- 동일한 데이터를 ChildNodes를 중복 해서 사용할 경우 setTreeNodeStore() 호출 후 참조 값이 같아서 watch 를 무한으로 타는 현상이 발생
- Node 의 children 객체를 딥클론하여 사용하도록 수정

[#1061] TreeGrid Child Nodes 무한 루프 이슈

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Event.vue
docs/views/barChart/example/Time.vue
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/Event.vue
package.json
src/components/chart/Chart.vue
src/components/chart/chart.core.js
src/components/chart/element/element.tip.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/uses.js

1. chartOption > selectItem > use: true로 되어 있을 경우, 차트에서 데이터를 클릭한 곳으로 selectItem옵션에서 설정한 Tip 혹은 Indicator 가 옮겨지는 기능 존재
2. 기본값의 위치가 최대값으로 고정되어 있어 maxTip과 헷갈림
- **v-model:selectedItem로 바인딩 된 값에 해당하는 아이템을 선택**
- **line, bar chart에만 해당됨 (pie, scatter 제외)**
- ![image](https://user-images.githubusercontent.com/53548023/152931381-cf587c13-f9e4-49cd-aad3-1c39d0c3e18f.png)
- ![image](https://user-images.githubusercontent.com/53548023/152931681-0b713934-ff7f-4973-bdda-36c9cb0157e0.png)
- ![image](https://user-images.githubusercontent.com/53548023/152931572-eb1cff65-43c5-48ab-8122-3c0b01e04ffc.png)
1. md파일에 설명 추가
2. v-model:selectedItem로 받은 데이터를 기준으로 tip을 표시할 수 있도록 차트 생성 인자에 `defaultSelectInfo` 추가
3. 불필요한 함수 제거 및 코드 정리 
4.  **Version Update (3.3.3 -> 3.3.4)**

[#1038] chart select item 옵션 관련 로직 개선

---

docs/views/lineChart/example/Tooltip.vue
package.json
src/components/chart/chart.core.js
src/components/chart/plugins/plugins.interaction.js

1. data가 변하면 v-model로 받은 defaultSelectItem을 무시하기로 했었으나 다시 고정하기로 변경
2. EVUI Revision update (3.3.4 -> 3.3.5)
1. removeEventListener 누락된 부분 추가
2. console에 warning message 뜨는 부분 2건 픽스
1. Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
2. [EVUI][InputNumber] It cannot be calculated because the step is smaller than the precision setting.

[#1038] Chart > selectItem 옵션 개선

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Time.vue
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/Event.vue
package.json
src/components/chart/element/element.tip.js
src/components/chart/uses.js

- https://github.com/ex-em/EVUI/issues/1066
1. 'tipText' 옵션 추가 
- 'value' 혹은 'label'
- 기본값 : 'value'
2. maxTip이 selectedTip보다 나중에 그려지도록 함
3. 관련 docs 수정
4. time 관련 example code에서 selectItem관련 옵션 제거
5. line, bar chart의 Event 관련 example code 수정
6. **EVUI version update (3.3.5 -> 3.3.6)**

[#1066] Chart > selectItem > showTextTip옵션 개선

---

src/components/grid/Grid.vue
src/components/treeGrid/TreeGrid.vue
src/components/treeGrid/TreeGridNode.vue
src/components/treeGrid/uses.js

#############
- row 데이터 속성 '_disabled: true' 일 때 checkbox disabled 처리
- checkedRows 처리 시 disabled 된 row 제외하고 계산
```
{
id: 'docstore.ini',
_disabled: true,
children: [
{ id: 'docstore' },
],
},
```
- 기존에 column 데이터와 tree 의 옵션에 대한 속성이 중복 될 수 있는 문제가 존재
- 새로 추가되는 옵션이므로 `_` 를 붙였는데 기존에 tree 옵션 속성인 `parent`, **`children`**, **`expand`**, **`checked`**, `index`, `isFilter`, `level`, `show` 도 추후 수정이 필요

[#1074] TreeGrid > row 별 disabled 속성 설정 옵션 추가

---

docs/views/pieChart/api/pieChart.md
docs/views/pieChart/example/Default.vue
src/components/chart/chart.core.js
src/components/chart/element/element.bar.js
src/components/chart/element/element.pie.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.pie.js
src/components/chart/plugins/plugins.tooltip.js

1. Tooltip기능 존재하지 않음
2. highlight 기능 존재하지 않음
1. Tooltip 기능 추가
2. Highlight 기능 추가
1. 여러개의 dataset을 표현하는 기능 제거 및 예제 코드 삭제
2. 모호한 변수명 변경 (`type` -> `seriesIDs`)
3.  JS Docs 일부 잘못 기재 되어있던 부분 정정
4. 기타 리팩토링

[#1076] Chart > Pie 차트 Tooltip 기능 추가

---

package.json
src/components/datePicker/DatePicker.vue
src/components/datePicker/uses.js
src/components/inputNumber/InputNumber.vue
src/components/select/Select.vue
src/components/select/uses.js

- `.ev-input` 사용하는 컴포넌트의 레이아웃 깨짐현상 수정
- ev-input-number / ev-select / ev-date-picker 컴포넌트
[원인]
- 컴포넌트 외부에서 `display: flex` 속성 적용 시, 컴포넌트 최상단 dom 높이에 영향을 주어 발생
- `.ev-input` 를 사용하는 컴포넌트의 경우 높이를 따로 지정하지 않고 자식 콘텐츠 높이를 적용 받음
[해결]
- 최상단 dom 아래 wrapper dom 추가
- date-picker, select의 경우, dropbox 위치 기준 대상 수정(추가한 wrapper dom)

[#1078] form 요소 레이아웃 깨짐 버그 수정

---

docs/views/grid/example/Default.vue
src/components/grid/Grid.vue
src/components/grid/uses.js

#############
- 스크롤 막대가 스크롤러의 끝에 도달할 때 `scroll-end` 이벤트 발생
- `scroll-end` 의 parameter
```
prevPage: 1 // 이전 페이지 넘버
currentPage: 2 // 새로 요청할 페이지 넘버
dataCount: 50 // page 당 데이터 개수
startIndex: 50 // 새로 요청할 데이터의 첫 번째 인덱스
```
ex) 초기 50개 로드 후 스크롤러의 끝에 도달할 때 50개씩 버퍼 데이터 로드

[#1080] Grid > Infinite Scroll 추가

---

docs/views/pieChart/api/pieChart.md
docs/views/pieChart/example/Default.vue
docs/views/pieChart/example/Doughnut.vue
docs/views/pieChart/example/Event.vue
docs/views/pieChart/props.js
src/components/chart/Chart.vue
src/components/chart/chart.core.js
src/components/chart/element/element.bar.js
src/components/chart/element/element.pie.js
src/components/chart/helpers/helpers.util.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.pie.js
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/uses.js

1. `click` , `dbl-click` 이벤트 추가 
2.  `selectItem` 옵션 사용 가능하도록 기능 추가 
- 단 tip 표현은 할 수 없음 
3. 관련 docs 및 example code 작성 
4. chartOption > padding 값이 적용 안되는 현상 픽스 및 기본값 조정 
- 다른 차트들은 padding-top값이 20이 기본값이지만, pie는 2로 지정함
6. 일부 코드 리팩토링
- 코드에서 seriesID, sId 등 일부 혼용해서 사용되고 있는 명칭이 있으나 최근 `seriesID` 처럼 full name으로 기재하고자 변경해나가고 있음. 
- 코드 수정범위가 커 조금씩 진행할 예정

[#1082] Pie Chart 2차 개선  - event, selectItem 기능 추가

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Column.vue
src/components/chart/element/element.bar.js
src/components/chart/helpers/helpers.constant.js

1. `decimalPoint` 옵션 추가
- 사용예시
-  ![image](https://user-images.githubusercontent.com/53548023/157600262-5ce13c0a-ab4f-40ae-8911-f674bc4fcf62.png)
3. 관련 문서 수정
4. 관련 예제코드 수정
5. 축(Axis) 속성으로도 `decimalPoint`가 존재하여 설명 추가함

[#1087] Bar Chart > showValue옵션에 decimalPoint 추가

---

package.json
src/components/chart/model/model.store.js

- 값이 없는 변수에 대한 참조로 인해 에러 로그 발생
- ![image](https://user-images.githubusercontent.com/53548023/158507521-f6ff856d-1bd5-431c-a9cb-8b7a42e01524.png)
- 예외 처리 추가
- minor version update 3.3.8 -> 3.3.9

[#1093] Chart > selectItem > tip관련 에러로그 발생

---

src/components/chart/plugins/plugins.legend.js

1. fill: true 옵션을 가진 series는 legend영역의 colorDOM을 다른 스타일로 표시

[#1097] Line Chart > Legend 영역 fill: true 옵션 표시

---

docs/views/grid/api/grid.md
docs/views/grid/example/Default.vue
docs/views/grid/example/Toolbar.vue
docs/views/pagination/example/Default.vue
src/components/grid/Grid.vue
src/components/grid/grid.filter.window.vue
src/components/grid/grid.pagination.vue
src/components/grid/uses.js
src/components/pagination/Pagination.vue

#############
- Pagination 컴포넌트 콤마 제거, css 수정 (dark 테마 확인)
- grid.pagination 컴포넌트 추가
- infinite scroll, sort, search, change page 이벤트 발생 시 조건에 맞는 데이터를 요청 할 수 있도록 `request-data` emit 발생
- server-side paging 이 아닌 경우 즉, `useClient: true` 로 설정하고 전체 데이터를 초기에 가져온 경우 getPagingData()를 호출해 위 이벤트 발생 시 조건에 맞게 데이터를 변경
- infinite scroll 사용 시 sort, search 이벤트 발생하면 조건에 맞게 데이터 길이 및 스크롤 위치 초기화
- pagination 사용 시 페이지 변경하면 checked 초기화
- `request-data` -> `page-change` $emit 명칭 변경
- docs 수정 -> page 옵션 추가

[#1086] Grid > Pagination 기능 추가

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/SelectLabel.vue
docs/views/barChart/props.js
src/components/chart/Chart.vue
src/components/chart/chart.core.js
src/components/chart/element/element.bar.js
src/components/chart/element/element.tip.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/scale/scale.js
src/components/chart/scale/scale.step.js
src/components/chart/scale/scale.time.category.js
src/components/chart/uses.js

[#1102] Chart > Select Label

---

package.json
src/components/chart/element/element.pie.js

1. 조각위에 마우스를 올려도 Tooltip이 발생하지 않음
1. 기존 `CanvasRenderingContext2D.isPointInPath()` 사용을 제거하고 `isPointInPath` 함수 직접 구현으로 변경
2. Revision Update (3.3.9 -> 3.3.10)

[#1103] Pie Chart > 브라우저 확대/축소 시 Tooltip 버그 발생

---

src/components/chart/element/element.heatmap.js
src/components/chart/model/model.store.js

재현 스텝
1. x축 type time, interval: 'second'
2. 보내는 x축 데이터 간격 2 second
3. heatmap 확인
기대 결과
1. heatmap 간격이 겹치지 않고 정상적으로 그려짐
실제 결과
1. 겹쳐서 그려짐

[#1108] Chart > HeatMap 개발 - min 값 조정 및 사이즈 계산 버그 수정

---

docs/views/scatterChart/api/scatterChart.md
docs/views/scatterChart/example/Default.vue
docs/views/scatterChart/example/SelectItem.vue
docs/views/scatterChart/props.js
src/components/chart/chart.core.js
src/components/chart/element/element.scatter.js
src/components/chart/element/element.tip.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.legend.js
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/uses.js

**1. `selectItem` 옵션 추가** 
**2. `selectItem` > `useSeriesOpacity` 옵션 추가** 
- 선택된 항목 외에 다른 항목들을 불투명하게 처리하는 옵션 
- bar, line 차트에는 다음 이슈로 추가할 예정
**3. 관련 설명 및 예제 코드 추가** 
**4. Indicator, tip 을 그리는 로직 중 위치 계산하는 로직에 series 별 옵션(ex. pointSize) 참고하도록 수정**
**5. Scatter 전용 tooltip draw 로직 생성**
- 기존대비 header영역이 없고 value영역애 `x, y` 로 표시됨
- ![image](https://user-images.githubusercontent.com/53548023/160775937-2f03322b-46b6-4d70-9850-ba5fcc15d471.png)
- formatter는 기존과 동일하게 사용가능
- ex). (x, y, value) => `x: ${x} / y: ${y}`;
-
**6. ScatterChart / Default.vue 불필요한 코드 정리**

[#1111] scatter chart > selectItem 옵션 추가 및 tooltip 개선

---

src/components/chart/plugins/plugins.pie.js

- Pie Chart DOM의 크기가 chartOptions> padding 값 보다 작은 상태에서 draw할 경우,  radius값이 음수로 나와 canvasRenderingContext2 관련 에러로그 발생 
- ![image](https://user-images.githubusercontent.com/53548023/161887580-c3c10ea0-2d4b-4cd9-8940-6b39f83fa4e0.png)
1. Pie 차트를 그릴때 width 혹은 height이 0보다 작은 경우 로직을 수행하지 않도록 예외 처리

[#1121] Chart > drawDoughnutHole 관련 에러로그 발생

---

src/components/chart/element/element.line.js

- 두개이상의 line type Series를 group으로 묶어 stack line chart로 구성하고, 동일한 위치에 null 값을 넣을 경우 데이터와 무관한 line이 보임 
- ![image](https://user-images.githubusercontent.com/53548023/163097805-8def69cf-0f19-4fbd-beff-8e912365b3bb.png)
- loop돌면서 stroke를 그리는 로직에서 beginPath가 누락되어 있어 추가함
- ![image](https://user-images.githubusercontent.com/53548023/163097854-01cedc5b-250d-4f48-af49-c39cae4faf27.png)

[#1127] Line Chart > 특정 조건에서 데이터와 무관한 line 발생

---

src/components/chart/element/element.line.js
src/components/chart/scale/scale.js

**1. x 축이 time 인 경우에도 `useLabelOpacity`  옵션이 적용되도록 스펙 변경**
- 선택된 시간이 x 축에 표시된 label 인 경우만 opacity 를 변경하고, 새로운 text 를 추가하지는 않는다

[#1131] Line Chart > Select Label - useLabelOpacity

---

src/components/chart/plugins/plugins.legend.js

1. type 전달이 누락되어 있어 추가
2. Pie Chart 일 경우에만 hit 정보를 series draw시에 넘겨줘야하기 때문에 조건문 추가
- https://github.com/ex-em/EVUI/issues/1143

[#1133] Pie Chart > selectItem 옵션 사용중일 때 legend영역 마우스 오버시 에러로그 발생

---

docs/views/heatMap/api/heatMap.md
docs/views/heatMap/example/Event.vue
docs/views/heatMap/example/Time.vue
package.json
src/components/chart/Chart.vue
src/components/chart/element/element.heatmap.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.legend.js
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/scale/scale.step.js
src/components/chart/uses.js

작업 내용
-
1. drag 범위 Block(HeatMap Item) 단위로 선택되도록 개선
2. Block Stroke 속성에 opacity 옵션 추가
3. 축이 step 타입인 경우 간격 별 label 조정(rangeMode인 경우만)
4. data 업데이트 시 범주 범위 업데이트
5. value 범위 표현 수정

 [#1129] HeatMap > 축 step 타입 면적에 따른 label 간격 조정 & range block 단위로 선택

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Default.vue
package.json
src/components/chart/chart.core.js
src/components/chart/element/element.bar.js
src/components/chart/uses.js

**1. cPadRatio 옵션 추가**
- 카테고리(라벨) 간 공간을 추가하는 옵션
- 기본 값 : 0 
- 0 이상 1미만 사이 값만 유효하며 유효범위를 넘을 경우 기본값 상태로 보여짐
**2. EVUI version Update**
- 3.3.15 -> 3.3.16
**before**
**after ( cPadRatio: 0.1 )**

[#1145] Bar Chart > cPadRatio 옵션 추가

---

docs/views/heatMap/api/heatMap.md
docs/views/heatMap/example/Time.vue
src/components/chart/element/element.heatmap.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.legend.js
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/uses.js

작업 내용
-
1. legend 표현 아래의 경우의 수에 따른 예외 처리
- data가 없는 경우
- value값이 모두 동일할 경우
- value max값와 min값의 차이가 범주 개수보다 작을 경우
- max값까지 범주 개수 조정
- interval이 1보다 같거나 작고 정수 표현인 경우 범위가 아닌 하나로 표현
2. legend 이벤트 버그 픽스
- legend off 한 범위에 속하는 value tooltip 또는 highlight가 뜸
- value값과 value가 속하는 legend 상이
3. heatmap color 옵션에 decimalPoint 속성 추가
- legend 범주 표현의 소숫점 처리 옵션

[#1144] HeatMap > value 값에 대해 경우의 수에 따른 예외 처리

---

src/components/pagination/pageButton.vue

- 페이징 버튼 클릭 시 이벤트 중복 호출되는 이슈 수정

[#1150] Grid > Page Number관련 오동작

---

docs/views/barChart/api/barChart.md
docs/views/heatMap/api/heatMap.md
docs/views/heatMap/example/Time.vue
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/Tooltip.vue
docs/views/pieChart/api/pieChart.md
docs/views/pieChart/example/Default.vue
docs/views/scatterChart/api/scatterChart.md
src/components/chart/plugins/plugins.tooltip.js

- 기존 Tooltip의 formatter는 `value` 영역 한정으로 제공되고 있었으나 title 영역에 대한 formatter 지원도 필요하여 기능 추가함
- ![image](https://user-images.githubusercontent.com/53548023/166175699-637ac913-a755-4a1d-95d4-1b82bf5674b7.png)
- 자세한 사항은 차트 타입별 docs 확인
1. formatter 옵션 수정
- 기존 formatter property에 function으로 바로 넣어서 사용하던 코드도 유지될 수 있도록 function / object type 둘다 지원하며 function타입으로 넘길 경우 valueFormatter로 동작하도록 함
3. bar, line, pie, scatter, heatmap 적용

[#1154] Chart > Tooltip > Title 관련 Formatter 옵션 추가

---

docs/views/barChart/api/barChart.md
docs/views/heatMap/api/heatMap.md
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/AxisTitle.vue
docs/views/lineChart/props.js
docs/views/scatterChart/api/scatterChart.md
package.json
src/components/chart/chart.core.js
src/components/chart/helpers/helpers.constant.js
src/components/chart/helpers/helpers.util.js
src/components/chart/scale/scale.js
src/components/chart/scale/scale.step.js
src/components/chart/scale/scale.time.category.js

1. Chart > Axis > title 옵션 추가
2. 관련 예제 코드 작성 (Line > AxisTitle.vue)
3. 관련 설명 추가

[#1156] Chart > Axis > title 옵션 추가

---

src/components/treeGrid/TreeGrid.vue

- parent가 없는 최상의 노드일 경우 자식노드 show 처리될 수 있도록 수정
[AS-IS]
[TO-BE]

[#1160] TreeGrid > Highlight 시 자식 노드 안보이는 이슈

---

src/components/chart/plugins/plugins.legend.js

**1. 차트 Legend DOM 의 height 조절**
-  ev-chart-legend, ev-chart-legend-box DOM 이 top, bottom 옵션으로 쓰일때 padding 및 allowResize 옵션으로 인해 크기가 맞지 않는 현상 수정

[#1162] Chart > legend - top, bottom 사용시 DOM height 조절

---

docs/views/heatMap/example/Gradient.vue
src/components/chart/element/element.heatmap.js
src/components/chart/scale/scale.step.js

작업내용
-
1. 높이가 낮아 max step이 2보다 낮은 경우 예외처리
2. radius보다 계산된 width, height가 작은 경우 예외처리

[#1164] HeatMap > 높이가 작을 경우 y축 사라지는 현상 픽스

---

src/components/select/Select.vue
src/components/select/uses.js

1. 한글로 입력시 두글자 부터 필터링 되는 현상 수정

[#1163] Select - filterable 에서 한글 입력이 바로 반영되지 않는 문제

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Stack.vue
package.json
src/components/chart/element/element.bar.js

1. Null이 Text로 표시됨
- ![image](https://user-images.githubusercontent.com/53548023/168961854-74d3ab23-c838-4b19-823d-cd66f36be645.png)
2. align: end  / start / center 이고 막대가 텍스트 너비 보다 좁을 경우 서로 겹쳐보이는 현상 발생
-  ![image](https://user-images.githubusercontent.com/53548023/168962064-16d14807-8e40-43cb-ac3f-5f6d68f2b004.png)
1. Null 이 Text로 표시되지 않도록 로직 수정
3. 막대 영역이 좁을 경우 text를 표시하지 않도록 조건 추가
4. 관련 문서 오타 수정 및 예외 조건 안내문 추가
5. Stack 예제 showValue 옵션 추가
6. EVUI Version Update  (3.3.20 -> 3.3.21)

[#1168] Stack Bar Chart > showValue옵션 로직 개선

---

package.json
src/components/chart/model/model.store.js

- 길이가 2인 배열인 형태를 기대했으나 간혈적으로 null이 들어가는 상황이 있고, null을 대상으로 구조분해할당 시 에러로그가 발생함
- 배열 구조 분해 할당 전 배열이 맞는지 확인하는 로직 추가
- EVUI version update (3.3.21 -> 3.3.22)

[#1170] line Chart > select Series 관련하여 간혈적으로 에러로그 발생

---

src/components/grid/Grid.vue
src/components/grid/uses.js
src/components/treeGrid/TreeGrid.vue
src/components/treeGrid/uses.js

- grid 내부의 paging 사용 시 total 값을 입력해도 현재 가지고 있는 rows의 개수 만큼만 카운팅되는 문제 수정

[#1172] Grid, TreeGrid > paging total 값 관련 이슈

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Default.vue
docs/views/heatMap/api/heatMap.md
docs/views/lineChart/api/lineChart.md
docs/views/pieChart/api/pieChart.md
docs/views/scatterChart/api/scatterChart.md
package.json
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/style/chart.scss
src/components/chart/uses.js

- Tooltip의 header영역과 Body 영역의 폰트가 다르게 적용됨
- Header (DIV DOM) 과 Body(Canvas DOM) 에 동일한 폰트가 적용되도록 로직 수정
- font를 사용자가 변경할 수 있도록 로직 수정 `chartOption > tooltip > fontFamily`
- Version Update (3.3.22 -> 3.3.23)

[#1174] Chart > 툴팁 타이틀 한글 폰트가 다르게 적용됨

---

src/components/treeGrid/uses.js

- 클릭 이벤트 시 클릭한 target 의 가장 가까운 td의 dataset을 가져올 수 있도록 수정

[#1179] Tree Grid > 클릭이벤트시 컬럼의 dataset 을 읽어오지 못하는 현상

---

docs/views/lineChart/example/Tooltip.vue
docs/views/scatterChart/example/SelectItem.vue
package.json
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.tooltip.js

- Formatter 적용 전 데이터를 기반으로 Tooltip의 value 표시 영역의 너비를 계산하여 실제 Text보다 더 넓거나 좁게 보일 수 있음 
- 실제 데이터
- ![image](https://user-images.githubusercontent.com/53548023/169971392-d705f1f8-f6e8-476a-9e1b-3d5c1ae4b6ec.png)
- formatter를 적용한 데이터 
- ![image](https://user-images.githubusercontent.com/53548023/169971428-7076f212-4d5a-4aa0-b02e-5f5aff4d6f7b.png)
- formatter를 적용하여 Text가 짧아졌음에도 불구하고 value 영역이 넓게 잡힘
1.  툴팁 DOM의 너비를 결정할 때 original Data가 아닌Formatter 적용 이후의 text를 참조하도록 로직 변경
- ![image](https://user-images.githubusercontent.com/53548023/169971578-725c58b3-97cb-4030-aba8-0d0a613954ca.png)

[#1181] Chart 툴팁 너비 계산 버그

---

src/components/chart/plugins/plugins.interaction.js

- Tooltip > showAllValueInRnage 사용시 일부 항목의 데이터가 undefined로 출력되는 현상 발생 
- https://github.com/ex-em/EVUI/pull/1182  이슈를 처리하면서 formatted 라는 속성으로 value를 표시하도록 변경하였으나 showAllValueInRange 로직 내부는 누락되어 발생한 버그 
- formatter관련 로직 `getFormattedTooltipValue`  함수로 분리
- showAllValueInRange 관련 로직 `addNotHitInfo` 함수로 분리

[#1188] Chart > Tooltip > showAllValueInRange 사용시 formatter 적용되지 않음

---

package.json
src/components/grid/uses.js

- 객체 타입의 Column 도 Sorting 기능 동작하도록 수정
- Column의 filed명과 동일한 key값을 기준으로 정렬 (search 기능 시 적용된 스펙과 동일)
- filed명 key 값을 기준으로 데이터 타입 지정 (ex. 'string', 'number', 'stringNumber', 'float', 'boolean')
- 타입 누락 시 기본 정렬 타입 'string'

[#1202] Grid > 객체 타입 Column Sorting

---

src/components/chart/helpers/helpers.util.js

- axis > `linear` 혹은 `log` 타입에서 0 이하의 숫자들로 데이터가 들어올 경우 축에 소수점을 포함하여 표시해야 하지만 정수만 표시되는 현상 발생
- ![image](https://user-images.githubusercontent.com/53548023/171789729-08953438-1a10-4711-9102-e79bb799bb3f.png)
```
axesX: [{
type: 'log',
showGrid: true,
}],
```
- 불필요한 조건문을 제거하여 사용자로부터 받은 `decimalPoint` 속성이 반영되도록 함
- ![image](https://user-images.githubusercontent.com/53548023/171789715-4ae82cca-7cd9-49e0-9079-233958a3af2a.png)
```
axesX: [{
type: 'log',
decimalPoint: 6,
showGrid: true,
}],
```

[#1200] Chart > Axis > Decimal Point 동작하지 않는 현상 발생

---

src/components/treeGrid/TreeGrid.vue

- row Highlight 시 스크롤 및 페이징 상태에서도 정확한 위치로 Focusing

[#1206] TreeGrid > Highlight Focusing Bug

---

src/components/chart/plugins/plugins.legend.js

- 차트 legend 클릭으로 series 를 hide 할때 최소 1개는 보여지는 것이 스펙이지만, 차트의 update 함수 호출 이후 모두 hide 가 가능해짐
- ![legend](https://user-images.githubusercontent.com/46586573/173725036-1a472be4-d89b-4b10-95cb-1bd838b3e99f.gif)
- 차트 update 가 호출된 이후에 visible counter 역할을 하는 seriesInfo.count 가 초기화 되지 않아서 updateLegend 를 호출하면 counter 가 증가하며, [실제 시리즈 갯수 x 2]개 의 count 를 갖게되어 legend 코드에서 의도한 것으로 보이는 최소 한개를 보여주는 스펙이 동작하지 않음.
- `resetLegend` 함수에서 count 를 초기화

[#1214] Chart > legend - update 호출 이후 모든 series hiding 이 가능해지는 버그

---

src/components/chart/plugins/plugins.interaction.js

[#1290] Chart > tooltip > 값이 null인 경우 보이지 않는 현상

---

src/components/chart/chart.core.js
src/components/chart/scale/scale.js

- decimalPoint를 지정하지 않은 차트(default: 0)에서 초기 데이터가 없다면 축에 0, 1로 렌더링하도록 수정
- decimalPoint를 지정하지 않은 차트(default: 0)의 데이터가 1보다 작으면 축에 0, 1로 렌더링하도록 수정
- 축의 step을 결정하는 `calculateSteps`함수에 decimalPoint 인자를 받도록 수정하였습니다.
- `calculateSteps`함수에서 최대값이 1이고, decimalPoint가 false인 경우에 동작하도록 로직을 추가하였습니다.

[#1212] Chart > decimalPoint를 지정하지 않았을 때 축의 값이 0과 1이 반복되어 보이는 현상

---

src/components/chart/chart.core.js
src/components/chart/element/element.bar.js
src/components/chart/element/element.line.js
src/components/chart/element/element.pie.js
src/components/chart/element/element.scatter.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.legend.js
src/components/chart/plugins/plugins.pie.js

- `selectSeries` , `selectLabel` 옵션을 사용중인 차트에서는 legend 영역에 mouseover를 하더라도 해당 series가 Highlight 되어 보이지 않음
- ![legend_highlight_before](https://user-images.githubusercontent.com/53548023/174253092-9072eceb-4cc1-48ae-ad74-d5c78bf9ed5f.gif)
- `Bar`, `Line`, `Pie`, `Scatter` 차트 Highlight / Downplay 구분하여 Opacity 값 구하는 로직 전면 수정
- Legend 영역 `Mounseover` 이벤트 안에 들어있던 series의 state값 변경시키는 로직 삭제
- `SelectSeries` 옵션 관련 로직안에 들어있던 series의 state값 변경시키는 로직 삭제
- ![legend_highlight_after](https://user-images.githubusercontent.com/53548023/174253110-de41d02b-224e-4283-82d2-2c4083624e6b.gif)

[#1215] Chart > Highlight 기능 우선순위 조정

---

docs/views/barChart/example/Column.vue
package.json
src/components/chart/plugins/plugins.interaction.js

- **tooltip > showAllValueInRange 옵션을 true로 설정하였을 때, 어떤 막대를 선택했느냐에 따라 Tooltip의 너비가 다르게 보임**
- ![image](https://user-images.githubusercontent.com/53548023/174696432-7cfb7409-0df4-41d0-ba0c-c91b8cb15b8d.png)
- **showAllValueInRange 옵션이 켜져있을 경우 show상태인 sereis를 대상으로 가장 길이가 긴 name과 value를 구하도록 로직 수정**
- ![image](https://user-images.githubusercontent.com/53548023/174696465-38d983e0-7264-497d-969c-0f6a5a3cd463.png)
- ![image](https://user-images.githubusercontent.com/53548023/174696483-1902b376-7daa-4246-b562-b2a518b98251.png)

[#1219] Chart > Tooltip > showAllValueInRange 옵션 사용중일때, 마우스 위치에 따라 동일한 툴팁의 너비가 다르게 보이는 현상 발생

---

docs/views/barChart/example/Column.vue
package.json
src/components/chart/plugins/plugins.interaction.js

- `tooltip`의 `showAllValueInRange` 옵션과 `formatter`를 동시 사용한 상태에서 `NULL` 로 표시된 공간에 마우스 오버시 참조 에러 발생
- EVUI Version Update (3.3.30 -> 3.3.31)
- Optional chaining 추가

[#1221] Chart > showAllValueInRange, formatter 동시 설정 시 콘솔 오류

---

src/components/chart/element/element.bar.js
src/components/chart/element/element.bar.time.js

- bar 의 갯수가 많아지는 경우 크기가 0 이 되어 차트가 그려지지 않음
- 크기 계산 방식을 반올림에서 올림으로 변경하여 최소 1을 보장

[#1224] Chart > bar Chart size 가 0 이 되는 문제

---

src/components/grid/style/grid.scss
src/components/treeGrid/style/treeGrid.scss

- 데이터가 있을 땐 body 에 row 의 width 에 따라 overflow 적용됨
- 데이터가 없을 때 전체 컬럼을 볼 수 있도록 `display: table`를 주어 header 의 width 에 따라 overflow 적용됨
- 이때 header 의 마지막 컬럼 margin 값으로 인해 scroll 이 생기는데 데이터가 있을 때는 scroll 이 사라지는 문제 -> margin 값을 제거
#데이터 있을 때
#데이터 없을 때
[AS-IS]
[TO-BE]

[#1229] Grid, TreeGrid > 데이터 없을 경우 scrollbar 생기는 현상

---

docs/views/datePicker/example/Default.vue
src/components/calendar/uses.js

이슈 사항
-
disabledDate로 최소 범위를 변경하고 싶은데 기존 SPEC으로 인해 최소 범위가 1일로 잡힘
작업 내용
-
**AS-IS**
기존 SPEC 
rangeMode(fromDate, toDate가 있는 경우)일 때 fromDate 시간이 toDate를 넘으면 disabled처리
**TO-BE**
사용자가 작성한 disabledDate가 있는 경우 기존 SPEC 무시
disabledDate가 없는 경우 기존대로 비교하여 disabled 처리

[#1234] Calendar > disabledDate 함수가 있는 경우 fromDate > toDate 비교하지 않도록 변경

---

.github/actions/jandi-notify/action.yml
.github/workflows/deploy-docs.yml
package-lock.json
package.json

- 잔디 알람 액션 파일 추가
- npm 캐싱 방식 수정

[#1236] Github Actions CI/CD 잔디 알람 적용

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/SelectLabel.vue
src/components/chart/plugins/plugins.interaction.js
src/components/chart/uses.js

- selectSeries 의 선택된 시리즈를 고정하고 싶다는 요구사항
- selectItem, selectLabel, selectSeries 옵션에 useClick 을 추가 (default: true)
- 클릭 이벤트에서 useClick 이 true 인 경우에만 클릭 이벤트로 select 기능이 동작

[#1248] Chart > select 기능 > useClick 옵션 추가

---

src/components/chart/Chart.vue
src/components/chart/chart.core.js

1. chart Option > legend > use: true <-> false 스왑
2. 동작 확인
3. v-if 등을 이용하여 ev-chart 컴포넌트 화면에서 제거
4. 제거 했던 ev-chart 다시 생성 
5. 1번과 같은 액션 수행
6. 동작 확인 
2/ 에러 없이 정상 수행
6/ 에러 없이 정상 수행
2/ 에러 없이 정상 수행 (PASS)
6/ this.legendDOM 을 못찾는 에러로그 발생 (FAIL)
-------------
1. watch 문이 mounted hook 안에 들어있어, mounted 될 때마다 동일한 객체를 바라보는 watch가 중복으로 생성되며 발생한 문제 픽스
1. 위 내용 테스트 도중 Chart의 init() 함수가 호출되기 전에 render() 함수가 먼저 호출되는 현상을 발경하여 예외 처리 추가

 [#1245] Chart > Legend 관련 옵션 변경 시 DOM 을 못찾는 Error log 발생 및 select관련 예외처리 추가

---

package.json
src/components/grid/uses.js
src/components/treeGrid/uses.js

- falsy 한 column 값은 검색 대상에서 제외는 이슈
- Nullish Coalescing을 이용해 colum 값이 0 이거나 false 인 falsy한 값이더라도 검색 대상에 포함되어 검색이 되도록 수정

[#1249] Grid, TreeGrid > falsy 한 column 값은 검색 대상에서 제외는 이슈

---

package.json

- Maxgauge for mongo 에서는 아직 evui 2 버전대를 사용하고 있기 때문에 2 버전대로 배포 한번 해줌

Publish - 2.1.1

---

package.json
src/components/chart/scale/scale.js

- Linear 타입의 축의 간격이 균일하게 배분되지 않는 현상 발생
- 균일한 간격으로 나눠 축을 그렸을때, 마지막 값이 maxValue보다 클 경우 maxValue로 대체되는 로직 제거

[#1254] Chart > Bar Chart의 높이가 이상하게 그려짐

---

src/components/chart/Chart.vue

- 차트를 사용하는 쪽에서 onMounted hook 전에 props data를 변경할 경우, chart.vue 파일의 watch문이 EvChart의 init 함수보다 먼저 호출되면서 참조 에러 로그 발생
- 차트 생성여부를 확인 할 수 있는 조건문 추가

[#1256] chart > 객체 참조 에러 로그 발생

---

docs/views/comboChart/example/TableTypeLegend.vue
src/components/chart/helpers/helpers.util.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.legend.js

- 합계, 최솟값, 최댓값, 평균 계산시 null과 undefined는 제외하도록 함
- 마지막값 계산 시 null과 undefined는 'Null'로 표시되도록함
- 계산된 값이 javascript기준 MAX_SAFE_INTEGER을 초과했거나 MIN_SAFE_INTEGER 미만일 경우 console warning이 출력되도록함

[#1269] Chart > Legend 영역 통계 > null 처리

---

src/components/grid/uses.js
src/components/treeGrid/uses.js

해당 사진 처럼 ev-grid 템플릿 단 에서 데이터 값을 정제하려고 할 때 `div` 가 한번 더 쓰여져 tr의 data-index를 읽어오지 못하는 현상임을 확인 하였습니다.
tr의 공통된 특징은 `'.row'` 라는 클래스를 가지고 있는 것 이므로 이벤트가 일어난 target 에서 가장 가까우며 `'.row'` 라는 클래스를 가진 부모 (tr)을 찾기 위해 `closest` 를 사용 하였습니다.
해당 부분은 Tree-Grid 에서도 같은 현상이 있음을 확인하고 같이 수정 작업 하였습니다.

[#1273] Grid, TreeGrid > title과 해당 column row 의 내용이 다를 때 마우스 우클릭 이상 동작 현상

---

package.json
src/components/radio/radio.vue

- 2.0 버전의 radio 컴포넌트가 disabled 상태일때 색상이 이상함
- type 이 button 형태일때는 button 컴포넌트가 disabled 상태인 색상을 표현하도록 css 를 추가
- :not(.button) 셀렉터를 이용하여 가중치를 변경해 의도한 색상이 나오도록 변경

[#1277][2.0] Radio > disabled 상태 color 조정

---

src/components/textfield/textfield.vue

2.0 버전의  컴포넌트에서 custom-error-msg prop 값 넘겨주었을 때 오류 상태를 표현하는 색상으로 변경되지 않습니다.
custom-error-msg prop가 truthy한 값인 경우, 오류 상태 표현하는 색상으로 변경
ID 항목에 custom-error-msg 설정하였지만 border-color가 변경되지 않는 모습

[#1280][2.0] TextField > disabled 상태 color 조정

---

package.json
src/components/grid/grid.vue

- 리사이즈 대상의 다음 컬럼이 hide: true 인 경우 에러 발생
- hide 가 아닌 다음 대상을 찾도록 수정
[AS-IS]
[TO-BE]

[2.0] Grid > Column 리사이즈 에러

---

src/components/chart/plugins/plugins.legend.js

-  ![image](https://user-images.githubusercontent.com/53548023/191912958-259e82e4-f642-4e00-9ecf-bb6931a7d1b8.png)
- heatmap 의 legend영역에 series color가 inactive color로 표시 됨
- https://github.com/ex-em/EVUI/pull/1226
- series 별 show값이 false경우 inactive상태로 표시되도록 수정된 내용
- heatmap은 사용자로부터 series별 show 여부를 받지 않아 기본이 undefined이기 때문에 inactive상태로 표시되는 현상 발생된 것 
- heatmap 의 series 정보에서 show: true 로 부여

[#1286] Chart > Heatmap > legend > series 활성화 버그

---

src/components/pagination/pageButton.vue

##############################
- #1150 에 관한 사이드 이슈 처리
- 버튼의 클릭 이벤트가 전파되는 것을 중단 시킴

[#1292] Grid / TreeGrid > Pagination prev / next 버튼 동작 안됨

---

package.json
src/components/chart/Chart.vue
src/components/chart/chart.core.js
src/components/chart/chartZoom.core.js
src/components/chart/plugins/plugins.title.js
src/components/chart/uses.js
src/components/chartBrush/ChartBrush.vue
src/components/chartBrush/chartBrush.core.js

###########################################
[이슈 내용]
- Chart Options의 title 변경 시 evChart.update를 타고 initTile로 타이틀이 변경 되어야 하지만 초반 차트를 그리며 this.isInitTitle = true; 된 값 때문에 initTitle 함수를 타지 않게 되고 변경 된 타이틀이 적용되지 않게 됨.   
- zoom 아이콘이 활성화 된 상태에서 데이터를 다시 업데이트 한 후 브러시 영역을 움직였을 경우 줌 아이콘은 비활성화 되어 있지만 나머지 아이콘은 활성화 됨.   
- brush에 사용하는 차트의 데이터가 없지만 브러시가 그려지게 됨
[수정 내용]
- title 변경 시 initTile 함수를 타고 titleDOM.textContent에 바뀐 title이 적용되도록 수정.   
- 데이터를 다시 업데이트하고 브러시 영역을 움직이더라도 zoom 아이콘들은 zoom 아이콘이 활성화 되어야 사용 가능하도록 수정.   
- brush에 사용하는 차트의 데이터가 없을 경우 브러시가 그려지지 않도록 수정

[#1296] Chart > Brush, Zoom, Title 수정

---

src/components/chart/scale/scale.js

#####################################################
[원인]   
- Horizontal BarChart이 처음 마운트 될 때 LogarithmicScale에 의해 Scale이 정해지는데 이때 Scale로 전달되는 options의 값이 없어 (undefined) x, y축 라벨의 텍스트가 그려지는 부분에서 options에 brush 프로퍼티를 찾을 수 없으므로 에러가 발생하게 됨.    
[수정 내용]    
- options.brush에서 options?.brush로 수정

[#1298] BarChart > Horizontal Chart의 Brush 관련 에러 확인

---

docs/views/brushChart/example/SelectLabelGroup.vue
package.json
src/components/chart/element/element.line.js
src/components/chartGroup/ChartGroup.vue

#####################################################
[원인]
- SelectedLabel 데이터 많을 때 정확하게 0번째 위치에 인디케이터가 생기지 않는데 데이터가 많아서 그래프의 포인트간 간격이 6 이하일 때 원하는 차트의 날짜에 클릭했을 때 정확하게 인디케이터가 생성 되지 않음.
[수정 내용]
- 차트 포인트 간격이 6 미만일 때 데이터간 간격의 최소 값인 1.5로 계산하여 데이터 값의 x - 1.5 < 클릭한 차트의 xp 위치 && xp < x + 1.5로 오차 범위를 최소화 함.
[수정 범위]
- line chart

[#1299] Chart > Indicator 인디케이터의 dataIndex가 0일 때 위치가 정확하지 않음

---

docs/views/datePicker/example/Default.vue
src/components/calendar/uses.js

이슈
-
date range 모드일 때, shortcut 버튼 클릭하면 model value는 변경되지만 calendar엔 바로 반영 되지 않음
예상 원인
-
model value watch에서 dateRange 모드인 경우엔 업데이트 하지 않음
작업 내용
-
1. date range 모드인 경우에도 model value가 변경 감지되면 calendar 업데이트 하도록 수정
2. date range shortcut 추가
3. docs shortcut의 lastMonth, lastWeek 범위 수정

[#1305] DatePicker > DateRange > Shortcut 버튼 클릭 시 calendar 반영되지 않음

---

src/components/grid/Grid.vue

- sort 클릭 이벤트 관련 이벤트 위치 이동
- 위 변경사항으로 인해 filtering 관련 클릭 이벤트 capture -> stop으로 변경

[#1321] grid > sort 이벤트 영역 개선

---

src/components/chart/model/model.store.js

- click 이벤트로 받은 mouse offset의 위치가 X축 시작과 끝 지점보다 크거나 작을 경우 조정하는 로직추가

[#1319] Line Chart > Select Label > 축을 벗어나는 라벨을 클릭하면 동작하지 않음

---

src/components/chart/helpers/helpers.util.js
src/components/chart/model/model.store.js

- legend 타입이 'table'일 경우 차트의 값을 가지고 계산하는 로직이 있음
- 계산하는 로직에서 차트의 값이 MIN_SAFE_INTEGER~MAX_SAFE_INTEGER  사이인지 검사하는 로직 존재
- null 또는 undefine은 무조건 safe하지 않은 값으로 간주하여 warning log 발생
- null은 차트 데이터에서 유의미한 데이터이기 때문에 warning log가 출력될 필요 없어 조건문 삭제함
- Util함수에 JS Docs 추가
- warning 메시지 오탈자 수정

[#1324] Chart Legend > table type 일 때 차트에 값이 null이 들어올 경우 예외처리

---

docs/views/brushChart/example/Default.vue
docs/views/zoomChart/api/zoomChart.md
package.json
src/components/chart/chartZoom.core.js
src/components/chart/uses.js
src/components/chartBrush/ChartBrush.vue
src/components/chartGroup/uses.js

################################
[수정내역]
- 차트에 사용하는 chartData가 업데이트 시 기존에 메모리와, 브러시 선택 영역이 자동으로 초기화 되던 부분을 useResetZoomMemory(default true) 옵션으로 상황에 따라 차트 데이터가 업데이트 되더라도 줌 메모리와 브러시 선택 영역은 초기화가 되지 않도록 수정.

[#1323]Line Chart > Zoom 메모리 초기화

---

src/components/grid/uses.js

- 최초에 그리드 사이즈 설정 시 세로 스크롤이 존재 할 때만 스크롤 넓이를 그리드 전체 넓이에서 빼주고 있음
- 위 조건 없이 그리드 전체 넓이에서 스크롤이 차지하게 되는 넓이를 제외시킨다.

[#1327] Grid > 가로 스크롤이 생기는 이슈

---

docs/views/brushChart/example/SelectLabelGroup.vue
src/components/chart/element/element.line.js
src/components/chart/model/model.store.js

[#1329]Line Chart > Select Label 차트 툴팁에서 날짜 확인 후 클릭해도 간헐적으로 다른 날짜가 선택 됨.
################################    
[원인]
- 클릭한 데이터의 xp 좌표를 가지고 findGraphData 함수를 이용하여 (xp 간격과 각각 데이터의 x 좌표을 이용해서 이진 탐색 함) 전체 데이터에서 좌표에 맞는 데이터의 인덱스를 구하고 해당 값에 seletedLabel이 생성되는데 데이터가 너무 많을 경우 날짜는 다르지만 각각 데이터의 x 좌표가 같게 되고 이진 탐색시 간헐적으로 클릭한 날짜에 정확하게 selectedLabel이 생성되지 않음.
[수정 내용]
- selectedLabel의 v-model 값으로 보내지는 dataIndex를 이용하여 정확하게 findGraphData를 하여 selectedLabel이 생성되도록 하고  tooltip과 같이 클릭 없이 마우스 위치의 값을 보여줘야 하는 경우 기존 xp 좌표를 이용하여findGraphData를 하도록 수정.
- pointSize를 추가하여 차트의 끝 부분을 클릭 시 정확하게 0번째 날짜와 와 마지막 날짜가 선택되도록 수정
[확인 경로]
- Line Chart > SelectedLabel

[#1329]Line Chart > Select Label 차트 툴팁에서 날짜 확인 후 클릭해도 간헐적으로 다른 날짜가 선택 됨.

---

docs/views/heatMap/api/heatMap.md
docs/views/heatMap/example/Category.vue
docs/views/heatMap/example/Custom.vue
docs/views/heatMap/props.js
package.json
src/components/chart/element/element.heatmap.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.legend.js
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/uses.js

작업 내용
-
1.  categoryColors 옵션 추가
- List 순서대로 범주의 label 변경
- categoryColors length가 있는 경우 min, max, categoryCnt 옵션 무시
- 속성
1. color: 범주 색상
3. label: 범주명
`Before`
min, max color내에서 범주 개수에 따라 그라데이션 색상 생성
`After`
사용자 지정 옵션 추가(categoryColors)

[#1334] Chart > HeatMap > 범주별 색상, 라벨 지정 옵션 추가

---

docs/views/barChart/example/SelectLabel.vue
docs/views/heatMap/api/heatMap.md
docs/views/heatMap/example/SelectLabel.vue
docs/views/heatMap/example/Time.vue
docs/views/heatMap/props.js
src/components/chart/element/element.heatmap.js
src/components/chart/element/element.tip.js
src/components/chart/model/model.series.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/plugins/plugins.legend.js

이슈
-
https://app.clickup.com/t/25540965/DEV-6485
작업 내용
-
1. label 선택 기능 추가
2. heatmp용 label tip 그리는 로직 추가
3. selectLabel 관련 description 추가
4. Time 예제 초기 data 함수로 생성하도록 변경
5. 옵션이 업데이트 되는 경우 categoryCnt가 categoryColors length가 아닌 option에 설정된 categoryCnt로 적용되는 이슈 수정
HeatMap SelectLabel  스펙
- 
1. label 선택하는 경우 선택된 label에 해당되는 데이터만 반환
기존 Chart
-  [{ series명: value}, {series명: value}]
HeatMap Chart (series명 반환 x)
- [{x: label, y: label, value: value}, {x: label, y: label, value: value}]
6. fixedPosTop 옵션 사용x (항상 tip이 top에 위치)

[#1337] Chart > HeatMap > label 선택 기능 추가

---

docs/views/heatMap/api/heatMap.md
docs/views/heatMap/example/ColorsByRange.vue
docs/views/heatMap/example/Default.vue
docs/views/heatMap/example/Event.vue
docs/views/heatMap/example/Gradient.vue
docs/views/heatMap/example/SelectItem.vue
docs/views/heatMap/example/SelectLabel.vue
docs/views/heatMap/example/Time.vue
docs/views/heatMap/props.js
src/components/chart/chart.core.js
src/components/chart/element/element.heatmap.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/uses.js

이슈
-
https://app.clickup.com/t/25540965/DEV-6715
작업 내용
- 
1. selectItem 옵션 추가
2. 옵션명 변경
- categoryCnt -> rangeCount
- categoryColors -> colorsByRange
* 변경이유
범주(category): 일한 성질을 가진 부류나 범위.
범위(range): 일정하게 한정된 영역.
**heatmap color 나누는 기준이 value를 나누는 개수에 맞게 min, max로 일정한 영역으로 나누기 때문에
범주보다 범위가 적합하다고 생각하여 옵션명을 변경하게 되었습니다.**
3. stroke을 그리는 경우 x, y, w, h 계산식 수정
4. highlight 효과 및 stroke 그리는 경우 계산식 수정
참고
-
**SelectItem**

[#1339] Chart > HeatMap > item 선택 시 하이라이트

---

.github/actions/jandi-notify/action.yml
.github/workflows/publish-npm.yml
package.json

- npm 배포 시 잔디 메시지 연동
- Release Note: 패치 내역 링크를 제공합니다.
- Release Version: 태그 이름으로 추적하며, 배포된 EVUI 버전을 알려줍니다.
Close #1341

[#1341] Release 웹훅 적용

---

docs/views/brushChart/example/SelectLabelGroup.vue
package.json
src/components/chart/element/element.line.js
src/components/chart/model/model.store.js

################################   
[수정 내용]      
**수정 전**   
**수정 후**
1. 데이터 사이 간격이 존재 할 경우(데이터 간격 0 초과일 경우  (데이터 사이 간격은 0, 0.5, 1... 0.5 배수임 / 0일 경우는 차트의 가시성이 떨어지는 경우임. 아래 한계 참조.))
- 마우스가 움직였지만 현재 툴팁과 이전 툴팁이 같거나 현재 마우스 포인트 기준 좌우 사이 간격이 같을 때 마우스가 우로 움직이고 있었다면 인덱스 +1, 좌로 움직이고 있었다면 인덱스 -1하여 1픽셀 움직일 때 tooltip에 다음 날의 값이 보여지도록 함.
- 그외, 현재 마우스 위치와 가까운 값을 확인하여 tooltip에 보여줌   
2. Tooltip을 확인한 위치에 select label/item 이 생성 되도록 다시 반복문을 돌리지 않고 Tooltip 값 확인하면서 저장 한 index (this.beforeFindItemIndex)를 이용하여 select label/item 생성   
- useSelectLabelOrItem가 false 일 때(Tooltip 표시될 때) this.beforeFindItemIndex에 현재 툴팁의 item.index 저장.
- useSelectLabelOrItem이 true 일 때(select label/item 표시될 때) 이전 툴팁을 확인하면서 저장한 index을 가져다 사용.
3. this.beforeMouseYp !== yp 추가
- 마우스가 Y 축으로만 움직였을 때 이전 Tooltip 그대로 보여줌
**this.beforeMouseYp …

[#1347][EXEM]Line Chart > Tooltip > 마우스 오버 시 일부 시점 포인트 안되는 현상

---

docs/views/calendar/example/Default.vue
docs/views/datePicker/api/datePicker.md
docs/views/datePicker/example/Default.vue
src/components/calendar/Calendar.vue
src/components/calendar/uses.js
src/components/datePicker/DatePicker.vue
src/components/datePicker/uses.js

이슈
-
date, dateTime 모드에선 input에서 바로 입력하여 변경 가능하지만 dateRange, dateTimeRange 모드에선 입력할 수 없음   
range 모드에서도 입력 가능할 수 있도록 개선 필요
기대 효과
-
range 모드도 calendar를 클릭하지 않고 input태그에 입력하여 변경할 수 있음
작업 내용
-
1. enableTextInput (텍스트 입력 활성화) 옵션 추가 
- 현재 프로젝트에 적용된 datepicker가 있으므로 적용된 프로젝트의 수정 범위가 적도록 하기 위해 옵션 추가
- 기본값: false
- enableTextInput : true일 경우 입력 할 수 없도록 적용(date, dateTime 모드도 포함)
- enableTextInput : false일 경우 입력 가능
- **참고** dateMulti 는 항상 readonly: true
- 입력할 때 disabledDate 함수에 포함되거나 invalid한 날짜 입력했을 때 변경되기 전의 날짜로 변경됨 
2. 그 외 이슈 또는 개선
- 함수 안에서만 사용하는 변수들 computed 제거
- range모드에서 clickDate했을 경우 클릭한 calendar의 page만 업데이트
- from 달력의 년,월 페이지가 to 달력의 페이지를 넘어서지 못하는 제한 제거(반대도 동일)
- 이전 from날짜에서 to날짜로 연속된 날짜 표시할 때 사용되었지만 현재 이 기능이 삭제되어 제거
- 추후 다시 기능을 넣을 때 사용 예정
- AS-IS
- TO-BE 
- range 모드에서 현재 달력에서 이전 달력의 날짜가 …

[#1350] DatePicker > dateRange, dateTimeRange 모드 > 사용자 입력 가능 옵션 추가

---

docs/components/Example.vue
docs/views/barChart/api/barChart.md
docs/views/barChart/example/Overlapping.vue
docs/views/barChart/props.js
src/components/chart/chart.core.js
src/components/chart/element/element.tip.js
src/components/chart/model/model.series.js
src/components/chart/model/model.store.js
src/components/chart/uses.js

[ 클릭업 ] https://app.clickup.com/t/25540965/DEV-8157
Stack Bar Chart와 유사하지만 값이 겹쳐지는 형태의 Overlapping Bar Chart 기능 구현
* **overlapping** 옵션 추가
Stack Bar Chart와 유사하게 groups 설정해야 하며, 추가적으로 overlapping: true로 지정해야 정상 작동하게 됩니다.

[#1348] Bar Chart > 겹쳐지는(비율) 표현 방식 추가

---

src/components/chart/uses.js

- ev-chart-group 사용 시 다음과 같은 에러가 발생합니다.
- ![image_2023-02-14_17-01-12](https://user-images.githubusercontent.com/10824092/218679158-690f6289-3c57-4e62-ac23-72ccb09fb62f.png)
- 컴포넌트가 업데이트되었지만 evChartZoom 변수가 없는 경우가 발생하여 valid 로직을 추가하였습니다.
Close #1353

[#1353] evChartZoom 변수 valid 로직 추가

---

package.json
src/components/grid/uses.js
src/components/treeGrid/uses.js

- ![image](https://user-images.githubusercontent.com/53548023/219247566-e5698c1a-47c0-4e51-9b4e-bf69d5fa5b26.png)
- Table-body 내 빈공간에서 마우스 우클릭시 아래와 같은 참조 에러 발생
- ![image](https://user-images.githubusercontent.com/53548023/219247490-8b887c5c-928b-4e71-947e-1a773377cb5f.png)
- optional chaining 추가

[#1355] Grid, TreeGrid > 마우스 우클릭 시 참조 에러 발생

---

docs/views/barChart/example/Event.vue
docs/views/heatMap/api/heatMap.md
docs/views/heatMap/example/SelectBoth.vue
docs/views/heatMap/props.js
docs/views/lineChart/example/Event.vue
src/components/chart/Chart.vue
src/components/chart/chart.core.js
src/components/chart/element/element.heatmap.js
src/components/chart/model/model.store.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/scale/scale.step.js
src/components/chart/uses.js

- HeatMap Chart에서 `selectLabel` 옵션과 `selectItem` 옵션을 동시에 사용할 수 없음. 
- 화면 기획의 요구사항에 따라 두개의 옵션을 동시에 사용할 필요 있음
- `v-model:selectItem` 혹은 `v-model:selectLabel` 둘 중 하나만 사용 가능 
- `v-model:selectItem`, `v-model:selectLabel` 두개 동시에 사용 가능하도록 구조 변경 
- 이럴경우 Item 클릭시 Item 만 클릭된것으로 인식하며, **Label (Axis text)을 클릭했을 경우에만 `selectLabel`로 인식되도록 함** 
_- 기존에는 `selectLabel`을 사용중일 경우, **item을 클릭해도** `selectLabel`로 인식되었음_
1.  `chartOption > selectLabel > useBothAxis` 옵션을 true 로 설정할 경우, 두 가지 축 모두에 이벤트가 동작하도록 개선
- 기존에는 X축 Y축 둘중 한쪽으로만 동작함
2. .Chart > click 이벤트 관련 로직 전체적으로 리팩토링 
- 차트 타입별로 이벤트 처리 방안이 다름에도 불구하고, 옵션명의 유무로 차트의 타입을 유추해야하는 점이 직관적이지 않아 switch 문으로 분리 
3. `selectItem`, `selectLabel` 둘다 사용중인 Example Code 추가
- ![select_label_after](https://user-images.githubusercontent.com/53548023/221526799-fbc3ad2a-2082-4f14- …

[#1360] HeatMap Chart > SelectItem, SelectLabel 두가지 옵션을 동시에 사용할 수 있도록 로직 개선 및 신규 옵션 추가

---

package.json
src/components/chart/Chart.vue
src/components/chart/uses.js
src/components/chartBrush/chartBrush.core.js
src/components/chartGroup/ChartGroup.vue
src/components/chartGroup/uses.js

Click Up: https://app.clickup.com/t/25540965/DEV-8567   
################################   
[원인]
- ev-chart-group 내에 있는 ev-chart의 props(data, options)를 가지고 전체 줌과 ev-chart-brush에 사용해야 하는데 slot의 정보로 props(data, options)를 찾을 경우 element로 감쌀 시 children에 들어있거나 컴포넌트의 경우 null이어서 찾지 못하게 되고 에러가 발생하게 됨.
[수정 내용]
- ev-chart-group에 'evChartPropsInGroup' 반응형 변수를 두고 group 내부에 있는 ev-chart가 생성될 때 ev-chart의 props(data, options)를 evChartPropsInGroup에 넣어 slot 으로 값을 찾지 않고 변수에 담긴 값을 이용하여 그룹에서 줌을 사용 시 brush와 함께 전체적으로 동작하도록 수정.
[확인 경로]
Chart > BrushChart

[#1362] Chart > ev-chart-group 내 ev-chart, ev-chart-brush를 element로 감쌀 시 에러 발생

---

package.json
src/components/calendar/uses.js

이슈
-
disabled 함수 적용되지 않음
원인
-
disabledDate 체크할 때 Date 객체의 파라미터에 공백 제거됨
```
disabledDate(new Date(`${currDate}${timeValue}`))
```
작업 내용
-
disabledDate 함수 파라미터에 공백 추가
```
disabledDate(new Date(`${currDate} ${timeValue}`))
```

[#1357] Calendar > Month, Year picker 기능 추가 > disabled 함수 적용되지 않는 버그 픽스

---

docs/views/barChart/api/barChart.md
docs/views/barChart/example/Event.vue
package.json
src/components/chart/element/element.bar.js

- `selectItem` 기능 사용중, 선택된 항목 외 다른 항목들에 대해 반투명 처리를 할 수 있는 옵션인 `useSeriesOpacity` 추가
- Tip( 위 이미지상 분홍색 부분) 으로만 표시 가능
- 선택된 항목 외 다른 항목들을 반투명하게 처리
- `elemenet.bar.js` 에서 Opacity값을 구할 때 `selectItem` 옵션의 `useSeriesOpacity` 값도 고려하도록 로직 추가함 
- barChart.md에 관련 설명 추가 
- `Event.vue` 예제 코드 수정

[#1372] Bar Chart > useSeriesOpacity 옵션 추가

---

docs/views/lineChart/api/lineChart.md
package.json
src/components/chart/element/element.line.js

-  Line Chart > Point: false 이고, 앞뒤 데이터가 null일 경우, 차트에 표시되지않는 문제 발생
- point를 그릴 때 앞/뒤 데이터가 null인지 체크하는 로직 추가
- docs에 관련 설명 추가

[#1380] Line Chart > Point: false 이고, 앞뒤 데이터가 null일 경우, 차트에 표시되지않는 문제 발생

---

src/components/chart/element/element.bar.js
src/components/chart/element/element.heatmap.js

이슈
-
1. Item Highlight 시 기존 item 크기보다 작게 그려지는 현상
재현 방법
-
1.  Heatmap 예제 중 stroke 옵션의 use: true, lineWidth: 10 이상 으로 할 경우 확인 가능
예상 원인
-
1. itemHightlight 로직에서 stroke를 사용할 경우 x, y point에서 lineWidth만큼 빼서 계산하는 로직
작업 내용
- 
1. itemHighlight 함수에서 lineWidth 계산하는 로직 제거
2. bar, heatmap findItem 함수에서 this.range -> this.filteredCount 로 변경
3. 그 외 이슈 사항 수정
- drag 할 경우 drag한 item을 제대로 찾지 못하는 버그 수정
**Before**
**After**
- scroll 사용 시 drag 할 때 block 단위로 되지 않는 현상 수정
**Before**
**After**

[#1382] Chart > Heatmap > Item Highlight 시 기존 item보다 작게 그려지는 현상 수정

---

package.json
src/components/grid/Grid.vue
src/components/grid/style/grid.scss

- 컬럼의 클릭 이벤트 태그 변경 (li -> span)
- 대신 span 의 영역의 넓혀 이벤트 동작되도록
[ as-is ]
[ to-be ]

[#1384] Grid > 컬럼 리사이즈 시 Sort가 동시에 되는 현상

---

src/components/chart/element/element.heatmap.js

이슈
-
1. Item Highlight 시 기존 item 크기보다 작게 그려지는 현상
재현 방법
-
1.  Heatmap 예제 중 stroke 옵션의 use: true, lineWidth: 10 이상 으로 할 경우 확인 가능
예상 원인
-
1. itemHightlight 로직에서 stroke를 사용할 경우 x, y point에서 lineWidth만큼 빼서 계산하는 로직
작업 내용
- 
1. itemHighlight 함수에서 lineWidth 계산하는 로직 제거

[#1382] Chart > Heatmap > Item Highlight 시 shadow 안쪽으로 그려지는 현상 수정

---

src/components/chart/plugins/plugins.interaction.js

이슈
-
HeatMap > 스크롤 우측 클릭하면 전체 item 흐리게 처리되는 현상 수정
재현 스텝
-
1. Select Label 옵션만 use: true로 변경 (SelectItem은 use: false)
2. 차트 외부 영역 클릭
3. item opacity 확인
예상 원인
-
차트 외 영역 클릭했을 때 예외 처리 없음
작업 내용
-
1. 차트 내부 영역만 클릭했을 때 SelectLabelItem 찾도록 예외처리
` AS-IS`
` TO-BE`
2. 함수 파라미터 warning 제거

[#1397] Chart > HeatMap > 차트 영역 외의 영역 클릭하면 전체 item 흐리게 처리되는 현상 수정

---

src/components/grid/uses.js

브라우저 배율 변경 시 그리드 row(=`<tr>`)의 width와 height가 같이 변경됩니다.
칼럼(=`<td>`) 너비 조정을 위해(옵션 adjust: true)
스크롤 여부를 확인하는 로직에서 row의 height를 고정 값(=옵션에서 설정한 값)으로 가지고 있어,
스크롤이 있는데 없다고 판별하여
칼럼 너비 계산에 오차가 생기는 이슈 발생하였습니다.
row(=`<tr>`)의 실제 height 가져오도록 수정

[#1402] Grid > 브라우저 배율 변경 시, adjust 상태에서 스크롤 생기는 이슈

---

docs/components/MarkdownView.vue

##########
- MarkdownView.vue > .markdown h1 ~ h6에 scroll-margin-top: 80px; 추가

[#1416] MarkdownView > heading 태그에 링크 연결 시 header에 가려지는 현상 수정

---

src/components/chart/plugins/plugins.interaction.js

- [#1401] 이슈 수정에서 발생한 사이드 이펙트
- 사용하지 않는 인자 제거
**Before**
**After**

[#1426] Chart > bar > horizontal 에서 select label 이 동작하지 않는 버그 수정

---

src/components/grid/Grid.vue
src/components/grid/uses.js

**수정내용**
- 컬럼 단일 hide 하는 경우, 마지막 하나 남은 컬럼은 hide 되지 않도록 수정
- columns 데이터를 새로 받아오는 경우, 필터링 되었던 컬럼정보 값들 초기화 해주도록 수정
Close #1431

[#1431] Grid > 컬럼 show/hide 기능 버그 수정

---

docs/views/scatterChart/api/scatterChart.md
docs/views/scatterChart/example/Event.vue
src/common/utils.js
src/components/chart/chart.core.js
src/components/chart/plugins/plugins.interaction.js
src/components/chart/uses.js

- mobile에서 drag가 UX적으로 좋지 않기에 기존 dragSelection에 내부 로직을 통해 mobile인지 감지하고, mobile일 경우 click했을 때 특정 범위만큼 박스로 선택되는 기능 추가

[#1420] Chart > Scatter > drag가 불가능한 mobile을 위한 selection 기능 추가

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/PlotLine.vue
docs/views/scatterChart/api/scatterChart.md
src/components/chart/helpers/helpers.constant.js
src/components/chart/scale/scale.js

- Axis > plotLine 기능에서 lineWidth 옵션을 1로 적용할때와 2로 적용할때 두께가 비슷하게 보이는 현상 발생
- lineWidth: **1**
-  ![image](https://github.com/ex-em/EVUI/assets/53548023/c6c8770a-5212-4d8f-bb6f-e41940003223)
- lineWidth: **2**
- ![image](https://github.com/ex-em/EVUI/assets/53548023/dc9381d3-fb29-4a40-9a7c-2d0db8bd9fe7)
- plot Line 그리기전 안티앨리어싱 로직 추가
- md 파일에 lineWidth 설명 추가
- plotLine > label 옵션 기본값 추가
- lineWidth: **1**
- ![lineWidth1](https://github.com/ex-em/EVUI/assets/53548023/586e71de-d7bf-40f4-a827-96c511031459)
- lineWidth: **2**
- ![lineWidth2](https://github.com/ex-em/EVUI/assets/53548023/04def913-3275-4712-b8f0-478a2f17c812)
- Anti Alias 관련 참고하면 좋은 링크 첨부합니다. 
- https://usefulangle.com/post/17/html5-canvas-drawing-1px-crisp-straight-lines
- https://ui.toast.com/posts/ko_20210526

[#1446] Chart > Axis > PlotLine > anti alias pixel 적용

---

docs/views/grid/example/Default.vue
package.json
src/components/grid/Grid.vue
src/components/grid/style/grid.scss
src/components/grid/uses.js

- label 우측이 아닌 컬럼영역의 우측으로 변경
- Row Contextmenu 클릭 시 로우 선택과 무관하게 옵션 클릭 버튼 동작하도록 변경 필요
- revision update

[#1444] Grid > sort 버튼 위치 변경

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/scatterChart/api/scatterChart.md
docs/views/scatterChart/example/RealTimeScatter.vue
src/components/chart/chart.core.js
src/components/chart/scale/scale.js
src/components/chart/scale/scale.step.js
src/components/chart/scale/scale.time.category.js

- RTM 차트에서 시간 흐름에 따라 Label 위치가 데이터 위치에 맞게 이동하는 기능 추가.
- RealTimeScatter.vue에 적용.
- axis.categoryMode는 고려하지 않았습니다.
- 만약 x축의 labels.length와 구간을 나누는 steps + 1이 같다면 flow 기능이 적용 안되게 하였습니다.
- options.axesX[0].flow로 설정.
다른 의견 환영 합니다.
예시
Closes #1448

[#1448] Chart > Axis > 시간에 따라 x축이 움직이는 기능 추가

---

docs/views/grid/api/grid.md
docs/views/grid/example/Default.vue
package.json
src/components/contextMenu/uses.js
src/components/grid/Grid.vue
src/components/grid/grid.filterSetting.vue
src/components/grid/style/grid.scss
src/components/grid/uses.js

- 컬럼명 field -> caption 표기
- 필터 설정창이 clientWidth를 넘어가면 계산 값으로 위치 조정
- 필터 버튼 변경
- 필터링이 2개 이상일 때, 이전 결과값이 없어도 연산 결과가 정상적으로 나오도록 수정
- comparison operator 셀렉트박스 title tooltip 노출
- string type 대소문자 구분 없이 필터링 되도록 수정
- stringNumber 타입 number값이어도 필터링 정상
- 컬럼 filterable 옵션 추가

[#1457] Grid > Fixes

---

src/components/chart/plugins/plugins.interaction.js

이슈
-
chart type이 scatter & heatmap이 아닌 경우 chart option의 tooltip use: false로 해도 item highlight 됨
작업 내용
-
1. item highlight 그리는 if문 조건 변경
->  tooltip.use 가 true일 때만 그리도록 변경
- before (tooltip use: false이지만 highlight됨)
- after (highlight 되지 않음)

[#1467] Chart > Tooltip 사용하지 않는 경우에도 item highlight 되는 버그 픽스

---

src/components/chart/plugins/plugins.scrollbar.js
src/components/chart/scale/scale.js

이슈
-
scatter chart에서 range 사용하는 경우 제대로 반영되지 않는 이슈
원인
-
heatmap에서 scrollbar 사용하는 경우 min, max를 넘어갈 때 스크롤 바가 영역을 벗어나는 오류가 있어 넣었었던 유효성 체크 로직 때문
해결
-
heatmap인 경우만 min, max 값을 넘어가지 않도록 분기 처리 로직 추가

[#1470] Chart > Scatter Chart > Range 사용할 때 Max Value가 그대로 적용되지 않는 이슈 수정

---

package.json
src/components/grid/Grid.vue
src/components/grid/uses.js

#################################
- 컬럼에 대한 필터링 전체 삭제 시 removeColumnFiltering() -> onApplyFilter() 메서드 호출
- column 사이의 operator 가 and 이지만, 다음 컬럼 필터의 oprator 가 or 이어서 or 연산으로 되었음, 다음 컬럼 필터의 0번째 인덱스 일 땐 column 사이의 operator 로 정상 분기되도록 수정
- sting 타입 값 undefined 시 toLowerCase 값 체크

[#1465] Grid > Filtering Functions Fixes

---

package.json
src/components/grid/Grid.vue
src/components/treeGrid/TreeGrid.vue

###################
- Column List 옵션창을 비롯하여 Column, Row Contextmenu 창들은 다른 영역을 클릭하면 닫히도록 되어있기 때문에 마우스 좌클릭으로 스크롤바를 클릭하여 스크롤하여도 닫히는 기존 동작과 휠을 이용한 스크롤 시에도 통일된 스펙으로 결정
- 단, 그리드 내의 스크롤인 경우에는 닫히는 경우 불편성을 야기시킬 수 있으므로 제외

[#1499] Grid > 스크롤 시 contextmenu 자동 닫힘 추가

---

package.json
src/components/tree/Tree.vue

Tree component의 prop으로 전달받은 data의 길이가 0인 경우 보여지는 문구가 prop으로 전달받은 emptyText가 아니라 No data로 적용되어있어서 수정했습니다.

[#1546] Tree 컴포넌트에 emptyText prop이 적용되지 않는 문제 해결

---

src/components/checkbox/checkbox-group.vue
src/components/selectbox/dropdown.vue

**<작업 진행사항 Log>**    
_2023.11.23_
<br />
> 1. 작업 이유 & 달성목표
MFM 관련 작업 중 발견한 이슈로서,
- stat 내부 checkBox-group의 값이 하위 checkBox와 UI 상호연동이 되지않는 문제
- DropDown 내 input-text 의 스타일로 인해, cursor 가 보이지 않는 문제
를 수정하고자 합니다. 
<br />
<br />
> 2. 부연설명
- checkBox-group에서, 10개 이상으로 클릭이 되지 않도록 사용처 쪽에 로직을 넣었음에도, checkBox-group 내 update 로직 내부
NextTick의 부재로 인해,. UI update가 먼저 처리됨으로 문제가 발현되었습니다. 
- 따라서, NextTick함수를 통해 UI update 시점을 조절하였습니다.
- Input box에서, text를 넣기 위해 클릭을 했을 때, text input cursor가 보이지 않아 사용성에 문제가 있었습니다. 
- 따라서, focus 시점에 cursor를 가리는 border Effect를 제거 / 양 옆측에 padding을 주어 corsur가 시야에서 벗어나지 않도록 수정했습니다.

2.0_MFM_checkBox-group 및 Dropdown 내부 input-text style 수정

---

docs/views/grid/api/grid.md
docs/views/grid/example/Summary.vue
docs/views/treeGrid/example/Default.vue
package-lock.json
package.json
src/components/grid/Grid.vue
src/components/grid/grid.summary.vue

- Grid > Summary 옵션 추가 시에 부동소수점 문제로 자리수 틀어지는 현상 발생
- 버전 : `3.3.67`
bignumber.js 라이브러리를 추가하여 부동소수점 계산을 추가하였습니다.
버전 : `9.1.2`
[AS-IS]
- Total (MB) 컬렘에 Summary를 sum으로 설정했을 시 부동소수점 문제 발생
[TO-BE]
- bignumer.js 라이브러리로 계산하여 부동소수점 해결
(`decimal` 옵션을 sum과 average에 적용하였습니다)

[#1553] Grid > Summary > 부동소수점 처리

---

docs/views/grid/api/grid.md
docs/views/grid/example/Summary.vue
package.json
src/components/grid/Grid.vue
src/components/grid/grid.summary.vue

- summary 옵션 사용시 모든 그리드의 summary가 동일한 decimal로 설정되는 현상
- 컬럼 별로 Summary의 Decimal을 설정할 수 있도록 `summaryDecimal` 추가

[#1555] Grid > Summary > 컬럼 별 decimal 설정 옵션 추가

---

docs/views/treeGrid/api/treeGrid.md
docs/views/treeGrid/example/Default.vue
package.json
src/components/grid/grid.summary.vue

#############################
- 부모의 값이 자식의 합한 값과 같은 경우 Total에 부모의 값만 합산 되어야 하지만 부모의 값과 그 자식을 합친 값들이 중복으로 합산되고있음.   
- tree grid의 summary 계산에서 column에 summaryOnlyTopParent가 true일 경우 최상단 부모 값만 계산될 수 있도록 수정.
summaryOnlyTopParent가 true일 경우

[#1559] Tree Grid > Summary 최상단 부모 값만 계산할 수 있도록 작업 

---

src/components/grid/grid.vue

- 컬럼 너비 확장 시 다음 컬럼이 최소 너비 이상인 경우에만 확장
- 마지막 컬럼에 대한 확장 제한
- 각 컬럼 너비 조정 시 그리드 전체 너비를 유지하는 제약사항이 있어 이에 대한 사용성 편의 개선
- 다음 컬럼의 너비와 상관 없이 마우스 move 지점까지 확장되도록 수정
- 마지막 컬럼도 확장 가능하며 그리드 영역 밖으로의 영역까지 확장되도록 수정 (추후 3.0 에도 반영 예정)
- 각 컬럼의 우측 border 에 마우스 눌러 이동하며 리사이즈하여 확인
- 다음 컬럼의 너비와 그리드 전체너비에 상관없이 자유롭게 확장 가능한지 확인
- 마지막 컬럼도 리사이즈 가능한지 확인
| Before | After  |
| ------ | ------ |
| ![2 0_grid_resize_before](https://github.com/ex-em/EVUI/assets/61657275/fa02d46a-9191-47b0-9b78-5cc599ff9c11) | ![2 0_grid_resize](https://github.com/ex-em/EVUI/assets/61657275/5c227b94-361b-4f96-82b2-c576301e3fe3) |
- #1243

[#1562][2.0] Grid > Improved column resize function

---

package.json
src/components/chart/plugins/plugins.tooltip.js

이슈
-
chart > customtooltip width가 0으로 위치를 제대로 잡지 못해 화면을 벗어남
작업 내용
-
위치를 잡기 전에 display=block으로 tooltip의 offsetWidth잡고 위치를 잡을 수 있도록 코드 위치 변경

[#1565] EVUI > Chart > CustomTooltip 화면 벗어나는 버그 수정

---

docs/views/scatterChart/api/scatterChart.md
docs/views/scatterChart/example/RealTimeScatter.vue
src/components/chart/Chart.vue
src/components/chart/element/element.scatter.js
src/components/chart/model/model.store.js

1. realTimeScatter의 내부 로직 데이터를 덮어쓸 방법이 없어서 위와 같은 문제가 발생.  
series의 데이터가 존재하다가 사라질 경우 반영되지 않음.
2. realTimeScatter > range값을 변경하여도 아무런 반응이 없음.
1. realTimeScatter의 데이터를 초기화 할 수 있는 v-model:realTimeScatterReset 추가.
boolean으로 전달하고, true를 전달하면 내부 데이터가 모두 초기화되고 자동으로 false로 바뀜.
2. range가 반영되기 위해 model.store.js > createRealTimeScatterDataSet 함수의 조건문 일부 삭제

[#1567] Chart > Scatter Chart > Real Time Scatter > 내부 데이터를 초기화하는 메소드 필요, range를 변경할 수 있게 수정 필요

---

docs/views/treeGrid/api/treeGrid.md
docs/views/treeGrid/example/Default.vue
src/components/grid/GridSummary.vue

#############################
MFC는 EVUI 3.3 버전을 사용하고 있어 3.4에 반영이 가능한 PR을 따로 올립니다.
- 부모의 값이 자식의 합한 값과 같은 경우 Total에 부모의 값만 합산 되어야 하지만 부모의 값과 그 자식을 합친 값들이 중복으로 합산되고있음.   
- tree grid의 summary 계산에서 column에 summaryOnlyTopParent가 true일 경우 최상단 부모 값만 계산될 수 있도록 수정.
summaryOnlyTopParent가 true일 경우

[#1559] Tree Grid > Summary 최상단 부모 값만 계산할 수 있도록 작업 (3.0 반영)

---

package.json
src/components/chart/Chart.vue

- 실시간 데이터가 아닌 지난 데이터의 특정 구간을 표현하기 위하여 realTimeScatter.use를 끄고 킬 수 있어야 함.
- realTImeScatter를 끄고 킬 수 있게 하기 위해 Chart.vue에 watch 추가
- 끄고 킬 때마다 realTimeScatter의 데이터를 리셋 해줘야합니다.

[#1569] Chart > Scatter Chart > Real Time Scatter > realTimeScatter.use를 끄고 킬 수 있게 수정 필요

---

package.json
src/components/chart/chart.core.js

일반 scatter => realTimeScatter로 변경 시 위 이미지와 같은 에러 발생.
- 일반 scatter => realTimeScatter로 변경 시 realTimeScatter의 초기 설정 dataSet을 못찾아서 발생하는 오류.  
update시에 dataSet이 존재하지 않는다면 dataSet 초기화

[#1573] 일반 scatter => realTimeScatter로 변경 시 위 이미지와 같은 에러 발생.

---

docs/components/Example.vue
docs/router/index.js

- DOM id 와 hash 를 이용한 Anchor 기능이 없어서 추가 했습니다.
- 수정 사항을 확인 받기 위해 URL 에 hash 를 포함하면, 해당 항목의 정확한 위치로 바로 스크롤 됩니다.
- Docs 의 예제를 이용해서 로컬에서 수정하며 테스트 할 때, HMR 될때 마다 최상단으로 스크롤 되지 않으므로 코드 수정이 용이해 집니다.
- vue-router 의 scrollBehavior 함수를 이용해 스크롤 위치를 변경합니다.
- title element 에 title 값을 이용해 id 를 부여하고, scrollBehavior 에서 찾아가도록 합니다.
- Example 의 타이틀 왼쪽에 ¶ 문자로 앵커를 숨겨두고, 마우스 hover 시 노출되도록 합니다.
- [vue-router scroll](https://router.vuejs.kr/guide/advanced/scroll-behavior.html)
- [테스트 페이지](http://10.20.141.34:9999/lineChart#select-label)

[#1558] Docs > Example Anchor

---

package.json
src/components/chart/Chart.vue
src/components/chart/chart.core.js

- scatter <=> realTimeScatter 전환 시 내부 로직의 차이로 인한 표현의 차이가 있음.
- 기본 scatter는 중복 처리가 안되어 있음. => 이미 그려진 좌표도 덮어서 또 그리는 방식.
- realTimeScatter는 극한의 성능 때문에 이미 그려진 좌표를 그려지지 않게 처리하였음.
- 그 결과 기본 scatter는 마지막 시리즈가 표현되는 반면, realTimeScatter는 첫번째 시리즈가 표현됨.
- realTimeScatter일 경우 series를 reverse

[#1575] Chart > Scatter Chart > Real Time Scatter 시리즈 그리는 순서 변경 필요

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/scatterChart/api/scatterChart.md
src/components/chart/helpers/helpers.constant.js
src/components/chart/helpers/helpers.util.js
src/components/chart/scale/scale.js

- X축 간격을 조절하고 싶음
- interval 옵션과 별개로 interval옵션은 유지하되 표시할 label을 조절하고자 함 
- ![image](https://github.com/ex-em/EVUI/assets/53548023/e9f1bfc6-b7a2-421e-a082-df531d19abbf)
- axesX > labelStyle > padding 옵션 추가 
- ![image](https://github.com/ex-em/EVUI/assets/53548023/06ed970f-52cf-4ffa-a021-068e4261740f)
- padding: 10
- linear, time type의 x축에만 해당되는 옵션

[#1577] Chart > axesX > labelStyle > Padding 옵션 추가

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/Tooltip.vue
docs/views/pieChart/api/pieChart.md
docs/views/scatterChart/api/scatterChart.md
package.json
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/style/chart.scss
src/components/chart/uses.js

- title, label, value 영역 각각 다르게 폰트 컬러 지정 가능 필요
- 기존에는 fontColor 옵션으로 title, label, value 일괄 적용
- ![image](https://github.com/ex-em/EVUI/assets/53548023/dc5487d0-9c50-4f3d-a262-8bfb8fc63355)
- series color shape 를 변경할 수 있는 옵션 필요
- ![image](https://github.com/ex-em/EVUI/assets/53548023/ee7ff4d9-a7c2-4fde-971b-8e1a7afb3b8e)
- padding 값 일부 조정
- 줄 높이 확대

[#1579] Chart > Tooltip > label font color, series color shape 옵션 추가

---

docs/views/message/example/Default.vue
src/components/message/Message.vue
src/components/message/index.js

- Message 컴포넌트에 expose 되는 함수를 추가하였습니다 (hide)
- ctx.$message (또는 EvMessage) 가 expose 된 함수들을 반환하도록 수정
- 관련 문서 추가

[#1581] Message > 외부에서 Message close 할 수 있는 기능 추가

---

docs/views/lineChart/example/CustomTooltip.vue
src/components/chart/Chart.vue
src/components/chart/chart.core.js

- formatter의 html 옵션을 사용했다가 사용하지 않을 경우 html 옵션 때 생성했던 custom tooltip DOM이 제거 되지 않아 지속적으로 보이는 현상 발생 
- ![custom_tooltip_issue](https://github.com/ex-em/EVUI/assets/53548023/f6c2ff75-0615-4411-9dde-dea731864e8c)
- formatter가 변경된 경우, tooltip DOM 제거 후 다시 생성하도록 로직 추가
- ![custom_tooltip_issue_fix](https://github.com/ex-em/EVUI/assets/53548023/48b57d78-502b-4aab-813b-d3af13e2aad4)

[#1587] Chart > tooltip > formatter > html > 동적으로 사용여부 적용 불가한 이슈 발생

---

package.json
src/components/chart/plugins/plugins.tooltip.js

- #1580 에서 header의 padding사이즈를 조정함에 따라 pie Chart Tooltip Header 부분이 도드라져 보임
- ![image](https://github.com/ex-em/EVUI/assets/53548023/d2d38396-756b-4bc3-861a-fcd1e10d60c8)
- tooltip header(title)영역에 표시할 data가 없을 경우 (예시, pie) tooltipHeaderDOM 안보이게 처리
- ![image](https://github.com/ex-em/EVUI/assets/53548023/bbda104f-691a-4847-91e0-8d8bdf8c2b8b)
- version update 3.4.31

[#1585] Chart > Pie > Tooltip > Tooltip Header 영역 표시 미필요

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/Tooltip.vue
docs/views/pieChart/api/pieChart.md
docs/views/scatterChart/api/scatterChart.md
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/style/chart.scss
src/components/chart/uses.js

- Tooltip에 표시되는 font size조정 가능한 옵션 
- Tooltip header 관련 padding Bottom 값 조정
- Before
- ![image](https://github.com/ex-em/EVUI/assets/53548023/40d4b9c0-7721-44e2-951b-e5e623299e56)
- After
- ![image](https://github.com/ex-em/EVUI/assets/53548023/24f03383-a98e-4465-8a5c-ad2a04e4f500)

[#1583] Chart > Tooltip > FontSize 조정 관련 옵션 추가 

---

docs/views/barChart/api/barChart.md
docs/views/heatMap/api/heatMap.md
docs/views/lineChart/api/lineChart.md
docs/views/lineChart/example/Tooltip.vue
docs/views/pieChart/api/pieChart.md
package.json
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/uses.js

- Tooltip의 Series 표현하는 Row의 padding값 조절하는 옵션 필요 
- 사용자가 Tooltip의 Row Padding사이즈를 조절 할 수 있도록 로직 추가

[#1589] Chart > tooltip > Row Padding 옵션 추가

---

src/components/select/uses.js

- 상위 컴포넌트의 setup 내부에서 정의하지 않고, props로 items(전체 리스트)를 받을 경우 최초 렌더링 시점에 items의 갯수가 0이 되어 all checkbox가 true값으로 세팅되는 버그
- 선택된 체크박스 갯수가 0일경우 all checkbox false 처리

[#1591] Select > Multiple Checkable Select > All Check 초기값 버그

---

docs/views/grid/api/grid.md
package.json
src/components/grid/Grid.vue
src/components/grid/uses.js

- 그리드 헤더 컬럼 메뉴의 특정 아이템을 숨김 처리 해야하는 기획 요청 사항
- 각 item 별로 숨김/노출 여부를 결정하는 객체 형태의 hiddenColumnMenuItem 옵션 추가
- 헤더 컬럼 메뉴에서 숨기고자 하는 아이템이 있을 경우 hiddenColumnMenuItem 옵션에 각 아이템 key 값에 대해 boolean 값 적용하여 숨김/노출 설정
- `true`이면 숨김 / `false`이면 노출 / 기본값은 `false` 로, 아무것도 설정 안할 경우 모든 메뉴 아이템 노출
> Before
> After

[#1594] Grid > header context menu 숨김/노출 여부 관련 옵션 추가

---

src/components/grid/uses.js

- 각 컬럼 너비 조정 시 그리드 전체 너비까지만 확장가능한 제약사항이 있어 이에 대한 사용성 편의 개선
- 그리드 영역 밖으로의 영역까지 확장되도록 수정
- 각 컬럼의 우측 border 에 마우스 눌러 이동하며 리사이즈하여 확인
- 그리드 전체너비에 상관없이 자유롭게 확장 가능한지 확인
| Before | After  |
|------ | ------ |
|![resize_before](https://github.com/ex-em/EVUI/assets/61657275/2bd19dd4-843e-40c7-8f09-b5d2d39f8f57) | ![resize_after](https://github.com/ex-em/EVUI/assets/61657275/97f6e0e1-a469-4b97-b553-c433fe495218)|
- #1243 
- #1562

[#1562] Grid > Improved column resize function

---

docs/views/barChart/api/barChart.md
docs/views/heatMap/api/heatMap.md
docs/views/lineChart/api/lineChart.md
docs/views/pieChart/api/pieChart.md
docs/views/scatterChart/api/scatterChart.md
package.json
src/components/chart/plugins/plugins.interaction.js

이슈
-
tooltip value에 series 별 unit을 다르게 표현하기 위해 formatter 파라미터에 seriesId가 필요
수정 내용
-
1. tooltip formatter 함수에 seriesId 추가
2. tooltip formatter 설명 추가

[#1598] Chart > Tooltip > Formatter 파라미터 seriesId 추가

---

package.json
src/components/tree/Tree.vue

이슈 
-
검색 결과가 없을 때 emptyText 보이도록 개선 필요
수정 내용
-
1. TreeNodeData의 visible 이 모두 false일 때 emptyText가 보이도록 수정
[BEFORE]
[AFTER]

[#1600] Tree > 검색 결과가 없을 때 emptyText 보이도록 수정

---

docs/views/barChart/api/barChart.md
docs/views/lineChart/api/lineChart.md
package.json
src/components/chart/plugins/plugins.tooltip.js
src/components/chart/uses.js

- Chart > Indicator > 점선 스타일 추가 
- chartOption > indicator > segments (default: null)
- ![image](https://github.com/ex-em/EVUI/assets/53548023/93e72683-53af-4acd-b509-a8a56438f860)
- ![image](https://github.com/ex-em/EVUI/assets/53548023/b6122f5c-f491-47bc-bb4f-f039fa6dd2d1)

[#1606] Chart > Indicator > Dash 스타일 추가

---

docs/views/lineChart/example/Tooltip.vue
src/components/chart/plugins/plugins.tooltip.js

- 간혈적으로 tooltipDOM의 height이 0으로 계산되는 현상 발생
- tooltipDOM의 height을 구하는 로직 변경

[#1602] Chart > Tooltip > Header DOM 영역이 0으로 계산되는 현상 발생

---

package.json
src/components/chart/plugins/plugins.tooltip.js

1. 같은 화면(document) 내에 tooltip > html 옵션을 사용하는 Chart 2개이상 배치 
2. Tooltip 확인 
1. 마우스 오버한 Chart의 Tooltip Position을 계산하는 과정에서 custom Tooltip DOM을 가져오는 로직이 this.tooltipDOM이 아닌 document로 되어 있어 현재 마우스 오버하지 않은 chart의 너비를 가져와 0으로 계산됨
- 탐색 타겟 변경
- EVUI version (3.4.35 -> 3.4.36)

[#1610] Chart > Tooltip > Html 옵션 사용시 간혈 적으로 width, height값이 0으로 계산됨

---

package.json
src/components/grid/uses.js

임의의 column을 resize하면 adjust가 적용돼있더라도 화면 크기 및 부모의 크기에 따라서 전부 다 resize가 안됨
- 이전엔 어떤 컬럼의 사이즈를 변경해도 resized라는 변수가 활성화되어 부모 크기에따라 resize되지 않았음
- 현재 변경한 컬럼의 index가 일치한 경우에만 resized 라는 변수를 활성화함.

[#1617] Grid > column resize시 그리드 전체 adjust 적용 안됨.

---

docs/views/grid/api/grid.md
docs/views/treeGrid/api/treeGrid.md
src/components/grid/Grid.vue
src/components/grid/GridColumnSetting.vue
src/components/grid/uses.js
src/components/treeGrid/TreeGrid.vue
src/components/treeGrid/uses.js

- 'No records', 툴팁 메뉴명 등 고정 텍스트에 대한 다국어 처리 및 커스텀에 대한 요구 사항
> Before
> After

[#1624] Grid, TreeGrid > 고정 텍스트에 대한 옵션 추가

---

src/components/chart/element/element.line.js

- ![image](https://github.com/ex-em/EVUI/assets/53548023/3cf165db-043b-4d95-a198-3829c13b3980)
-  기존 로직 
- label개수와 상관 없이, data(o)를 기준으로 position을 계산하고 line을 그림 
- label이 없고 data만 있을 땐 내부 로직상 x값이 없고 o값은 있는 형태임
- o값의 유무로만 체크하여 line을 그리고 있었음 
- line Chart 그릴 때 x값이 undefined면 o(original value)가 null일 때와 동일하게 처리되도록 로직 추가
- 툴팁에 표시할 아이템을 찾는 로직에서 x값이 undefined인 요소는 제외하고 탐색하도록 로직 수정
- Label보다 넘치게 들어온 data에 대해서 null과 동일하게 취급한다. 
- line, point, tooltip 표시 X

[#1630] Line Chart > label 개수보다 data 개수가 많을 경우 예외 처리

---

src/components/chart/chart.core.js
src/components/chart/plugins/plugins.interaction.js

이슈
-
1. chart resize 됐을 때 drag 영역 사라짐
2. chart resize 후 drag 영역 다시 그릴 때 chart 크기가 달라지면 이전과 다른 곳에 drag 영역이 그려짐
작업 내용
-
1. resize 이벤트가 일어난 경우 dragInfoBackup 데이터가 있으면 drag 영역을 다시 그리게 호출
2. chart 사이즈가 달라졌을 경우 chart 달라진 비율에 따라 drag 영역 그리도록 수정

[#1638] Chart > Drag 영역 Chart resize 됐을 때 Chart 크기에 맞게 위치와 크기가 변경되지 않는 현상 수정

---

src/components/grid/uses.js

- Grid > Column 이동 시 맨 앞으로 이동되는 현상 발생
- onDrop 이벤트에서 droppedIndex가 undefined가 넘어오는 경우 moving target 컬럼이 맨 앞으로 이동되었습니다.
- `setColumnMoving` 함수에서 인덱스 정보가 integer가 아닌 경우 return 하도록 수정하였습니다.
[AS-IS]
[TO-BE]

[#1622] Grid > Column 이동 시 맨 앞으로 이동되는 현상 수정

---

docs/views/grid/api/grid.md
docs/views/grid/example/ColumnEvent.vue
docs/views/grid/example/RowDetail.vue
docs/views/grid/props.js
docs/views/treeGrid/api/treeGrid.md
docs/views/treeGrid/example/ColumnEvent.vue
docs/views/treeGrid/props.js
src/components/grid/Grid.vue
src/components/grid/uses.js
src/components/treeGrid/TreeGrid.vue
src/components/treeGrid/uses.js

- EVUI Grid, Tree Grid에서 컬럼 변경(컬럼 순서, 컬럼 사이즈, 컬럼 위치, 컬럼 show/hide)시 내부적으로 변경되는 그리드 컬럼의 정보를  emit으로 올려주는 기능이 필요함.
- 이벤트 명 : `resize-column`
- 인자
- column : 현재 대상 target의 컬럼 정보
- columns : 해당 이벤트가 발생된 직후의 전체 컬럼들의 정보
```jsx
emit('resize-column', {
column: stores.orderedColumns[columnIndex],
columns: stores.updatedColumns,
});
```
- 화면
- 이벤트 명 : `change-column-position`
- 인자
- column : 현재 대상 target의 컬럼 정보
- columns : 해당 이벤트가 발생된 직후의 전체 컬럼들의 정보
```jsx
emit('change-column-position', {
column: stores.orderedColumns[droppedIndex],
columns: stores.updatedColumns,
});
```
- 화면
- 이벤트 명 : `change-column-status`
- 인자
- columns: 해당 이벤트가 발생된 직후의 전체 컬럼들의 정보
```jsx
emit('change-column-status', {
columns: stores.updatedColumns,
});
```
- 화면
Grid와 동일하나, `resize-column`, `change-column-status` 이벤트만 존재함

[#1633] Grid > Column 옵션 emit 이벤트 추가

---

docs/views/brushChart/api/brushChart.md
docs/views/brushChart/example/Default.vue
src/components/chartBrush/chartBrush.core.js
src/components/chartBrush/uses.js

3.3-rc에 반영되어 있는 작업을 3.0에 반영하기 위함. (3.3-rc: https://github.com/ex-em/EVUI/pull/1644)
- 브러쉬의 `DEFAULT_OPTION` 에 `useWheelMove: true` 추가
- useWheelMove가 true인 경우에만 wheel 이벤트가 추가되도록 분기 처리

[#1645] Brush Chart 마우스 스크롤 옵션화 (3.0 반영 작업)

---

src/components/grid/Grid.vue

grid에서 sorting을 세팅한 이후에는 grid에 전달하는 데이터가 변경되어도 grid에 반영되지 않는 문제가 있었습니다.
grid row 데이터 변경 시  setStore(value, !sortInfo.sortField);가 실행되는데 sortField가 있는 경우에는 grid 내부 데이터가 업데이트 되는 로직이  !sortInfo.sortField값이 false가 되면서 실행되지 않고 있었습니다. 그 부분을 제거하였습니다.

[#1650] Grid > Sort 적용한 이후 데이터 변경이 grid에 반영 되지 않음
