- src/guide/GuideApp.vue
- src/guide/GuideContent.vue
- src/guide/GuideSource.vue
- src/guide/GuideSummary.vue
> Guide Page > Main Summary Area 추가

- jsdoc.json
- package.json
change jsdoc-vuejs include position
>  jsdoc-vuejs include 위치 변경

- package.json
- styleguide.config.js
> vue styleguide 추가

- src/guide/GuideNav.vue
- src/guide/GuideSummary.vue
eventBus를 통해 emit하는 데이터의 경량화
기존에는 GuideNav.vue에서 데이터의 속성을 추가하였지만,
GuideNav.vue의 데이터를 GuideSummary.vue로 가져온 뒤 속성을 추가하는 방식으로 변경
> Improvement - Guide Page 썸네일 요약페이지 기능 개선

- src/guide/GuideApp.vue
> Parser 기능 부분 수정

- src/guide/GuideNav.vue
메뉴 css 수정
썸네일 이미지 클릭 시 url 이동 파라미터 변경 (menuName -> fileName)
> Improvement - Guide Page 썸네일 요약페이지 메뉴 css수정

- examples/routers/TextBox.vue
> [#78] 2.0 환경 구축

- examples/routers/HelloWorld.vue
- examples/routers/TextBox.vue
> [DONE] 2.0 환경 구축

- examples/routers/TextBox.vue
> [DONE] PR TEST

- .eslintrc.js
- examples/routers/chart.vue
- src/components/chart/chart.vue
- test/unit/specs/chart/chart.spec.js
##########
1. eslintrc.js
- underscore 및 no-plusplus 처리
2. 차트 기본 소스 추가
- 구조 분리 예정
- 기본적인 X축 Y축 데이터에 기반한 라인 생성
> [WIP] chart 개발

- examples/routers/container.vue
- examples/routers/containerbox.vue
- src/components/container/container.vue
- src/components/container/index.js
- src/components/container/resizebar.vue
- test/unit/specs/layout/container.spec.js
1. Container flex 처리
2. resize 소스 추가
> [WIP] vbox / hbox 개발

- src/components/table/table.css
- test/unit/specs/table/table.spec.js
> [WIP]table 개발

- src/components/table/table.vue
##########
Sort, Multi Sort 기능 개발
> 테이블 개발- Sort 기능 추가

- examples/routers/table.vue
- src/common/utils.table.js
- src/components/table/table.vue
##########
1. 테이블에 사용하는 util 파일 분리
2. 그리드 width, height 값 받게 끔 수정(px,%,숫자)
3. Column resize
- size 값을 %, Px, 숫자 혹은 size를 주지 않을 수 있다.
% : 그리드 넓이의 %값을 준다.
px : px 값을 준다.
숫자 : px값으로 준다.
no Size : 사이즈가 없을 경우 위값들을 처리 하고 남은 크기를 자동으로 나눠서 준다. 공간이 없을시 기본 최소사이즈 25p로 할당한다.
- 컬럼 min max 기능 추가. 기본 min 값은 25px
> [#86] 테이블 개발-Resize기능 추가

- examples/routers/chart.vue
- src/components/chart/chart.vue
- src/components/chart/charts/chart.bar.js
- src/components/chart/charts/chart.base.js
- src/components/chart/charts/chart.line.js
- src/components/chart/charts/chart.scatter.js
- src/components/chart/core/axis/axis.scale.steps.js
- src/components/chart/core/core.data.js
Bar, Stack Bar, Column Bar 차트 구현
> [#84] Chart 개발 (Bar차트)

- examples/routers/chart.vue
- src/components/chart/charts/chart.bar.js
- src/components/chart/charts/chart.base.js
- src/components/chart/charts/chart.line.js
- src/components/chart/charts/chart.scatter.js
- src/components/chart/core/axis/axis.js
- src/components/chart/core/axis/axis.scale.fixed.js
- src/components/chart/core/axis/axis.scale.steps.js
- src/components/chart/core/core.data.js
##########
1. Horizontal (Bar, Stack, Column) Bar 차트 개발
2. displayCanvas drawImage 시점 정리
3. Axis Type별 객체 생성 등의 parameter 정리
4. category일 때 x, y 등 value 처리
> [#84] [2.0] Chart 개발 Horizontal Bar 차트

- examples/routers/dock/dockframeSample.vue
- src/components/dock/dockframe.css
- src/components/dock/dockframe.layerpopup.vue
- src/components/dock/dockframe.main.vue
- src/components/dock/dockframe.sub.vue
- src/components/dock/dockframe.tab.nav.vue
- src/components/dock/dockframe.tab.panel.vue
- src/components/dock/dockframe.vue
- src/components/dock/index.js
- DockFrame 삭제 버튼 추가
- DockFrame 삭제 기능 추가
- DockFrame DataMap 삭제 로직 추가
> [#83] 2.0 docklayout 삭제 기능추가

- examples/routers/chart.vue
- examples/routers/charts/chart.bar.vue
- examples/routers/charts/chart.line.vue
- examples/routers/charts/chart.pie.vue
- src/components/chart/charts/chart.bar.js
Examples 수정 및 BarChart category가 없을 시에 대한 예외 처리 추가.
> 2.0 Chart 개발 - Examples 수정

- examples/app.vue
- examples/main.js
- examples/routers/chart.vue
- examples/routers/charts/chart.bar.vue
- examples/routers/charts/chart.line.vue
- examples/routers/charts/chart.pie.vue
- examples/routers/table2.vue
- src/components/chart/charts/chart.bar.js
- src/components/table/table.vue
>  [#86] 가상스크롤 기능 추가

- examples/app.vue
> [#] conflict 해결시 누락 </li> 추가

- examples/app.vue
- examples/main.js
- examples/routers/button.vue
- src/components/button/button.vue
- src/components/button/index.js
- src/index.js
- src/styles/evui.css
> Pr 126 button kjm

- src/components/table/table.vue
##########
virtual Scroll 기능시
데이터가 많을경우 느렸던 성능 개선
> [#86] 테이블 성능 개선

- src/common/utils.js
> [#137] Custom Console

- package.json
> [#78] 웹팩 설정 변경

- src/index.js
##########
네이밍 변경
기존 table , button 등 HTML태그랑 이름이 같을경우
충돌도 생기고, 획일적이지 않아
ex를 추가하여 네이밍 변경
> [#76] evui 라이브러리 네이밍 변경

- src/common/utils.js
######
일부 변수명 변경
parameter > rest parameter 로 변경
error, debug, dir wrapper 추가
> [#137] Console wrapper 수정 및 추가

- home/guide/views/examples/inputnumber/input-number-view.vue
- src/components/codeview/code.vue
######
- description option / isBottom option 추가
- code component 상 하단에 설명을 넣는 기능을 추가함
- isBottom default = false 기본은 상단에 보여주는 기능입니다.
> [#163] code component 기능 추가 작업 진행

- examples/routers/table.vue
- examples/routers/table2.vue
- examples/routers/table3.vue
- src/components/table/table.filter.lite.vue
- src/components/table/table.vue
- src/components/table/table2.css
##########
- table 필터  구조 변경 및 ui 변경
- 데이터 정렬 기능 추가
- 필터 옵션 추가
- 테이블 리사이즈 기능 추가
> [#86] 테이블 filter 개발

- src/components/checkbox/checkbox.vue
######
마지막 parameter 에 old value를 추가
> [#176] CheckBox event parameter 추가작업 진행

- build/webpack.maxgauge.conf.js
=======================
- CopyWebpackPlugin 추가
- path: MAXGAUGE -> maxgauge
- port:8888 -> 9999
> [#174] webpack.maxgauge.conf.js 수정

- src/components/table/table.vue
##########
table height 100%로 안먹던 버그 수정
> [#86] 테이블 개발

- home/guide/views/examples/label/label-default.vue
- src/components/label/label.vue
######
label font bold option 추가
> [#142] label font bold option 추가 작업 진행

- home/guide/views/examples/table/table-buffer.vue
- home/guide/views/examples/table/table-default.vue
- home/guide/views/examples/table/table-page.vue
- src/components/table/table.filter.lite.vue
- src/components/table/table.vue
- src/components/table/table2.css
##########
-컬럼무브 ghost, filter Context menu 위치 이상한데 생기던거 수정
-예제 소스 import 부분삭제
-z-index 관련 수정
> [#86] 테이블 버그 수정

- src/components/table/table.grey.css
- src/components/table/table.navy.css
- src/components/table/table.vue
> [#86] 테이블 css 변경

- src/components/chart/charts/chart.base.js
- src/components/chart/core/axis/axis.js
- linearLabel 관련 수정처리
- 중복코드 추후 수정 예정
> [#84] Chart 임시 수정

- src/components/dock/docking.container.vue
- src/components/dock/docking.css
- src/components/dock/docking.frame.vue
- src/components/dock/docking.splitter.vue
1. Container에 따라 내부 구성요소인 Frame, Splitter에 대한 위치 로직 수정
> [#169] 레이아웃 구성 관련 수정

- src/components/table/table.black.css
- src/components/table/table.vue
> [#86] 테이블 black 테마 추가 및 변경

- src/components/table/table.black.css
- src/components/table/table.grey.css
- src/components/table/table.navy.css
- src/components/table/table.vue
> [#86] 테이블 cellRender 개발

- home/guide/views/examples/tree/tree-table-calltree.vue
- src/index.js
##########
index.js 삭제된부분 복구
콜트리 데이터 트리obj 변경 함수 멕스게이지 util 부분 methods로 카피
> [#86] 트리 테이블 개발

- .eslintrc.js
##########
class-methods-use-this 항목 off
> [#221] 린트 수정

- src/components/tabs/tabs.vue
1. isActive 정상 작동 안하던 부분 수정
2. Render 되기 전에 Scroll Size 를 책정해서 불필요한 스크롤이 생기는 부분 수정
> [#194] Tab Panel 기능 개발

- src/components/window/window.vue
1. onmousemove
2. onmouseout
3. onmousedown
4. onmouseup
5. onheaderdblclick
6. onbeforeclose
> [#197] window 이벤트 추가

- home/guide/views/examples/radio/radio-group-default.vue
- src/components/radio/radio-group.vue
- src/components/radio/radio.vue
- radio.vue, radio-group.vue 컴포넌트에 name 속성 살림
> [#237] radio 컴포넌트 오류 수정

- home/guide/views/examples/label/label-default.vue
- src/components/label/label.vue
Label Align 추가 및 isError 버그 수정
> [#142] Label Align 기능 추가

- src/components/window/window.vue
#########################################
window resize 및 drag 동작 중, 방해받을 일이 없을거 같아 제거함
> [#197] window > mousedown event > preventDefault 제거

- src/components/textfield/textfield.vue
##########
- 중복 CSS 제거
- hideString에 대한 기능 재검토로 코드 제거
- 불필요 코드 일부 변경
> [#145] textfield 기능 확인 진행

- src/components/window/window.vue
####################################################
1. window body component에서 close 가능하도록 이벤트 처리
2. window 외부에서 window close를 위한 api 제공
> [#197] Window 개발

- home/guide/views/examples/window/window-default.vue
- src/components/window/window.vue
#####################################
props 제거 및 component 는 slot 으로 처리
> [#197] window spec 변경

- home/guide/views/examples/checkbox/checkbox-default.vue
- home/guide/views/examples/checkbox/checkbox-group-all-check.vue
- home/guide/views/examples/checkbox/checkbox-group-default.vue
- home/guide/views/examples/checkbox/checkbox-view.vue
- src/components/checkbox/checkbox-group.vue
- src/components/checkbox/checkbox.vue
- 단일 체크박스 기능 개발
- 그룹 체크박스 기능 개발
- 그룹 체크박스에 마우스 클릭 이벤트
- 클릭한 마우스 Event 리턴 (@changeEvent)
> [#249] Checkbox 기능 개발

- home/guide/views/examples/tab/tab-default.vue
- src/components/tabs/tab-panel.vue
- src/components/tabs/tabs.vue
1. tab props 명칭 수정
2. tab panel title props 제거
3. tab css 수정
> [#262] Tab CSS 수정

- home/guide/views/examples/tab/tab-default.vue
- src/components/tabs/tabs.vue
> [#267] Tab Title Icon 추가

- src/components/window/window.vue
> [#197] Window css 수정

- src/components/loadingmask/loadingmask.vue
> [#274] LoadingMask CSS 수정

- src/components/loadingmask/loadingmask.vue
1. 초기 위치값 계산전에 display: none 적용
2. v-if 처리를 v-show로 변경
>  [#274] LoadingMask CSS 수정

- src/components/tree/tree.table.grey.css
- src/components/tree/tree.table.vue
##########
1. 트리 그레이 테마로 변경, 추후 테마 변경 로직이 필요할듯
> [#86] 트리 수정

- home/guide/views/examples/label/label-default.vue
- src/components/label/label.vue
> [2.0] Label 변경 처리

- src/components/tabs/tabs.vue
1. Tab 추가 시 추가된 Tab이 활성화가 되도록 수정
2. Tab이 1개만 남을 경우 Tab 제거 아이콘 안보이도록 수정
> [#281] Tab 추가 시 Active 관련

- home/guide/views/examples/label/label-default.vue
- src/components/label/label.vue
> Label 오프라인 리뷰 결과 반영

- home/guide/views/examples/textfield/textfield-default.vue
- src/common/utils.js
- src/components/textfield/textfield.vue
[#145] Textfield 기능 변경
##########
- v-model 사용가능
- event별 emit 추가
- maxLength 및 regExp에 따른 css처리 기능 강화
- maxLength는  custom code에서 input 태그가 지원하는 기능으로 대체
> [2.0] Textfield 기능 변경

- examples/routers/chart.vue
- examples/routers/charts/chart.line.vue
- src/components/chart/chart.vue
- src/components/chart/charts/chart.base.js
- src/components/chart/core/axis/axis.js
- src/components/chart/core/core.legend.js
- src/components/chart/core/core.util.js
- src/components/chart/core/data/data.js
> Pr 84 chart jw

- src/components/table/table.grey.css
> [#86] 테이블 수정

- src/components/table/table.grey.css
- src/components/table/table.vue
##########
1. text filed 컬럼 추가중
> [#86] 테이블 수정 

- src/components/table/table.grey.css
- src/components/table/table.vue
- src/components/tree/tree.table.black.css
- src/components/tree/tree.table.grey.css
##########
1. 트리 css수정 스크롤 나오지 않는 현상 수정
>  [#86] 트리 css 수정

- build/webpack.liteplus.conf.js
- package.json
- src/components/table/table.grey.css
- src/components/table/table.vue
- src/components/tree/tree.table.black.css
- src/components/tree/tree.table.grey.css
##########
1. 라이트플러스 배포 관련 설정 파일 수정 추후 삭제 예정
>  [#174][2.0]설정파일 수정

- home/guide/views/examples/textfield/textfield-default.vue
- src/components/textfield/textfield.vue
- password type 추가
- css 변경 (password type추가에 따른 prefix 변경 및 height 관련 조절)
> [#295] TextField 변경

- src/components/toggle/toggle.vue
- :class를 위한 불필요한 함수형태 제거
- class 접두어 변경
- toggleType이 slide일 때, 슬라이드 모양이 움직이는 모션이 페이지 로딩될 때 나와
nextTick, setTimeout 후에 v-show하도록 로직 변경
- 그 외 css 수정
> [#298] toggle css 수정

- src/components/checkbox/checkbox.vue
> [#249] checkbox가 table cell에 있을 때 label:before가 정상적으로 나오지 않는 현상 css 수정

- src/components/checkbox/checkbox.vue
- top: 50%, transform: translateY(-50%) 적용
- circle, square / normal, small 모두 적용
> [#249] checkbox css 수정

- home/guide/views/examples/checkbox/checkbox-default.vue
- src/components/checkbox/checkbox.vue
> [#249] checkbox 마이너스 모양 추가

- src/components/loginfield/index.js
- src/components/loginfield/loginfield.vue
- src/index.js
######################
TextField 기반의 LoginField 개발
> [#305] TextField 기반의 LoginField 개발

- src/components/window/window.vue
######################
이미지 교체 등 추후 작업이 추가로 필요한거 같아서 우선 옵션만 추가해서 푸쉬함
> [#197] window 컴포넌트에 maximizable 옵션 추가

- build/webpack.base.conf.js
> [#308] webpack config MiniCssExtractPlugin publicPath 변경

- home/guide/views/examples/loadingmask/loadingmask-custom.vue
- home/guide/views/examples/loadingmask/loadingmask-default.vue
- home/main.js
- package.json
- src/components/loadingmask/loadingmask.vue
- css 박스모델에서 margin은 관계없고, padding과 border에 따라서
로딩마스크 백그라운드와 스피너의 위치를 조정
- 첫번째 예제에서 버튼 클릭 시 ON/OFF가 되도록 개발
- 커스텀 로딩컴포넌트의 props는 Number로 변경
> [#316] LoadingMask 컴포넌트 재개발

- package.json
- src/components/splitter/index.js
- src/components/splitter/splitter.vue
- src/index.js
################################
1. Splitter 컴포넌트 개발
2. Splitter 사용 시 resize 이벤트 처리를 위한 라이브러리 디펜던시 추가 (vue-resize-directive)
> [#320] Splitter 개발

- home/main.js
> [#308] home router path 임시 수정

- src/components/chart/model/model.store.js
##########
null이 들어왔을 때 무한루프 현상 제거
> [#327] chart scale 버그 수정

- examples/routers/charts/chart.bar.vue
- home/guide/views/examples/chart/chart.line.scatter.vue
- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.line.js
- src/components/chart/element/element.scatter.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/plugins/plugins.title.js
- src/components/chart/scale/scale.js
option watch에 따른 title, legend 처리 개선
range 기능 처리
axis label 갯수에 대한 영역 확장
> Chart 버그 수정 및 기능 개선

- src/components/chart/chart.core.js
##########
legend, title 업데이트 시 legend 없는데도 hide하는 로직 수정
> [#327] chart update 버그 수정

- home/guide/views/examples/checkbox/checkbox-default.vue
- src/components/checkbox/checkbox.vue
> [#339] checkbox 체크모양 추가 및 예제 적용

- home/guide/views/content.vue
- home/guide/views/examples/chart/chart-combo-view.vue
- home/guide/views/examples/chart/chart-reactivity-view.vue
- home/guide/views/examples/chart/chart.reactivity.array.func.vue
- home/guide/views/examples/chart/chart.reactivity.replace.object.vue
- home/main.js
- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/scale/scale.js
- 예제 추가
- update에 따른 series 처리 기능 구현
- DOM이 없을 때 -값이 MaxStep으로 만들어지기 때문에 Default값 설정
> Chart 데이터 Watch 기능 변경

- src/components/loginfield/loginfield.vue
크롬 디버깅창에 input type password 관련 Warning 메시지가 출력되는 부분이 있어서 해당 부분 수정
> [#305] LoginField 에 input type 이 password 일 경우 autoComplte 속성 추가

- src/components/textfield/textfield.vue
> [#295] TextField 에 Click Event 추가

- build/webpack.prod.conf.js
- package.json
webpack4 버전업으로 인해 build 시 에러나는 부분 수정 진행.
> [#308] 배포관련 webpack 설정 변경

- examples/routers/chart.vue
- examples/routers/charts/chart.pie.vue
- home/guide/views/examples/chart/chart-pie-view.vue
- home/guide/views/examples/chart/chart.pie.default.vue
- home/guide/views/examples/chart/chart.pie.doughnut.vue
- home/guide/views/examples/chart/chart.pie.sunburst.vue
- src/components/chart/chart.core.js
- src/components/chart/element/element.bar.js
- src/components/chart/element/element.pie.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/model/model.series.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.legend.js
> [#345] 파이차트 리팩토링

- src/components/markdown/index.js
- src/components/markdown/markdown.vue
- src/index.js
> [#355] markdown 컴포넌트 개발

- src/components/table/table.grey.css
> [#357] [2.0] Table Data Copy 가 안되는 부분 수정

- docs/pages/toggle/api/toggle.md
- docs/pages/toggle/examples/type.vue
- docs/pages/toggle/toggle.vue
- src/components/toggle/toggle.vue
- toggle 컴포넌트 너비 로직 변경
- toggle 컴포넌트 설명 추가 (md파일 추가)
> [#298] toggle 컴포넌트 로직 수정 및 설명 추가 (md파일)

- docs/pages/textfield/api/textfield.md
- docs/pages/textfield/textfield.vue
> [#317][2.0] Textfield 컴포넌트 md파일 내용 추가

- docs/pages/datepicker/examples/calendar.vue
- docs/pages/datepicker/examples/default.vue
- docs/pages/loadingmask/api/loadingmask.md
- docs/pages/loadingmask/loadingmask.vue
- loadingmask 컴포넌트 설명 추가 (md파일 추가)
- datepicker 예시에 'ev-' 접두어 추가
> [#316] loadingmask 컴포넌트 설명 추가 (md파일)

- src/components/checkbox/checkbox.vue
- src/components/radio/radio-group.vue
- src/components/radio/radio.vue
##########
- 버튼 라디오 기능 추가(Beta)
> [#391]Radio 버튼 추가

- src/components/datepicker/calendar.core.js
- src/components/datepicker/datepicker.vue
============================
- 인풋박스 내 날짜 값이 모두 채워진 상태에서 특수문자 좌측에 커서를 위치하고 숫자 입력 시 발생하는 버그 수정
- 커서 위치에 따라 인풋박스의 스트링에 slice 처리하는 인덱스 값 수정
- calendar canvas 폰트 수정
> [#389] datepicker inputbox 컴포넌트 버그 수정

- docs/pages/table/examples/new.vue
- docs/pages/table/table.vue
- src/components/grid/grid.filter.vue
- src/components/grid/grid.vue
- src/index.js
#########################################
1. display
2. sort
3. filter
> [#384] 1차 table refactoring

- docs/pages/chart/bar/examples/default.vue
- docs/pages/chart/line/examples/default.vue
- docs/pages/chart/line/examples/stack.vue
- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.bar.js
- src/components/chart/element/element.line.js
- src/components/chart/element/element.pie.js
- src/components/chart/helpers/helpers.canvas.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.pie.js
- src/components/chart/plugins/plugins.tooltip.js
##########
- tooltip 개선
- line, bar 적용
- pie 계열 진행 중
> [#393] Chart Event 기능 개선

- src/components/menu/menu.nav.item.vue
- src/components/menu/menu.nav.sub.vue
1. list
2. expand / collapse
3. select
> [#398] menu 리팩토링

- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.line.js
#########
- Series 정보 변경 시 발생하는 버그 수정
- line fill 상태에서 데이터가 없을 경우 발생하는 버그 수정
- merge 처리 변경
> [#393] Chart 버그 수정

- src/components/toggle/toggle.vue
- 토글 시 스위치의 움직임 너비 조정
- mounted시 토글의 너비가 계속 커지는 버그 수정
- 기타 css 수정
> [#403] toggle 버그 수정

- src/components/toggle/toggle.vue
============================
- 스타일 변경 로직 누락으로 인해 추가
> [#403] toggle 클릭 후 체인지이벤트 시 스타일 변경하도록 로직 추가

- src/components/checkbox/checkbox.vue
- src/components/input/input.number.vue
##########
- checkbox 일반크기에서, disable 일경우 체크모양 css가 깨지는 문제 해결
- inputnumber 위아래 아이콘 모양 깨지는 문제 해결
> [#406] checkbox, input number css 수정

- docs/pages/table/examples/new.vue
- src/components/grid/grid.vue
1. 초기 로딩 시 목록 표시 문제 수정
2. url 직접 접근에 대한 리다이렉션 처리
3. Dom 리사이즈 시 컬럼 사이즈 재 계산 안되는 문제
4. 컬럼 show/hide 기능
5. 이벤트 처리 (row click, checked, selected)
> Table 리팩토링

- src/components/checkbox/checkbox.vue
> [#406] fix input event

- docs/pages/tab/api/tab.md
- docs/pages/table/api/table.md
- docs/pages/table/examples/new.vue
- docs/pages/table/table.vue
1. tab 관련 API 문서 수정
2. table 관련 API 문서 추가
3. table example 수정
> [#411] Add documentation for the table

- docs/pages/chart/line/examples/fill.vue
- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.line.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/model/model.series.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/plugins/plugins.pie.js
- src/components/chart/plugins/plugins.title.js
- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/scale/scale.js
#########
LineChart에서 시간값에 null이 들어오는 경우에 대한 버그 처리
디자인 일부 변경
> [#421] Chart 기능 개선 및 버그 수정

- src/components/radio/radio.vue
> [#426] Remove height of wrap class

- docs/pages/table/examples/new.vue
- src/components/grid/grid.render.vue
- src/components/grid/grid.vue
1. cell renderer
2. cell renderer example
> [#384] Add cell render to grid

- src/components/button/button.vue
- src/components/window/window.vue
- src/styles/themes/mixin.scss
- src/styles/themes/variables.scss
- evui 관련 scss mixin/function명 앞 ev 붙임
- 작명 규칙 확인
- mixin / function: 카멜케이스
- 변수: 스네이크케이스
> [#424] scss mixin/function명 수정

- src/components/loginfield/loginfield.vue
> [#305] loginfield 를 새로운 시안에 맞도록 변경

- src/components/grid/grid.vue
- src/styles/themes/variables.scss
1. css 처리를 scss에 맞게 수정
2. grid 관련 theme 별 컬럼값 정의
> [#437] Fix css to scss

- docs/components/example.vue
- docs/components/header.vue
- docs/components/menu.vue
- src/components/chart/chart.vue
- src/components/codeview/code.vue
- src/components/loadingmask/loadingmask.vue
- src/components/markdown/markdown.vue
- src/components/menu/menu.context.children.vue
- src/components/menu/menu.context.vue
- src/components/selectbox/dropdown.vue
- src/components/slider/slider-tooltip.vue
- src/components/splitter/splitter.vue
- src/components/table/table.black.css
- src/components/table/table.filter.vue
- src/components/table/table.navy.css
- src/components/timepicker/timepicker.vue
- src/components/window/window.vue
> [#436] z-index 조정

- src/components/toggle/toggle.vue
##########
v-model 되게끔 watch 추가
> [#447] toggel v-model 기능 추가

- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.bar.js
- src/components/chart/element/element.line.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/plugins/plugins.tooltip.js
1. destroy 로직 추가
2. tooltip 기능 개선
3. 기타 버그 수정
> [#443] Chart Tooltip 추가 및 기능개선

- src/common/utils.js
- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.line.js
- src/components/chart/helpers/helpers.util.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.tooltip.js
> [#450] Chart MaxTip 기능 개발

- src/components/button/button.vue
- src/components/checkbox/checkbox.vue
- src/components/datepicker/datepicker.vue
- src/components/grid/grid.vue
- src/components/loginfield/loginfield.vue
- src/components/radio/radio.vue
- src/components/selectbox/dropdown.vue
- src/components/selectbox/listbox.vue
- src/components/selectbox/option.vue
- src/components/selectbox/selectbox.vue
- src/components/tabs/tabs.vue
- src/components/timepicker/timepicker.vue
- src/components/toggle/toggle.vue
- src/components/tree/tree.table.vue
- src/components/window/window.vue
- src/styles/themes/variables.scss
- src/styles/utils/mixins.scss
- src/styles/utils/variables.scss
###########
변경 컴포넌트
- window
- button
- checkbox
- radio
- select box
- table(grid)
- timepicker / datepicker (input만)
- toggle
- login
> [#449] theme 작업 및 스타일 정리 1차

- src/components/textfield/textfield.vue
- src/styles/themes/variables.scss
###########
변경 컴포넌트
- text field
> [#449] theme 작업 및 스타일 정리

- src/components/chart/chart.core.js
- src/components/chart/plugins/plugins.legend.js
- src/components/selectbox/selectbox.vue
- src/components/textfield/textfield.vue
- src/styles/themes/variables.scss
mousemove 이벤트가 발생하지 않을 시,
mouseup에서 좌표 변경 계산을 하지 않도록 변경.
legend position에 따라 위치 처리를 다른 style 요소로 하고 있어, 연산을 처리하지 않는 방향으로 처리함.
> [#453] Chart Legend 버그 수정

- src/components/menu/menu.nav.item.vue
- src/components/menu/menu.nav.sub.vue
- src/components/menu/menu.nav.vue
- src/styles/themes/variables.scss
- src/styles/utils/variables.scss
1. 테마별 스타일 정리
2. 메뉴에 필요한 스타일 값 추가
> [#449] Fix style in menu

- src/components/chart/element/element.line.js
> [#453] Chart MaxTip 버그 수정

- src/components/radio/radio.vue
- src/components/textfield/textfield.vue
- src/styles/themes/variables.scss
- radio > type : button 스타일 변경
> [#449] theme style변경

- docs/pages/table/examples/new.vue
- src/components/grid/grid.vue
1. selected / checked 관련 watch 적용
2. All check 선택 시 checked 데이터에 row 데이터 외에 index, check 상태 값도 포함되는 문제 수정
3. renderer 처리 컬럼만 중앙정렬하도록 수정
> [#455] Fix selected and checked in grid

- .eslintrc.js
- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.line.js
- src/components/chart/plugins/plugins.legend.js
Legend에 mouseover시 각 series별 state를 변경하여 highlight 효과처리.
> [#469] Chart Series Highlight 기능 개발

- build/webpack.base.conf.js
- package.json
- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.bar.js
- src/components/chart/element/element.line.js
- src/components/chart/element/element.pie.js
- src/components/chart/element/element.scatter.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/scale/scale.js
- 여백 줄이기
- Stack Chart 버그 수정
- 객체 변경 감지를 좀 더 디테일하게 처리함.
- lodash 사용법 변경
- 크롬 글꼴 확대 시 차트 대응 코드 추가
> [#471] Chart 수정 요구사항 진행

- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.line.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.tooltip.js
##########
- Mouseover MaxHighlight 기능 개발
- mouse event 사용성 개선
- tooltip 옵션처리 변경
> [#471] Chart 기능 개선

- src/components/window/window.vue
> [#449] ev-window 글자 색 변경

- src/components/input/input.number.vue
- wheel up, down 시 min, max값을 넘는 문제 수정
> [#484] input number > wheel 로직 수정

- src/components/chart/chart.core.js
- src/components/chart/element/element.tip.js
########
init이 setTimeout으로 밀리면서 몇 가지 로직에서 시점 데이터가 없어 에러 발생
> [#478] Chart 버그 수정

- src/components/datepicker/calendar.core.js
- src/components/datepicker/datepicker.vue
- theme에 맞게 색상 변경될 수 있도록 로직 개발
- 폰트 변경
- 연도, 요일 변경
- z-index 변경
- 드랍다운 컴포넌트 위치 변경
- 마우스 오버 및 클릭 시 선택되는 일자를 네모에서 동그라미로 변경
- 삼각형을 삼각뿔 화살표로 변경
> [#488] datepicker 스타일 및 로직 변경

- src/components/window/window.vue
> [#197] window > modal z-index 를 710 으로 변경

- src/components/menu/menu.nav.item.vue
- src/components/menu/menu.nav.vue
##########
- menu를 안 보일수 있게끔 히든 속성 추가
> [#495] Menu - hidden 속성 추가

- src/components/datepicker/calendar.core.js
- src/components/datepicker/datepicker.vue
- src/components/message-box/message-box.vue
- datepicker, calendar 디자인 변경
- 최초 인풋박스 클릭 시 calendar에 날짜 세팅하도록 함
- message-box 컴포넌트 $el valid 처리
> [#493] datepicker 스타일 변경 및 버그 수정

- src/components/message-box/message-box.vue
- src/components/message/message.vue
- src/styles/lib/icon.css
- message : 900
- message box : 1000
> [#497] Message / Message Box Z-index 조정

- src/components/tabs/tabs.vue
- src/styles/themes/variables.scss
> [#499] tab 색상 및 디자인 수정

- src/components/chart/element/element.bar.js
- src/components/chart/element/element.line.js
- src/components/chart/element/element.pie.js
- src/components/chart/element/element.scatter.js
########
MaxTip에서 사용하기 위해 Element별 Type추가
> [#478] Chart Element별 Type 추가

- src/components/icon/icon.vue
기존 data로 클래스 적용하던 것을 computed로 변경
> [#507] icon 반응형 수정

- docs/pages/chart/line/examples/default.vue
- src/components/chart/chart.vue
- src/components/chart/plugins/plugins.legend.js
########
- Legend 사이즈 변경
- tooltip 기본 위치 변경
> [#478] 차트 레전드 수정처리

- src/components/input/input.number.vue
- src/styles/themes/variables.scss
> [#512][2.0] Input Number CSS 수정

- src/components/input/input.number.vue
1. spinner 버튼을 통한 up, down 시에 max, min 예외처리가 정상적으로 발생하지 않아 해당 로직 수정
> [#512] Input Number CSS & Event 수정

- src/components/tabs/tabs.vue
###############################################
탭에 마우스오버시 포인터 모양 변경 추가
> [#521] Tab > cursor pointer 추가

- src/components/checkbox/checkbox.vue
- src/components/radio/radio-group.vue
- src/components/radio/radio.vue
> [#525] checkbox, radio 컴포넌트 props type 변경

- src/components/chart/element/element.bar.js
- src/components/chart/element/element.line.js
- src/components/chart/element/element.tip.js
- src/components/chart/plugins/plugins.interaction.js
########
- Tip이 BarChart에서 비정상적으로 동작하여, 해당 부분 수정
- MaxTextTip이랑 겹칠 경우 Tip을 위로 올라가도록 처리
> [#478] Chart Select Tip 버그

- src/components/input/input.number.vue
spinner 버튼 클릭시 최대, 최소값 조건문에 변수 참조가 잘못되어 재수정
> [#512] Input Number Event 수정

- src/components/selectbox/selectbox.vue
컴포넌트 내 select-box 전체 및 input 관련 class 설정 데이터: data > computed 로 수정
> [#530] selectbox 데이터 반응형 수정

- src/components/window/window.vue
##########
- 창 확대 아이콘 초기화 안되던 문제 해결
- Window 바디자식으로 생성되게끔 수정
> [#197] Window 컴포넌트 버그 수정

- src/components/selectbox/dropdown.vue
- src/components/selectbox/listbox.vue
- 드랍다운의 너비는 셀렉트박스 너비와 동일하게 한다.
- 드랍다운 안의 리스트박스의 경우 x, y 스크롤 auto로 변경
- 셀렉트 박스 내용에 title 속성 추가
> [#533] select box > dropdown, listbox 스펙 변경

- src/components/selectbox/listbox.vue
- src/components/selectbox/selectbox.vue
- readOnly 초기값을 true로 변경하여 검색안되는 것을 디폴트로 함
- listbox의 스타일을 변경하여 리스트박스 내 텍스트들을 줄바꿈하도록 함
> [#533] select box, listbox 스펙 변경

- docs/pages/chart/bar/bar.vue
- docs/pages/chart/bar/examples/default.vue
- src/components/chart/chart.core.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/scale/scale.js
- src/components/chart/scale/scale.step.js
########
- step scale일 경우, ellipsis 기능 추가
> [#478] 차트 기능 개선

- src/components/window/window.vue
mout 될때 추가하거나 이동한 element 가 계속 남아 있는 버그 수정
> [#541] Window 버그 수정

- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/scale/scale.step.js
########
- Step의 경우 ...을 붙이는 로직이 있는데, 툴팁에서는 해당 값 제거.
- Title과 Series간의 FontSize 차이가 생겨 해당 부분 반영.
> [#478] Tooltip 버그

- src/components/selectbox/dropdown.vue
#########
- Selectbox 내부 선택한 항목에 스크롤이 가도록 수정
> [#546] Selectbox 내부 선택한 항목에 스크롤이 가도록 수정

- src/components/selectbox/dropdown.vue
> [#546] SelectBox 내부 스크롤 설정

- src/components/selectbox/dropdown.vue
- Selectbox에서 첫번째 항목 선택할 때만 스크롤 위치가 원래 위치보다 조금 아래로 밀려 수정
> [#546] Selectbox에서 첫번째 항목 선택할 때만 스크롤 위치가 원래 위치보다 아래로 밀려 수정

- src/components/grid/grid.vue
1. scrollWidth 옵션 추가
2. qtip 추가
> [#550] Add option & qtip

- src/components/datepicker/calendar.core.js
- src/components/datepicker/datepicker.vue
- src/components/menu/menu.context.vue
> [#552] 리스너 제거로직 추가

- src/components/grid/grid.vue
> [#554] Remove resize

- src/components/checkbox/checkbox-group.vue
- src/components/datepicker/calendar.core.js
- 체크박스 컴포넌트 리스터 제거로직 추가
- 익명함수 사용X
- 캘린더 리스너 bind this
> [#552] 리스너 제거로직 추가, 리스너 bind 추가

- src/components/chart/scale/scale.time.category.js
#########
Axis Label 그리는 부분 마지막값 처리 추가
> [#478] Chart Time Category 축 Steps 처리 변경

- src/components/chart/scale/scale.time.category.js
#########
- 이전 수정 내역 원복
- 최초 개발 시 처리했던 내용을 제대로 기억하지 못하여 잘못 수정처리함.
> [#478] 차트 버그 수정

- src/components/chart/chart.core.js
- src/components/chart/chart.vue
#########
- delete 연산자로 GC가 원활하게 수행되지 않아 null 처리로 변경
> [#564] Chart 성능 개선

- src/components/chart/plugins/plugins.interaction.js
#########
- itemSelect에서 해당 label의 Y값이 null일 경우 0으로 처리
> [#478] itemSelect 기능 변경

- src/components/menu/menu.context.children.vue
- src/styles/themes/variables.scss
#################################
1. 컴포넌트 스타일 적용
> [#566] context menu 스타일 적용

- src/components/grid/grid.vue
> [#569] Fix sort icon

- src/components/grid/grid.vue
- src/styles/themes/variables.scss
1. stripe rows
2. 스크롤 유무에 따른 컬럼계산 처리
> [#572] Grid 기능 추가 및 개선

- src/components/datepicker/calendar.core.js
- Calendar 윤년 2월 일수 계산 누락 버그 수정
> [#574] Calendar 윤년 2월 일수 계산 누락 버그 수정

- src/components/chart/element/element.tip.js
- src/components/chart/plugins/plugins.interaction.js
#########
- MaxTip 및 Indicator의 fixedPosTop 옵션을 차트의 데이터 중 최대값에 맞추는 것이 아닌 차트 Y축의 상위로 올림
- 상기 사항 개발을 진행하며, 예외처리 조건 수정
> [#478] Chart MaxTip 및 Indicator 변경

- docs/pages/tab/examples/default.vue
- src/components/tabs/tab-panel.vue
- src/components/tabs/tabs.vue
- tab title size 옵션 추가
- 의미 없는 코드 제거
- 예제 코드 수정
> [#577] add option for tab title

- src/components/chart/chart.core.js
- src/components/chart/chart.vue
- src/components/chart/element/element.tip.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.legend.js
#########
- Legend의 On/Off 시 Selected Tip이 초기화 되는 이슈 수정
> [#478] Chart Tip 버그 수정

- src/components/grid/grid.vue
- src/styles/themes/variables.scss
1. cell 내부 여백 추가
2. 테마별 스타일 변경 사항 적용
3. 컬럼 내 name / sort-icon 간격 처리
> [#580] grid 관련 수정

- src/components/menu/menu.context.vue
- src/components/window/window.vue
1. context-menu : 300 -> 850
2. window-modal: 710 -> 720
> [#586] z-index 조정

- src/components/grid/grid.vue
> [#580] Grid Lint Fix

- src/components/datepicker/datepicker.vue
- src/styles/themes/variables.scss
> [#594] Theme Color 변경

- src/components/grid/grid.vue
- checked 에 빈 배열을 넣어도 체크가 해제 안되는 문제 수정
- DOM 리사이즈에 따라 처리 안되는 부분 수정
> [#606] grid 버그 수정

- docs/pages/grid/examples/default.vue
- src/components/grid/grid.vue
- 각 메뉴별 validate 함수 처리 추가
- validate 결과에 따른 메뉴 disable/enable 처리
- docs 예제 수정
> [#607] contextMenu disable/enable

- src/components/grid/grid.vue
1. validate 자체를 설정하지 않는 상태에 대한 예외처리
> [#607] context menu bug fix

- docs/pages/grid/examples/default.vue
- src/components/grid/grid.vue
> [#607] add dblclick event on row

- src/components/grid/grid.vue
- align 속성을 이용하여 렌더러 컬럼도 정렬 되도록 수정
> [#607] renderer 컬럼 정렬 처리 추가

- src/components/chart/chart.core.js
- src/components/chart/element/element.bar.js
- src/components/chart/element/element.line.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/model/model.series.js
- src/components/chart/plugins/plugins.interaction.js
#########
- 버그 수정
- element 초기 옵션 처리 merge에서 defaultsDeep으로 변경
- click이 custom listener 유무와 관계없이 select 옵션에 따라 동작하도록 변경
- 기능 추가
- Bar 차트의 막대기에 값이 추가되도록 series 옵션 추가
- `showValue: { use: true, fontSize: 12, textColor: '#000000' }` 형태
> [#478] Bar Chart 값 추가

- docs/App.vue
- docs/components/Example.vue
- docs/components/Header.vue
- docs/components/MarkdownView.vue
- docs/style/lib/highlightjs.github.scss
- docs/style/lib/highlightjs.hybrid.scss
- tests/unit/example.spec.js
- 테마 스타일시트 변경
- provide / inject 적용
> [#623][3.0] Docs 테마 관련 수정

- docs/views/checkbox/example/CheckboxGroup.vue
- docs/views/checkbox/index.vue
- src/components/checkbox/Checkbox.vue
- src/components/checkboxGroup/CheckboxGroup.vue
- src/main.js
- Checkbox 컴포넌트 개발
- CheckboxGroup 컴포넌트 개발
- 각 컴포넌트의 샘플 코드 작성
> [#630] Checkbox, CheckboxGroup 컴포넌트 개발

- docs/pages/tab/api/tab.md
- 오타 수정 disable-move-tab)
- 누락된 props 추가 (title-size)
> [#632] Tab Docs 수정

- docs/views/checkbox/example/CheckboxGroup.vue
- src/components/checkboxGroup/CheckboxGroup.vue
- CheckboxGroup 내 emits의 valid type 추가 (Array)
- All Check 예제 추가
- change 이벤트에서 v-model값 추가하는 예제 수정
> [#630] Checkbox 샘플 기능 추가

- docs/pages/chart/combo/examples/line.stackbar.vue
- docs/pages/chart/combo/examples/stackline.bar.vue
- src/components/chart/chart.core.js
- src/components/chart/element/element.bar.js
- src/components/chart/element/element.bar.time.js
- src/components/chart/element/element.line.js
- src/components/chart/element/element.pie.js
- src/components/chart/element/element.scatter.js
- src/components/chart/element/element.tip.js
- src/components/chart/helpers/helpers.canvas.js
- src/components/chart/helpers/helpers.util.js
- src/components/chart/model/model.series.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/plugins/plugins.pie.js
- src/components/chart/plugins/plugins.title.js
- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/scale/scale.js
- src/components/chart/scale/scale.linear.js
- src/components/chart/scale/scale.logarithmic.js
- src/components/chart/scale/scale.step.js
- src/components/chart/scale/scale.time.category.js
- src/components/chart/scale/scale.time.js
#########
- 예제 코드 버그 수정
- 함수별 jsdoc style comment 추가
> [#478] Chart JSDoc style comment 추가

- src/components/grid/grid.vue
- render cell 의 경우 overflow 속성 초기화
> [#606] 버그 수정

- docs/pages/tree/api/tree.md
- src/components/tree/tree-node.vue
- src/components/tree/tree.vue
> [#604] 트리 개발

- docs/router/index.js
- docs/views/toggle/api/toggle.md
- docs/views/toggle/example/Default.vue
- docs/views/toggle/index.vue
- docs/views/toggle/props.js
- src/components/radio/Radio.vue
- src/components/toggle/Toggle.vue
- src/components/toggle/index.js
- src/main.js
- Toggle 컴포넌트 개발
- DOCS > Toggle 페이지 생성 및 샘플예제 코드 추가
> [#660][3.0] Init & Create Toggle Component

- docs/components/Example.vue
- docs/views/textField/api/textField.md
- docs/views/textField/example/Default.vue
- docs/views/textField/example/Password.vue
- docs/views/textField/example/Textarea.vue
- docs/views/textField/props.js
- src/components/inputNumber/InputNumber.vue
- src/components/textField/TextField.vue
- src/components/textField/index.js
- src/components/textfield/index.js
- src/main.js
- src/style/components/input.scss
- src/style/variables.scss
- textfield > textField / ev-textfield > ev-text-field
- 예제 코드 변수명 변경
- style scoped 제거
> [#644][3.0] textField 컴포넌트명 변경

- docs/components/content.vue
- docs/pages/splitter/examples/default.vue
- docs/pages/splitter/splitter.vue
- docs/router.js
- src/components/splitter/splitter.vue
1. bound 처리 개선
2. 스플리터와 맞닿은 dom 제거 부분 이전으로 복구
3. 스플리터 예제 추가
> [#618] fix splitter

- src/components/selectbox/listbox.vue
- src/components/selectbox/selectbox.vue
##########
- selectbox 아이콘 추가
- placeholder 추가(default: '')
> [#664] Selectbox placeholder 추가, icon 추가

- src/components/contextmenu/contextmenu.vue
##########
- contextmenu 아이콘 추가
> [#667] Contextmenu icon 추가

- src/components/splitter/splitter.vue
1. mousedown / up 이벤트 시점에 emit 이벤트 전달로 부모가 해당 이벤트 시점을 알수 있도록 추가
> [#618] 마우스 이벤트 emit 추가

- src/components/splitter/splitter.vue
- src/components/textfield/textfield.vue
1. 높이 설정 시 placeholder의 가운데 설정을 위해 line-height도 설정되도록 수정
> [#671] textfield height 속성 수정

- src/components/splitter/splitter.vue
##########
- splitter 의 size 가 계산된 min 값으로 bound 를 설정 하도록 수정
> [#681] splitter - right bound 버그 수정

- docs/components/Example.vue
- docs/components/Menu.vue
- docs/router/index.js
- docs/views/Intro.vue
- docs/views/inputNumber/api/inputNumber.md
- docs/views/inputNumber/example/Default.vue
- docs/views/slider/api/slider.md
- docs/views/slider/example/Default.vue
- docs/views/slider/example/Input.vue
- docs/views/slider/example/Mark.vue
- docs/views/slider/example/Range.vue
- docs/views/slider/index.vue
- docs/views/slider/props.js
- src/common/utils.js
- src/components/checkbox/Checkbox.vue
- src/components/inputNumber/InputNumber.vue
- src/components/inputNumber/uses.js
- src/components/radio/Radio.vue
- src/components/slider/Slider.vue
- src/components/slider/index.js
- src/components/slider/uses.js
- src/components/textField/TextField.vue
- src/main.js
- src/style/components/input.scss
- src/style/themes.scss
- src/style/variables.scss
- Slider 2.0 버전 마이그레이션 및 기능 개선 및 추가
: tooltip formatter, hide tooltip / fill color / with input / mark 등 기능 추가
- Input Number 컴포넌트 step-strictly 속성 추가 & 파일 분리 & 버그 수정
- 컴포넌트 scss 테마 변수명 변경
> [#675][3.0] Slider 컴포넌트

- src/components/tree/tree-node.vue
- src/components/tree/tree.vue
- tree css 변경
- 접고 펼쳤을시 빈공간 셀렉트 되는문제 해결
> [#604] 트리 개발 

- src/components/tabs/tab-panel.vue
1. preload 속성 추가
- 탭이 활성화 되지 않더라도 tab 컴포넌트 생성 시 tab-panel 컴포넌트도 생성되는 옵션
> [#689] tab 속성 추가

- src/components/textfield/textfield.vue
컴포넌트 밖에서 validation 처리를 하고 Error Msg 를 넣으면 보이도록 기능 추가
> [#694] TextField > Custom Error Msg 관련 처리 추가

- src/components/textfield/textfield.vue
##########
- Props 로 받은 RegExp 와 errorMsg 에 watch 를 걸어서 에러 메시지 변경과 정규식 변경시 validation 메시지가 변경 되도록 수정
> [#697] TextField > RegExp 및 errorMsg 변경 기능

- docs/router/index.js
- docs/views/notification/api/notification.md
- docs/views/notification/example/Default.vue
- docs/views/notification/props.js
- src/components/message/Message.vue
- src/components/message/index.js
- src/components/notification/Notification.vue
- src/components/notification/index.js
- src/main.js
- src/style/themes.scss
- Notification 2.0 버전 마이그레이션 및 기능 개선
- 옵션별 기능 개발 및 레이아웃 구조 변경
> [#699][3.0] Notification 컴포넌트

- docs/App.vue
- docs/components/Content.vue
- docs/router/index.js
- docs/views/scheduler/api/scheduler.md
- docs/views/scheduler/example/Default.vue
- docs/views/scheduler/props.js
- src/components/scheduler/Scheduler.vue
- src/components/scheduler/index.js
- src/components/scheduler/uses.js
- src/main.js
- 스케쥴러 컴포넌트 개발
- 리펙토링 및 테스트
- DOCS > 스케쥴러 예제 작성
- DOCS > 컴포넌트 마크다운 설명 추가
> [#701][3.0] Scheduler 컴포넌트 개발

- src/components/splitter/splitter.vue
##########
- browser 가 resize 되면 bound 값을 다시 계산하도록 window 에 이벤트 등록
> [#708] splitter > browser resize 이벤트

- src/main.js
- component import 위치 변경
- component install 및 use 로직 수정
> [#615][3.0] main.js  수정

- src/components/contextmenu/contextmenu.wrap.vue
- clientRect가 undefined인 상태에서 .width에 접근하려다가 에러 로그 발생 -> 조건문 추가
> [#711] [2.0] ContextMenu 에러로그 발생

- docs/App.vue
- docs/components/Content.vue
- docs/components/Menu.vue
- docs/router/index.js
- docs/views/menu/api/menu.md
- docs/views/menu/example/Default.vue
- docs/views/menu/props.js
- src/components/contextMenu/ContextMenu.vue
- src/components/contextMenu/MenuList.vue
- src/components/menu/Menu.vue
- src/components/menu/MenuItem.vue
- src/components/menu/index.js
- src/main.js
- src/style/mixins.scss
- src/style/variables.scss
- 2.0 버전 마이그레이션 및 기능 개선
- docs 메뉴 그룹화
- docs 샘플 페이지 작성 및 menu 컴포넌트 적용
> [#729][3.0] Menu 컴포넌트

- src/components/icon/Icon.vue
###########
- setup() 내부 불필요한 async 제거
> [#639][3.0] Icon 컴포넌트 setup() 내부 불필요한 async 제거

- src/components/grid/grid.filter.window.vue
- src/components/grid/grid.render.vue
- src/components/grid/grid.vue
- src/components/tabs/tab-panel.vue
- src/components/tabs/tabs.vue
1. grid 컴포넌트 관련
2. tab 컴포넌트 관련
> [#707] Jsdoc 작성

- docs/router/index.js
- docs/views/tree/api/tree.md
- docs/views/tree/example/Default.vue
- docs/views/tree/index.vue
- docs/views/tree/props.js
- package-lock.json
- src/components/tree/Tree.vue
- src/components/tree/TreeNode.vue
- src/components/tree/index.js
- src/main.js
###########
- router> index.js: tree 메뉴 로드 정보 수정
- views> tree에 tree.md, Default.vue, props.js 파일 추가하고 index.vue 파일은 제거
- src> components> tree에 index.js(ev-tree 등록), Tree.vue, TreeNode.vue 파일 추가
- main.js: 등록한 ev-tree 컴포넌트 전역에서 사용할 수 있도록 추가
- Tree.vue: 트리 정보를 재정의하고 체크박스 선택 해제 시마다 현재 체크된 노드를 기준으로 체크박스 설정을 수정하는 로직이 구현
- TreeNode.vue: 가시적인 트리 구조가 구현되어 있고 체크박스 선택, 컨텐츠 클릭, 트리 펼침/닫힘 처리가 수행됨
> [#734][3.0] Tree 컴포넌트 마이그레이션 진행

- src/components/window/Window.vue
Window 컴포넌트 windowClass props추가
> [#717] Window 컴포넌트 windowClass props추가

- docs/views/menu/api/menu.md
- docs/views/textField/api/textField.md
- docs/views/textField/example/Search.vue
- docs/views/textField/props.js
- src/components/textField/TextField.vue
- TextField 컴포넌트 Search type추가
- md파일 수정
> [#644] TextField 컴포넌트 Search type추가

- docs/views/slider/example/Default.vue
- docs/views/slider/example/Mark.vue
- src/components/slider/Slider.vue
- src/components/slider/uses.js
- Slider 컴포넌트 readonly props 추가 & 샘플 코드 추가
> [#675] Slider 컴포넌트 readonly props 추가

- src/components/inputNumber/uses.js
- 최소값 0 설정 후, 그보다 작은 값 입력 시 동작 오류 수정
- 코드 주석 추가
> [#654] inputNumber bug fix

- docs/components/Menu.vue
- docs/views/menu/api/menu.md
- docs/views/menu/example/Default.vue
- src/components/menu/Menu.vue
- src/components/menu/MenuItem.vue
- items props에 value 프로퍼티 추가(필수), modelValue로 value 넘겨줌
- change 이벤트 파라미터 수정: 기존 text로 받은 값 > 변경 클릭한 메뉴 obj 전체
> [#729][3.0] Menu 컴포넌트 props, event 파라미터 수정

- docs/App.vue
- docs/components/Content.vue
- docs/router/index.js
- docs/views/window/api/window.md
- docs/views/window/example/Default.vue
- src/components/menu/MenuItem.vue
- src/components/messageBox/MessageBox.vue
- src/components/textField/TextField.vue
- src/components/window/Window.vue
- showModalLayer props 추가 & 스타일 수정
- closeOnClickModal props 추가
- lockScroll props추가
- docs scroll 대상 body로 변경
- textField 컴포넌트 아이콘 변경
> [#717][3.0] Window 컴포넌트 props 추가

- src/components/window/Window.vue
> [#717][3.0] Window 컴포넌트 unmounted 시 동작 추가

- .eslintrc.js
- package.json
> [#748][3.0] 베이스 LINT EXEM으로 변경

- package-lock.json
- src/components/chart/chart.core.js
- src/components/chart/element/element.bar.js
- src/components/chart/element/element.bar.time.js
- src/components/chart/element/element.line.js
- src/components/chart/element/element.pie.js
- src/components/chart/element/element.scatter.js
- src/components/chart/element/element.tip.js
- src/components/chart/helpers/helpers.canvas.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/helpers/helpers.util.js
- src/components/chart/index.js
- src/components/chart/model/index.js
- src/components/chart/model/model.series.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/plugins/plugins.pie.js
- src/components/chart/plugins/plugins.title.js
- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/scale/scale.js
- src/components/chart/scale/scale.linear.js
- src/components/chart/scale/scale.logarithmic.js
- src/components/chart/scale/scale.step.js
- src/components/chart/scale/scale.time.category.js
- src/components/chart/scale/scale.time.js
- src/components/chart/style/chart.scss
> [#750][3.0]Chart 컴포넌트 마이그레이션

- docs/views/message/api/message.md
- docs/views/messageBox/api/messageBox.md
- docs/views/notification/api/notification.md
- src/components/loading/Loading.vue
- src/components/message/index.js
- src/components/messageBox/index.js
- src/components/notification/index.js
- src/components/tabs/Tabs.vue
- src/main.js
- Message / MessageBox / Notification 컴포넌트 개별 import 방식 추가
- ev-tab stretch 타입 스타일 수정
- ev-loading full screen 타입 스타일 수정
> [#765] Message / MessageBox / Notification 컴포넌트 개별 import 방식 추가 및 스타일 수정

- docs/views/grid/api/grid.md
- docs/views/grid/example/Default.vue
- src/components/grid/Grid.vue
> [#768][3.0] Grid Style 관련 옵션 추가

- src/components/grid/Grid.vue
- RowHeight min-height 옵션 설정 추가
> [#770][3.0] Grid RowHeight min-height 설정

- docs/views/barChart/api/barChart.md
- docs/views/lineChart/api/lineChart.md
- docs/views/pieChart/api/pieChart.md
- docs/views/scatterChart/api/scatterChart.md
- src/components/chart/Chart.vue
- Chart Resize - debounce wait(timeout)값 옵션화
- 관련 DOCS 모두 수정
> [#774][3.0] Chart Resize - debounce wait(timeout)값 옵션화

- docs/views/messageBox/api/messageBox.md
- docs/views/window/api/window.md
- docs/views/window/example/Default.vue
- package-lock.json
- src/components/messageBox/MessageBox.vue
- src/components/tabs/Tabs.vue
- src/components/window/Window.vue
- 기존: 직접 body 스타일 조정(width, height, overflow)
- 변경: wheel 이벤트 막음
> [#778][3.0] window, messagebox 컴포넌트 내 body 스타일 변경 관련 로직 수정

- src/components/chart/element/element.bar.js
- 초록색 바 안의 값이 누적값으로 표시됨
- 초록색 바가 가지는 값을 표시하도록 수정
> [#796] [3.0] Chart - showValue 버그 픽스

- docs/views/window/api/window.md
- docs/views/window/example/Default.vue
- src/components/select/Select.vue
- src/components/slider/Slider.vue
- src/components/window/Window.vue
- `transform(-50%, -50%)` 사용한 요소관련 흐림 현상 수정
- 기타 불필요 스타일 삭제
> [#801][3.0] transform 사용으로 인해 일부 요소 흐려지는 현상 수정

- README.md
- package.json
> [#753][3.0] Update NPM Version

- src/components/menu/Menu.vue
- src/components/menu/MenuItem.vue
> [#812][3.0] Menu 컴포넌트 로드 시 에러 수정

- src/components/grid/Grid.vue
- src/components/grid/style/grid.scss
- empty row 표시
- selected row 스타일 수정
- Non-Prop Attributes
> [#827] Grid empty row 표시 및 스타일 관련 수정

- docs/views/window/api/window.md
- docs/views/window/example/Default.vue
- src/components/window/Window.vue
- 기존 wheel 이벤트 막는 것에서 body에 paddingRight주고 스크롤 없애는 형태로 수정
> [#840] Window Hide Scroll 로직 수정

- docs/views/lineChart/api/lineChart.md
- 이미 lineChart - Line width 관련 옵션이 존재
- line chart - series 부분 document 내용 보충
> [#793] [3.0] line chart 두께 설정 옵션 추가

- docs/views/pieChart/api/pieChart.md
- src/components/chart/chart.core.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/plugins/plugins.pie.js
- stroke 관련 옵션 추가
- 기본값 
- 문서내용 보충
**1.  기본**
**2. stroke { show : false }**
> [#844] [3.0] chart - pie chart stroke 제거

- docs/views/barChart/api/barChart.md
- docs/views/lineChart/api/lineChart.md
- docs/views/scatterChart/api/scatterChart.md
축(Axis)에 위치할 Label이 길어질 경우 사용가능한 `fitWidth`, `fitDir` 에대한 설명이 누락되어있어 추가
> [#850] [3.0] chart - Axis Label 이 길어질 경우 사용되는 옵션값 설명 추가

- src/components/select/Select.vue
- Select 컴포넌트 내 아이콘 클릭 시 클릭이벤트가 안되는 현상 수정
> [#646][3.0] Select 컴포넌트 내 아이콘 클릭 시 클릭이벤트가 안되는 현상 수정

- src/components/tabPanel/TabPanel.vue
- src/components/tabs/Tabs.vue
- Tab과 TabPanel 간의 provide, inject로 넘겨주는 인자의 반응성 문제 수정
- 변수명 수정
- setup() 내 불필요한 return 프로퍼티 제거
> [#724][3.0] Tab과 TabPanel 간의 provide, inject로 넘겨주는 인자의 반응성 문제 수정

- docs/views/pieChart/api/pieChart.md
Stroke 관련 옵션인 use 대신 show로 작성했던 부분 정정
show -> use
> [#870] [3.0] Chart - Pie Stroke 관련 설명 정정

- src/components/chart/plugins/plugins.legend.js
> 차트를 redraw할때 Legend 관련 DOM Element를 담은 변수가 null/undefined인 경우 에러 코드 발생하지 않도록 return 처리
> [#877] [3.0] Chart legend 관련 예외 처리

- src/components/chart/plugins/plugins.legend.js
> [#877] [3.0] chart legend exception

- src/components/chart/plugins/plugins.legend.js
- src/components/chart/style/chart.scss
legend영역 Click이벤트에서 class 명을 사용하고 있어, 
기존 클래스명을 **수정**하는 로직에서 **추가**하는 로직으로 변경하였습니다.
> [#883] [3.0] line chart legend color style error fix

- docs/views/window/api/window.md
- docs/views/window/example/Default.vue
- src/components/window/Window.vue
- src/components/window/uses.js
- draggable, resizable, maximizable 기능 추가
- 관련 docs 문서 수정
> [#885][3.0] Window draggable, resizable, maximizable 기능 추가

- docs/views/window/api/window.md
- docs/views/window/example/Default.vue
- src/components/window/Window.vue
- src/components/window/uses.js
- 기존 props > style 삭제 & width, height 추가
- 초기 로드 시 window 높이,너비 제대로 반영되지 않는 버그 수정
- props로 받는 크기가 %, vw, vh 일 경우, 크기 제대로 반영되지 않는 버그 수정
> [#885][3.0] Window props 수정 및 기본 스타일 설정 버그 수정

- src/components/window/Window.vue
- src/components/window/uses.js
- 리사이즈 시 최대 크기 지정 & 상단 리사이즈 시 브라우저 넘어가지 않도록 수정
- 스크롤 허용 시 창 position 조정
- 최대화 옵션 버그 수정
- 클래스명 및 변수명 변경
> [#885][3.0] Window 리사이즈 예외 처리 추가

- src/components/window/uses.js
- 드래그 중 브라우저 창 상하단 위치 시, 스크롤 및 창 이동
- 드래그 중 마우스휠 이벤트 발생 시 창 위치 이동
> [#885][3.0] Window 드래그 관련 기능 추가

- docs/views/comboChart/example/LineBar.vue
- src/components/chart/element/element.tip.js
- 이전 선택 위치 기억하도록 로직 추가
- LineBar 예제 코드 누락된 옵션 추가
> [#900] [3.0] Chart - TIP 위치 버그 픽스

- src/components/window/Window.vue
- src/components/window/uses.js
- 브라우저 창 보다 클 경우 top, left 0으로 설정
- 상대 크기로 width, height 설정 시 상대 크기 유지
> [#885][3.0] Window 초기 레이아웃 설정 수정

- docs/views/barChart/api/barChart.md
- docs/views/barChart/example/Column.vue
- docs/views/lineChart/api/lineChart.md
- docs/views/lineChart/example/Default.vue
- docs/views/scatterChart/api/scatterChart.md
- package-lock.json
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/scale/scale.js
- src/components/chart/scale/scale.step.js
1. Axis 내부 옵션으로 `plotLines` 옵션 추가
2. scale.js에서 사용하지 않는 로직 제거 (showIndicator 관련)
3. 관련 문서 작성
4. Sample Code 수정
```
// ... 생략
axesY: [{
type: 'linear',
startToZero: true,
autoScaleRatio: 0.1,
showGrid: false,
plotLines: [{
value: 180,
color: '#FFA500',
label: {
text: 'Warning',
fontColor: '#FFA500',
},
}, {
value: 300,
label: {
lineWidth: 1,
lineColor: '#000000',
fillColor: '#FF0000',
fontColor: '#FFFFFF',
text: 'Critical',
},
}],
}],
```
```
// ... 생략 (chartData)
labels: ['value1', 'value2', 'value3', 'value5', 'value5'],
// ... 생략 (chartOption)
axesX: [{
type: 'step',
plotLines: [{
value: 2,    // labels 배열에서 2 번째 요소 -> value3 에 해당
segments: [2, 1],
label: {
text: 'Caution',
},
}],
}],
```
> [#925] [3.0] Chart > plot line 기능 추가

- docs/views/barChart/api/barChart.md
- docs/views/barChart/example/Horizontal.vue
- docs/views/lineChart/api/lineChart.md
- docs/views/lineChart/example/Fill.vue
- docs/views/lineChart/example/Tooltip.vue
- docs/views/scatterChart/api/scatterChart.md
- src/components/chart/element/element.bar.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/helpers/helpers.util.js
- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/scale/scale.linear.js
- src/components/chart/scale/scale.logarithmic.js
- src/components/chart/scale/scale.step.js
- src/components/chart/scale/scale.time.category.js
- src/components/chart/scale/scale.time.js
- Chart 의 Label 에 해당하는 부분에 formatter기능 추가
> [#918] [3.0] Chart formatter 추가

- docs/views/barChart/api/barChart.md
- docs/views/lineChart/api/lineChart.md
- docs/views/scatterChart/api/scatterChart.md
- package.json
- src/components/chart/chart.core.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/scale/scale.js
- src/components/chart/scale/scale.step.js
1. Axis > labelStyle > show 옵션 추가
2. 기본값 true 설정
3. Axis Label Style Docs에 내용 추가
4. **Minor version update (3.1.39 -> 3.1.40)**
> [#933] [3.0] Chart - Axis Label show 옵션 추가

- src/components/grid/Grid.vue
- checked 된 row와 전체 row의 길이가 같을 때 header 체크박스 체크되도록
> [#945][3.0] Grid Checked 관련 수정

- docs/views/treeGrid/example/CellRenderer.vue
- docs/views/treeGrid/props.js
- package-lock.json
- src/components/treeGrid/TreeGrid.vue
- src/components/treeGrid/TreeGridNode.vue
- src/components/treeGrid/treeGrid.toolbar.vue
[#927][3.0] Cell Renderer 추가
- cellrenderer 추가하기 위해 treegrid > props.js 수정 (cellrenderer 컴포넌트 추가)
- CellRenderer.vue 파일 추가
- TreeGrid.vue, TreeGridNode.vue : cell renderer 추가
> [#927][3.0] treeGrid - cell Renderer 추가

- package.json
3.1.41 -> 3.1.42 version update
> Update Package.json (#949)

- docs/views/calendar/api/calendar.md
- docs/views/datePicker/api/datePicker.md
- docs/views/datePicker/example/Default.vue
- package.json
- src/components/datePicker/DatePicker.vue
- src/components/datePicker/uses.js
- 작업내용
1. option > timeFormat의 validator 및 설명 보완
2. shortcuts의 validator 및 설명 보완
3. date tag 클릭 이벤트 추가 > 클릭 시 dropdown
> [#951][3.0] DatePicker > timeFormat, shortcuts의 validator 및 설명 보완

- src/components/chart/element/element.bar.js
> [#961] [3.0] chart > Stack Bar chart - borderRadius 옵션 추가

- package.json
- src/components/chart/chart.core.js
1. 차트 업데이트 시 horizontal값을 넘기지 않아 발생하는 이슈 픽스
2. evui 버전 마이너 버전 업데이트
> [#963] [3.0] Chart > 높이 혹은 너비계산시 NaN이 리턴되는 현상

- package.json
- src/components/chart/model/model.store.js
1. hasOwnProperty를 null혹은 undefined에 사용할 경우 스크립트 에러 발생하여 조건문 추가
2. EVUI monir version update (3.1.48 -> 3.1.49)
> [#963] [3.0] chart > falsy value issue

- src/components/textField/TextField.vue
#################
- input 이벤트 발생 시 한글일 경우 v-model과 값이 다른 경우 발생 -> nextTick을 이용하여 값이 변경된 후 emit이 발생할 수 있도록 변경
> [3.0] TextField 한글 관련 이슈

- src/components/treeGrid/uses.js
- treeRows 배열을 순회하며 root node가 그려질 수 있도록 수정
> [#979] [3.0] TreeGrid Root Node가 하나만 그려지는 이슈

- package.json
- src/components/chart/Chart.vue
- src/components/chart/chart.core.js
`Keep-alive` 엘리먼트에 대응한 `onDeactivated` hook에서 차트의 Tooltip DOM을 숨기는데,  불특정한 확률로 아래 두가지 상황이 발생되어 예외처리 추가함
1. EvChart 클래스의 인스턴스인 evChart 변수의 값이 빈 객체로 변경되어 있음
2. tooltipDOM 변수의 값이 undefined으로 변경되어 있음
1. 빈객체인지 검사하는 조건문 추가
2. TooltipDOM이 실제로 존재하는지 검사하는 조건문 추가
**3. EVUI Minor Version Update (3.1.51 -> 3.1.52)**
> [#965] [3.0] Chart > keep-alive엘리먼트 관련 처리 코드 예외처리 추가

- src/components/calendar/Calendar.vue
- src/components/calendar/uses.js
1. 끌어서 선택하는 기능 삭제
2. 왼쪽 달력은 from, 오른쪽 달력은 to
- 같은 달의 from, to를 선택한다면 from, to 달력 동일
AS-IS
TO-BE
> [#982][3.0] Calendar > dateRange 모드 SPEC 변경

- docs/views/window/api/window.md
- src/components/window/Window.vue
- src/components/window/uses.js
[ 추가 사항 ] : Window에 ESC 키 누르면 닫히는 기능 추가
-  props에 esc-close 추가
1. Window.vue에 default값 false인 escClose prop 추가
2. uses.js에 esc keydown 이벤트 관리하는 useEscKeydownEvent 추가
- 문서에 esc-close 옵션 추가
> [#994] [3.0] EVUI > Window ESC 누르면 닫히게 개선

- docs/views/window/api/window.md
- docs/views/window/example/Default.vue
- package.json
- src/components/window/Window.vue
- src/components/window/uses.js
- .ev-window dom의 position 속성 변경
- 초기 위치 잡는 로직 수정
- fixed 변경 관련, wheel 이벤트 제거
[기존]
- position: absolute로 body 기준으로 위치 및 크기 잡음
- vw, vh 활용하여 top, left 중앙으로 위치  
[변경]
- position: fixed로 변경
- top, left 50%로 설정, transform 활용하여 중앙으로 위치
> [#991][3.0] Window 초기 스타일 설정 로직 수정

- docs/views/toggle/api/toggle.md
- docs/views/toggle/example/Default.vue
- package.json
- src/components/toggle/Toggle.vue
- toggle 내 읽기전용 옵션 추가, 예제 및 문서내용 추가
- EVUI 3 버전 업데이트
> [#1001][3.0] Toggle 컴포넌트 > readonly 옵션 추가

- src/components/chart/element/element.bar.js
- src/components/chart/model/model.store.js
- Stack Bar Chart 의 `borderRadius` 기능 제거 (코드 롤백)
> [#1004][3.0] Chart - Remove 'borderRadius' option on stack bar chart

- docs/views/treeGrid/example/Toolbar.vue
- src/components/treeGrid/TreeGrid.vue
- src/components/treeGrid/uses.js
**수정사항**
- 숨겨진 컬럼은 검색 대상에서 제거되도록 조건문 추가하여 수정
- 검색어 입력 전/후 체크박스 동작에 버그가 발생하여 검색된 데이터를 searchStore에 관리되도록 추가하여 검색어 입력 전/후에도 체크박스가 정상적으로 동작되도록 수정
ex- 검색 후, 전체 체크하면 검색된 데이터만 전체 체크되도록 수정
**[AS-IS]**
**[TO-BE]**
> [#976][3.0] TreeGrid Search 기능 관련 이슈

- docs/views/grid/example/CellRenderer.vue
- docs/views/grid/example/Default.vue
- src/components/grid/Grid.vue
> [#1014][3.0] Grid 불필요한 method 제거

- src/components/window/uses.js
> [#1009][3.0] Window > 클릭 시 z-index 높이는 기능 추가

- src/components/grid/Grid.vue
- src/components/treeGrid/TreeGrid.vue
- keep-alive 사용 시 onActivated훅에서 데이터를 다시 할당
-> 정확한 원인과 방안 필요
> [#1032] Grid, TreeGrid keep-alive 관련 이슈

- src/components/window/uses.js
- 변경된 스타일 있을 경우, 선 반영되도록 수정  
---
[before]  
[after]
> [#1050] Window Resize 후 Drag 시 크기 조정되는 버그 수정

- package.json
- src/components/grid/Grid.vue
- src/components/grid/uses.js
- src/components/treeGrid/TreeGrid.vue
- src/components/treeGrid/uses.js
#############
- 초기에 searchValue 값이 있을 때만 onSearch 호출
- 리사이즈 관련 이슈
- TreeGrid 노드 무한 루프 이슈
> [#1058] Grid, TreeGrid 관련 이슈

- docs/views/grid/example/Toolbar.vue
- src/components/grid/Grid.vue
- src/components/grid/uses.js
- src/components/treeGrid/TreeGrid.vue
- src/components/treeGrid/uses.js
#############
- 그리드 데이터 변경 시 설정된 검색어로 재필터링
- 트리그리드 checked 데이터 index 로 확인으로 변경
**[AS-IS]**
- '2016' 검색어 입력 후 해당 데이터가 포함된 row가 추가되면 전체 데이터가 보여짐
**[TO-BE]**
- '2016' 검색어 입력 후 해당 데이터가 포함된 row가 추가되면 필터링 돼서 보여짐
> [#1072] Grid > Search 입력 후 데이터 변경 시 재필터링

- docs/router/index.js
- docs/views/pagination/api/pagination.md
- docs/views/pagination/example/Default.vue
- docs/views/pagination/props.js
- package.json
- src/components/pagination/Pagination.vue
- src/components/pagination/index.js
- src/components/pagination/pageButton.vue
- src/main.js
#############
- Pagination 컴포넌트 개발
> [#1084] Pagination 컴포넌트

- src/components/chart/Chart.vue
> [#1095] Pie Chart > selectItem > 빈문자열, null을 넘길경우 선택 해제되지 않는 현상 발생

- docs/router/index.js
- docs/views/heatMap/api/heatMap.md
- docs/views/heatMap/example/Default.vue
- docs/views/heatMap/example/Event.vue
- docs/views/heatMap/props.js
- src/components/chart/chart.core.js
- src/components/chart/element/element.heatmap.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/model/model.series.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/uses.js
작업 내용
-
1. X값에 대한 Y 값의 value(count 등)에 따른 색상 분포 표현
2. Event : Drag, Click, DblClick 기능 가능
3. series 옵션에 count에 따른 color의 옵션 추가 
- min: 그라데이션 min color
- max: 그라데이션 max color
- categoryCnt : color array length(그라데이션 분류 개수)
- border: item border color
- error: item error color (count가 -1경우 error)
4. series 옵션에 spaces 옵션 추가
- x: x축 칸 개수
- y: y축 칸 개수
5. tooltip 명: x축 범위 / y축 범위, value값 
6. legend click 및 resize 기능 추가
> [#1089] Chart > HeatMap 개발

- src/components/chart/scale/scale.js
- src/components/chart/scale/scale.step.js
- src/components/chart/scale/scale.time.category.js
1. 사용자가 rgba로 입력할 경우 입력한 투명도가 아닌 1로 고정되었던 로직 수정
> [#1114] Chart > Axis > LabelStyle 버그

- docs/views/barChart/api/barChart.md
- docs/views/barChart/example/SelectLabel.vue
- docs/views/lineChart/api/lineChart.md
- docs/views/lineChart/example/SelectLabel.vue
- docs/views/lineChart/props.js
- src/components/chart/element/element.line.js
- src/components/chart/element/element.tip.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/scale/scale.js
**1. 라인차트와 콤보차트에서 Select Label 가능하도록 변경**
**2. 관련 설명 및 예제 코드 추가** 
**3. `drawLabelTip` 함수 리펙토링 및 Label 축이 이산(discrete)적 이지 않은 경우 예외처리**
**4. `v-model:selectedLabel` 에 바인딩한 변수가 없더라도 정상 동작 하도록 데이터 초기화 부분 수정**
> [#1117] Line Chart > Select Label  (#1117)

- docs/views/grid/example/Summary.vue
- docs/views/treeGrid/api/treeGrid.md
- docs/views/treeGrid/example/Default.vue
- docs/views/treeGrid/example/Toolbar.vue
- package.json
- src/components/grid/grid.summary.vue
- src/components/grid/uses.js
- src/components/treeGrid/TreeGrid.vue
- src/components/treeGrid/TreeGridNode.vue
- src/components/treeGrid/uses.js
- Pagination 기능 추가
- row 다중 선택
- 하이라이트된 row로 스크롤 이동
- Summary 기능 추가
-> 노드 접힙/펼침 상태 변화에 따른 paging 처리
-> 하이라이트된 row로 스크롤 이동 시 하이라이트 노드의 부모 자동 펼쳐주기
> [#1118] TreeGrid > 그리드 신규 기능 추가

- docs/views/heatMap/api/heatMap.md
- docs/views/heatMap/example/Time.vue
- src/components/chart/element/element.heatmap.js
- src/components/chart/scale/scale.step.js
- src/components/chart/scale/scale.time.category.js
작업 내용
-
1. time(categoryMode) type에 rangeMode 추가
- categoryMode인 경우만 사용 가능
- 축에 표시할 값을 line에 표시할지의 여부
> [#1123] Chart > HeatMap > time(categoryMode) rangeMode 추가

- package.json
- src/components/grid/Grid.vue
- src/components/treeGrid/TreeGrid.vue
- v-model: selected 를 설정하지 않았을 경우 멀티 선택 되는 이슈
> Grid, TreeGrid > selected 멀티 선택 되는 이슈

- docs/views/lineChart/api/lineChart.md
- docs/views/lineChart/example/SelectSeries.vue
- docs/views/lineChart/props.js
- src/components/chart/Chart.vue
- src/components/chart/chart.core.js
- src/components/chart/element/element.tip.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/uses.js
**1. Select Series 기능추가**
- line chart 한정 기능으로 legend 에서 mouse hover 동작에 사용되는 `highlight, downplay` 상태를 변경하여 시리즈의 선택 상태를 고정하도록 하여 구현함
- 클릭된 위치의 series 를 찾는 방식이 일반 line chart 와 stack chart 에서 달라집니다
- 일반 line chart 는 직선과 클릭 위치 사이의 거리를 이용하며, stack chart 는 직선보다 클릭 위치가 아래에 있는지를 확인하여 판단합니다
- https://content.byui.edu/file/b8b83119-9acc-4a7b-bc84-efacf9043998/1/Math-2-11-2.html
- https://brilliant.org/wiki/dot-product-distance-between-point-and-a-line/
- https://stackoverflow.com/questions/3838319/how-can-i-check-if-a-point-is-below-a-line-or-not
**2. 관련 설명 및 예제 코드 추가**
> [#1130] Line Chart > Select Series

- docs/views/grid/example/Summary.vue
- docs/views/treeGrid/example/Default.vue
- src/components/grid/Grid.vue
- src/components/grid/grid.summary.vue
- src/components/grid/uses.js
- src/components/treeGrid/TreeGrid.vue
- src/components/treeGrid/uses.js
- summary 영역 스크롤 내부에 미포함
- summary 값에 title 속성 추가
- float 타입 합계에서도 콤마(,) 추가
> [#1138] Grid, TreeGrid > Summary 관련 이슈 및 수정사항

- docs/views/menu/api/menu.md
- docs/views/menu/example/Default.vue
- src/components/menu/Menu.vue
- src/components/menu/MenuItem.vue
> [#1148] Menu > disabled 옵션 추가

- package.json
- src/components/grid/uses.js
- row 마우스 우측 클릭하여 context menu 사용 시 클릭한 row 데이터 조회 관련 이슈
> [#1152] Grid > ContextMenu 관련 에러로그 발생

- package.json
- src/components/chart/chart.core.js
1. #1156  관련하여 작업한 코드 중 Pie Chart에서 에러로그가 발생하여 예외처리 추가
2. Version Update 3.3.18 -> 3.3.19
> [#1156] Pie Chart 에러로그 발생

- docs/views/heatMap/api/heatMap.md
- docs/views/heatMap/example/Default.vue
- docs/views/heatMap/example/Gradient.vue
- docs/views/heatMap/example/Time.vue
- docs/views/heatMap/props.js
- package.json
- src/components/chart/chart.core.js
- src/components/chart/element/element.heatmap.js
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/model/model.series.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.legend.gradient.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/style/chart.scss
- src/components/chart/uses.js
작업 내용
-
1. gradient legend 추가
2. item highlight css 변경
3. stroke border-radius 옵션 추가
> HeatMap > graident legend 추가

- src/components/chart/element/element.heatmap.js
- src/components/chart/plugins/plugins.legend.gradient.js
작업 내용
-
Chart Data가 없는 경우 (series, labels, data) 예외 처리 추가
> [#1166] HeatMap > Gradient Legend series가 없는 경우 예외 처리

- src/components/grid/Grid.vue
- src/components/grid/style/grid.scss
- src/components/treeGrid/TreeGrid.vue
- src/components/treeGrid/style/treeGrid.scss
> [#1184] Grid, Tree Grid > 데이터 없어도 Scrollbar 생성

- package.json
- src/components/chart/plugins/plugins.tooltip.js
- 항상 value를 그리는 로직은 정상적으로 수행하지만,  간혈적으로 화면에 나타나지않는 현상 발생
- tooltipDOMdml  display 속성이 'block' 으로 변환된 후 fill Text를 하도록 함수 호출 순서 변경
> [#1187] Chart > Tooltip 데이터가 간혈적으로 보이지 않는 현상 발생

- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.legend.gradient.js
작업 내용
-
1. 데이터 없을 때 drag 하는 경우 console error 예외처리
2. series가 없을 때 getElementByClassName console error 예외처리
> [#1191] Chart > HeatMap 데이터 없을 때 drag 하는 경우 console error 예외처리

- src/components/chart/plugins/plugins.interaction.js
작업 내용
-
HeatMap Tooltip value가 음수일 경우 'error'로 표시
참고 내용
-
[#1189] pr merge 된 후에 merge 필요
> [#1196] Chart > HeatMap Tooltip value 음수일 경우 'error' 표시

- docs/views/pieChart/api/pieChart.md
- docs/views/pieChart/example/ShowValue.vue
- src/components/chart/element/element.pie.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.pie.js
- showValue - formatter - percentage parameter 추가
- tooltip - formatter - percentage parameter 추가
- 관련 설명 추가
- showValue example code 에서 textColor 항목 삭제
> [#1195] Pie Chart > showValue > Formatter 인자 추가

- docs/views/heatMap/api/heatMap.md
- docs/views/heatMap/example/Time.vue
- docs/views/heatMap/props.js
- package.json
- src/components/chart/helpers/helpers.constant.js
- src/components/chart/scale/scale.step.js
- src/components/chart/scale/scale.time.category.js
작업 내용
-
1. Axis 옵션 rangeMode 삭제
2. Axis Label 옵션 alignToGridLine 추가(이전 rangeMode 기능 동일)
> alignToGridLine: 축 line에 표시할지의 여부
4. Axis step type displayLine인 경우 number로 이루어진 경우만 높이에 따라 label 표시 조정
> [#1216] HeatMap > 축의 rangeMode -> Axis Label Style의 alignToGridLine으로 변경

- docs/views/barChart/api/barChart.md
- docs/views/comboChart/example/TableTypeLegend.vue
- docs/views/comboChart/props.js
- docs/views/lineChart/api/lineChart.md
- docs/views/pieChart/api/pieChart.md
- docs/views/pieChart/example/Legend.vue
- docs/views/pieChart/props.js
- package.json
- src/components/chart/Chart.vue
- src/components/chart/chart.core.js
- src/components/chart/helpers/helpers.util.js
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.legend.js
- src/components/chart/style/chart.scss
- src/components/chart/uses.js
- chartOption > legend > table 옵션 추가
- name, min, max, avg, total, last 값 표시 여부 및 style, formatter 등 각각 설정가능
- Pie, Line, Bar 차트에서만 사용 가능
- 예제 코드 추가
- PieChart / Legend.vue
- ComboChart / TableTypeLegend.vue
- chartData > series > show: false 인 값들이 legend 영역에 반영되지 않는 버그 픽스
- Before
- ![image](https://user-images.githubusercontent.com/53548023/176810899-86469182-255a-496b-881a-99d7237a3f4c.png)
- After
- ![image](https://user-images.githubusercontent.com/53548023/176810854-6959d882-1fe1-4cfa-9dfe-846c438dbbae.png)
```
legend: {
show: true,
position: 'bottom',
height: 150
table: {
use: true,
style: {
header: {
color: '#495057',
borderBottom: '2px solid #DDDDDD',
},
row: {
borderBottom: '1px solid #DDDDDD',
},
},
columns: {
name: {
title: 'Series Name',
style: {
minWidth: '100px',
maxWidth: …
```
> [#1225] Chart > Legend 영역 value 관련 데이터(min, max, avg, total, last) 표시

- package.json
- src/components/grid/uses.js
> [#1232] Grid, TreeGrid > row 마우스 우클릭 시 select 해제 이슈

- LICENSE
> [#1236] Update Year In License File

- src/components/chart/model/model.store.js
#################################
1. Nullish Coalescing Operator 를 추가하여 null 또는 undefined 일 경우 null로 데이터가 관리될 수 있도록 로직 수정
> [#1251] Chart> 데이터로 undefined 배열이 넘어갈 경우, line이 상단에 그려지는 현상 발생

- src/components/button/button.vue
- src/components/icon/icon.vue
- src/components/message-box/message-box.vue
###############################################
- 배포 전, 내부에서 ev 태그를 사용하여 문제 발생 확인했고 components 추가해줌
> [#1259][2.0] MessageBox > EvButton, EvIcon 참조 관련 이슈

- .github/workflows/publish-npm.yml
- `NPM_TOKEN` 시크릿 키 생성
- release 시 npm 배포 자동화
> [#1266] npm 배포 자동화

- docs/views/scatterChart/api/scatterChart.md
- docs/views/scatterChart/example/Default.vue
- docs/views/scatterChart/example/DisplayOverflow.vue
- docs/views/scatterChart/example/Event.vue
- docs/views/scatterChart/props.js
- src/components/chart/chart.core.js
- src/components/chart/element/element.scatter.js
- src/components/chart/scale/scale.js
|스크린샷|내용|
|-|-|
|![image](https://user-images.githubusercontent.com/81760347/192270172-cb2b1966-7a6e-41d3-bd1f-1de4a94e0284.png)|displayOverflow 신규 옵션 추가하여 Y축의 최댓값 이상의 값이 표현되도록 구현하였습니다.|
|![image](https://user-images.githubusercontent.com/81760347/192270572-723d2725-d665-44d0-96f6-0e964f33176b.png)|Y축의 끝선이 맞지 않는 부분을 수정하였습니다.<br>다른 type의 차트에도 적용됩니다.|
> [#1289] Chart > Scatter > Y축 최댓값 이상의 값 표시 기능

- package.json
- src/components/chartBrush/chartBrush.core.js
#########################################
- 브러시 감도 최적화
- 마우스 이동되는 속도(감도)에 따라 브러쉬의 영역도 같이 이동되도록 수정
> [#1304] Chart > Brush 감도 최적화

- src/components/calendar/Calendar.vue
이슈
-
Arrow 버튼 영역 mouse over할 때 아이콘 색상 변경 되지 않음
재현 방법
-
1. 프로젝트(SAP, MFC) PA 화면 진입
2. datepicker 클릭
3. calendar의 arrow hover
기대 결과
-
버튼 클릭이 되는 영역이면 아이콘 색상 변경 돼야 함
실제 결과
-
버튼 클릭이 되는 영역이지만 아이콘에 hover하지 않는 이상 색상 변경 되지 않음
작업 내용
-
1. hover 영역을 부모 element 로 변경
2. disabled 클랙스를 i 태그가 아닌 부모 element로 위치 변경
3. 각 dom에 접근이 쉽도록 class 추가 및 변경
4. header size 변경
> [#1312] Calendar > Arrow 버튼 영역 mouse over할 경우 아이콘 색상 변경 안되는 현상 수정

- docs/views/brushChart/example/SelectLabelGroup.vue
- package.json
- src/components/chart/element/element.tip.js
- src/components/chart/model/model.store.js
####################################
- 데이터 존재 유무 상관 없이 SelectLabel이 표시되도록 수정.
> [#1317] Chart > SelectLabel 데이터 존재 유무 상관 없이 표시되도록 수정

- package.json
- src/components/grid/Grid.vue
- src/components/grid/uses.js
- 데이터 변경 시 리사이즈 되도록 수정
[as-is]
- 최초에 한번만 리사이즈
- 처음에 데이터가 없어서 세로 스크롤이 없을 경우 나중에 데이터가 많아졌을 때 틀어짐
[to-be]
- 데이터가 변경되면 리사이즈
> [#1327] Grid > 가로 스크롤이 생기는 이슈

- src/components/chart/chart.vue
- src/components/chart/helpers/helpers.canvas.js
- src/components/chart/helpers/helpers.util.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/plugins/plugins.tooltip.js
2.0 버전의 차트 툴팁에서 스크롤을 제공하지 않아 툴팁에 표기할 내용이 많을 경우, 내용을 다 확인 할 수 없는 문제
3.0 버전에서 제공하고 있는 툴팁 useScrollbar 옵션 및 maxWidth / maxHeight 옵션 추가
> [#1359][2.0] chart tooltip scroll

- src/components/checkbox/checkbox-group.vue
##########################
- `bindValue` 값을 computed 로 하여 checkbox-group의 value 가 변경되면 같이 동기화 되도록 수정
> [#1365][2.0] Checkbox Group > bindValue 관련 에러

- src/components/selectbox/dropdown.vue
##########################
- selectedItems 이 없을 때 undefined 에러 발생
> [#1366][2.0] SelectBox > Dropdown update 에러

- docs/views/barChart/api/barChart.md
- docs/views/heatMap/api/heatMap.md
- docs/views/lineChart/api/lineChart.md
- docs/views/scatterChart/api/scatterChart.md
- src/components/chart/Chart.vue
- src/components/chart/model/model.store.js
- src/components/chart/plugins/plugins.interaction.js
- src/components/chart/uses.js
[작업 내용]   
- chart에 mouse-move 이벤트 추가
- location: 현재 커서의 위치 (yAxis, xAxis, chartBackground, canvas)
- dataIdx: chart data의 data에서의 index (default -1)
- maxDataVal: 데이터 값 (x축 기준으로 큰 값 default '')
- labeldIdx: chart data의 label에서의 index (default -1)
- labelVal: 현재 보여지는 라벨의 값 (default '')
- originVal: 가공 하기 전의 chart 데이터 또는 라벨의 값
- horizontal: true도 동일
[적용 범위]
- Bar, Line, Scatter, Combo, HeatMap
> [#1401]Chart > Mouse Move 이벤트 추가

- public/404.html
- public/index.html
- root path가 아닌 menu별 route path로 접근 시에 정상적으로 페이지가 나타날 수 있도록 html 내 script 추가
- Closes #1408
> [#1408] EVUI Document의 Router 기능 개선

- package-lock.json
##########
- github 의 action 에서 npm install 이 필요한데,  package-lock.json 파일의 변경이 없으면 해당 step 이 생략되는 문제
> [#1411] Select > filterable 기능 개선

- docs/views/scatterChart/api/scatterChart.md
##########
- realTimeScatter Description 추가
> [#1410] Chart > Scatter > 실시간으로 대량의 데이터를 처리할 때의 성능 이슈

- docs/views/grid/api/grid.md
- docs/views/grid/example/Default.vue
- src/components/grid/Grid.vue
- src/components/grid/uses.js
- limitCount 옵션 제거
- multi select 모드 일 때 key 를 누르지 않아도 여러 개의 행선택이 가능하도록 변경 (ctrl key + 클릭과 동일하게 동작)
- shift key 기능 추가
```
- Shift + 클릭
- Shist 키를 누른 채 선택할 마지막 행을 클릭하여 연속된 행을 선택할 수 있다.
- Shist 키를 누른 채 이미 선택된 행 클릭 시 마지막 선택한 행을 기준으로 선택한 행까지 선택이 해제된다. (ref. gmail)
- Ctrl + 클릭
- Ctrl 키를 누른 채 선택할 행을 클릭할 수 있다.
- Ctrl 키를 누른 채 이미 선택된 행 클릭 시 해당 행은 선택이 해제된다.
```
> [#1418] Grid > MultiSelect 기능 개선

- docs/views/grid/example/Default.vue
- package.json
- src/components/grid/Grid.vue
- src/components/grid/style/grid.scss
> [#1433] Grid > 정렬 버튼 slot 추가

- docs/views/treeGrid/api/treeGrid.md
- docs/views/treeGrid/example/CellRenderer.vue
- docs/views/treeGrid/example/Default.vue
- docs/views/treeGrid/example/Toolbar.vue
- src/components/treeGrid/TreeGrid.vue
- src/components/treeGrid/TreeGridNode.vue
- src/components/treeGrid/style/treeGrid.scss
- src/components/treeGrid/treeGrid.toolbar.vue
- src/components/treeGrid/uses.js
작업내용
--
- TreeGrid > 컬럼 show/hide 기능 추가
- useColumnmSetting 옵션 추가
- 컬럼 클릭 시, 단일 hide 가능하도록 컬럼 컨텍스트 메뉴 추가
- treeGrid > css 추가 및 cellrender 관련 css 수정
> [#1437] TreeGrid > 컬럼 show/hide 기능 추가

- package.json
- src/components/treeGrid/TreeGridNode.vue
- src/components/treeGrid/style/treeGrid.scss
수정 내용
---
- treeGrid > expand 아이콘 가운데 정렬 안되는 현상이 있어 스타일 수정
Close #1439
> [#1439] TreeGrid > 스타일 수정

- docs/views/grid/example/Default.vue
- src/components/grid/Grid.vue
- src/components/grid/style/grid.scss
- src/components/grid/uses.js
- Row Contextmenu 버튼 slot 추가
- 클릭 이벤트 중복 호출 제어
> [#1442] Grid > Row Contextmenu 버튼 개선

- src/components/grid/Grid.vue
- src/components/grid/uses.js
> [#1455] Grid > Add Column moving

- package.json
- src/components/grid/Grid.vue
- src/components/grid/grid.filterSetting.vue
- src/components/grid/uses.js
- onUpdated 훅에서 grid 너비 가져오기
- contextmenu icon 클릭 시 row 선택/해제
- ev-grid-filter-setting-modal toolbar 밖으로 이동
- useFilter 옵션 false 일 시 비활성화
> [#1460] Grid > Row Funtions Fixes

- src/components/grid/uses.js
####
- 컬럼 show/hide 시, 컬럼 hide 속성은 제외하여 필터링 되도록 수정
> [#1431] Grid > 컬럼 show/hide 기능 버그 수정

- package.json
- src/components/grid/Grid.vue
- src/components/grid/uses.js
- 우클릭 또는 플로팅 버튼을 이용해 Contextmenu 기능을 사용 시, multiple 모드 일 때 클릭 해제되지 않도록 수정
> [#1462] Grid > Contextmenu 관련 클릭 이벤트 수정

- docs/views/grid/example/Default.vue
- package.json
- src/components/grid/grid.filterSetting.vue
- src/components/grid/uses.js
#########################
- 필터링 시 falsy 값 예외 처리
- and 조건 데이터 정상적으로 나오도록 수정
- 최초 한번은 꼭 originStore 기준 필터링
- 조건 add 시 이전에 설정한 operator 값을 가지도록
- boolean 타입 필터 설정 추가
> [#1465] Grid > Filtering Functions Fixes

- package.json
- src/components/grid/Grid.vue
- src/components/grid/grid.filterSetting.vue
- src/components/grid/style/grid.scss
- src/components/grid/uses.js
###################
- 필터가 많을 때 '+n' 으로 표시
- number 타입은 숫자와 마침표만 입력 가능
- 컬럼 사이 operator 셀렉트 대신 텍스트 박스로 표시
- 컬럼 옵션 기능 전체 비활성화 시 contextmenu 제어
- sort 아이콘 호버 시 기본 아이콘 표시 제거
> [#1489] Grid > 필터 영역 표현 방식 개선

- package.json
- src/components/grid/Grid.vue
- src/components/grid/style/grid.scss
> [#1501] Grid > Filtering 기능 사용 시 아이콘 표시

- package.json
- src/components/grid/grid.toolbar.vue
- src/components/treeGrid/treeGrid.toolbar.vue
> [#1503] Grid > 컬럼 옵션 설정 아이콘 위치 조정

- src/components/chart/plugins/plugins.legend.js
- options.legend.stopClickEvt 옵션 추가
- default는 false, true인 경우 click event 막음
> [#1516] Chart > Legend Click 이벤트 방지 옵션 추가

- src/components/datepicker/calendar.core.js
*   DatePicker 상 Arrow 셀렉터가 너무 작거나, HOVER 감지영역이 너무 좁아서 사용에 문제가 있었습니다.
*   DatePicker 상 Arrow 셀렉터의 hover 감지로직을 변경하여, hover의 유무 판단 영역을 넓히는 것이 효율적이라 판단했습니다.
*   `calendar.core.js` 를 분석하고, canvas에 삼각형을 그리는 함수 & Hover 감지 및 대응로직 & highlight를 해주는 삼각형을 그리고 destroy하는 신규 로직을 구현했습니다.
*   삼각형을 그리는 함수 & 호버 감지 함수의 로직을 개선하기 위한 REFACTORING 작업을 수반했습니다.
> [2.0] datePicker Arrow usage 를 위한 수정 & Refactoring

- src/components/datepicker/calendar.core.js
*   DatePicker 상 Arrow 셀렉터의 hover Highlight 색깔이 배경에 따라 가시적이지 않은 문제가 있었습니다.
*   `calendar.core.js` 내부에 Hover 감지 후 highlight를 해주는 로직을 수정하여, theme에 맞는 컬러로 highlight 기준컬러를 변경하도록 했습니다.
> 2.0 date picker arrow highlight refac

- docs/views/barChart/api/barChart.md
- docs/views/heatMap/api/heatMap.md
- docs/views/lineChart/api/lineChart.md
- docs/views/lineChart/example/Tooltip.vue
- docs/views/pieChart/api/pieChart.md
- src/components/chart/plugins/plugins.tooltip.js
- src/components/chart/uses.js
- Tooltip의 Header영역 숨김/보임 기능 
- showHeader( default: true)
> [#1604] Chart > tooltip > showHeader 옵션 추가

- docs/views/grid/api/grid.md
- docs/views/grid/example/RowDetail.vue
- package-lock.json
- package.json
- src/components/grid/Grid.vue
- src/components/grid/uses.js
column의 width가 변경되었을때, 어떤 컬럼이 어떻게 변경되었는지 알려주는 event가 필요했습니다.
```ts
const handleMouseUp = () => {
const destLeft = parseInt(resizeLineEl.style.left, 10);
const changedWidth = destLeft - startColumnLeft;
if (stores.orderedColumns[columnIndex]) {
stores.orderedColumns[columnIndex].width = changedWidth;
stores.orderedColumns.map((column) => {
const item = column;
item.resized = true;
return item;
});
}
resizeInfo.showResizeLine = false;
document.removeEventListener('mousemove', handleMouseMove);
onResize();
emit('resize:column', stores.orderedColumns[columnIndex]); // 계산 후 emit하는 로직 추가
};
```
> [#1608] grid resize column event

- package.json
> [#1635] Update Version (3.4.40)

- docs/views/grid/api/grid.md
- docs/views/grid/example/Disabled.vue
- docs/views/grid/props.js
- src/components/grid/Grid.vue
- src/components/grid/style/grid.scss
- src/components/grid/uses.js
큰 기능은 없고, disabled-row를 받아서
disabled attribute를 적용해준다는 작업만 진행했습니다.
> [#1649]Grid > Disabled-row 추가

- docs/views/grid/api/grid.md
- docs/views/grid/example/Disabled.vue
- package.json
- src/components/grid/Grid.vue
- src/components/grid/uses.js
> [#1649]Grid > Disabled html 속성과 이름 겹치는 문제

- src/components/grid/Grid.vue
- src/components/grid/uses.js
- src/components/treeGrid/uses.js
- 컬럼셋팅 메뉴명, title columnMenuText 로 설정될 수 있도록 수정
> [#1674] Grid > Option useGridSetting.columnMenuText 적용되지 않는 현상 수정

- package.json
- src/components/treeGrid/uses.js
- Tree Grid  redraw시, 간혈적으로 element가 없는 현상 발생 
- ![image](https://github.com/ex-em/EVUI/assets/53548023/4bf025c2-513f-48a9-a340-aae87db4d8c8)
- ![image](https://github.com/ex-em/EVUI/assets/53548023/a0b203b9-b0cf-4c58-a162-77134b4b216a)
- 조건문 수정
- version update
> [#1693] TreeGrid > undefined bug fix
